### ISSUE TITLE
minimum_should_match not working as expected in case of fields containing synonyms

### ISSUE THREAD

**Issue by mallikarjuna91** [elasticsearch/elasticsearch#10001]
Here is my settings and mappings

Settings

    PUT test3
    {
      "settings": {
        "analysis": {
          "analyzer": {
            "my_analyzer": {
              "filter": [
                "lowercase",
                "english_stemmer",
                "my_synonyms"
              ],
              "tokenizer": "standard"
            }
          },
          "filter": {
            "my_synonyms": {
              "type": "synonym",
              "synonyms" : [
                    "image, image skincare"
                ]
            },
            "english_stemmer": {
              "type": "stemmer",
              "language": "light_english"
            }
          }
        }
      }
    }

Mappings

    PUT test3/type/_mapping
    {
      "type": {
        "properties": {
          "name": {
            "type": "string",
            "analyzer": "my_analyzer"
          }
        }
      }
    }

Data insertion

    POST /test3/data/_bulk
    {"index":{"_id":4}}
    {"name":["image skincare"]}

Here goes the search query. Irrespective of whatever i give in the second word, query is giving results, though that word is not there in the data itself and when there is 100% match.
Same results even when I change the operator to "and"  

My elastic search version is 1.3.4

    GET test3/_search?size=100
    {
      "query": {
        "multi_match": {
          "query": "image SOMETHINGHERE",
          "fields": [
            "name"
          ],
          "minimum_should_match":"100%",
          "tie_breaker": 0.2
        }
      }
    }

**Comment by clintongormley** [comment]
Hi @mallikarjuna91 

The reason for this is revealed by doing a validate-query request, which returns:

    "+(name:image name:image) +(name:somethinghere name:skincare)"

The term `image` is being expanded by your synonyms filter to `[ [image,image], [skincare] ]`, and "skincare" is in the same position as whatever other query term is specified, so both positions always match.

You have to be very careful with multi-word synonyms.  I suggest having a read of this chapter: http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/synonyms.html
