### ISSUE TITLE
Filtering term with "_" doesn't work

### ISSUE THREAD

**Issue by limabetalabs** [elasticsearch/elasticsearch#10006]
I'm trying to make a query like this:

{
  "query" :{
    "filtered" :{
      "query" :{
          "multi_match" : {
            "query" : "Vonder Carregador de Baterias CBV 0900 - 110V",
            "fields" : [ "nome^10", "descricao" ],
            "operator" : "or"
          }
       },
       "filter" : {
         "bool" : {
           "must" : [
             {"term" : { "ativo" : 1 }},
             {"term" : {"id_instancia": "Master_cleaner"}},
           ]
         }
       }
     }
   }
}
But when I filter some term with "_" it doesn't work.

**Comment by s1monw** [comment]
please use the mailing list for questions like this. The issue tracker is only for bugs and features. 

thanks!
