### ISSUE TITLE
index disappearing issue on 1.4.4

### ISSUE THREAD

**Issue by kwongb98** [elasticsearch/elasticsearch#10009]
Hi there, I'm using elasticsearch v1.4.4 (oracle jvm 1.7.0_75) but strange issues occurred.

I have a index which consists of one parent doc type and 25 different types of child doc type. 
After create index 400 billion documents, garbage collect did't work and elasticsearch was terminated abnormally.

![image](https://cloud.githubusercontent.com/assets/9878011/6521399/b2a72de0-c41a-11e4-9400-6905882c666e.png)

After restart a elasticsearch, all 400 billion document are missing.

I was checked a hprof dump file and finded out a retain memory of org.apache.lucene.store.RAMFile was 29G.

![image](https://cloud.githubusercontent.com/assets/9878011/6521402/bad87910-c41a-11e4-9583-bd6c4658e1e7.png)

is there any connection between parent-child document and retain memory of org.apache.lucene.store.RAMFile?

And I wonder why documents were disappeared.

Let me know if you need more information.

**Comment by s1monw** [comment]
can I see some of your configurations ie. what kind of store do you use? Are you using ` "index.store.type": "memory"` by any chance?

**Comment by kwongb98** [comment]
Oops,  I set "index.store.type": "memory" as you expect...
thank you, for your advice

**Comment by s1monw** [comment]
thanks for clarifying.. we removed it in 1.5 actually to prevent these problems
