### ISSUE TITLE
Settings = 3 Shards => Result = 5 shards

### ISSUE THREAD

**Issue by ZeAleks** [elasticsearch/elasticsearch#10012]
Hi there,

I don't know if it is really an issue or if it is a misconfiguration on my side but here is my problem.
I configured an index settings that way :

GET iislog/_settings
{
   "iislog": {
      "settings": {
         "index": {
            "creation_date": "1425458515905",
            "number_of_shards": "3",
            "number_of_replicas": "1",
            "version": {
               "created": "1040299"
            },
            "uuid": "FJrBfCRkSR-bh3HUlmC4Ww"
         }
      }
   }
}

But, I just realized that, in fact, there is 5 shards :

GET _cat/shards
iislogs    4 p INITIALIZING                  127.0.0.1 S3DEV-BI-ES09 
iislogs    4 r UNASSIGNED                                            
iislogs    0 p STARTED      15864679   5.3gb 127.0.0.1 S3DEV-BI-ES08 
iislogs    0 r UNASSIGNED                                            
iislogs    3 p STARTED      15999341   9.2gb 127.0.0.1 S3DEV-BI-ES09 
iislogs    3 r UNASSIGNED                                            
iislogs    1 p STARTED      15819303   5.2gb 127.0.0.1 S3DEV-BI-ES08 
iislogs    1 r UNASSIGNED                                            
iislogs    2 p STARTED      15986204   5.5gb 127.0.0.1 S3DEV-BI-ES10 
iislogs    2 r UNASSIGNED 

Notice that I recently deleted this index and recreated it. It was initialy having 5 shards but I always get and unassigned shard (the first one). So I decided to reconfigure it with only 3 shards.

I will keep this index today if you need more inputs but I will need to recreate it before the week-end begin. 

Thank you for your help
Alek

**Comment by s1monw** [comment]
hey Alek, you pasted `GET iislog/_settings` but cat shows an index called `iislogs` <== note the plural `s`? does it matter?

**Comment by ZeAleks** [comment]
Hi Simon,

I really feel stupid now :(

Thank you !

**Comment by s1monw** [comment]
no worries, thanks for reporting back
