### ISSUE TITLE
ElasticSearch fails when kibana makes request over https

### ISSUE THREAD

**Issue by 91pavan** [elasticsearch/elasticsearch#10050]
Apache2 has SSL module on to make connections to localhost over https

Kibana config:

```
elasticsearch: "https://localhost:9200",
```
ElasticSearch config:

```
http.cors.enabled: true
http.cors.allow-origin: /https?:\/\/localhost/

```

When we access kibana over https, we get all types of exceptions:

```
Caught exception while handling client http traffic, closing connection [id: 0x18a54cf5, /10.127.153.212:55525 => /173.39.242.2:9200]
java.lang.IllegalArgumentException: empty text
```

```
Caught exception while handling client http traffic, closing connection [id: 0xa5767d95, /10.127.153.212:55489 :> /173.39.242.2:9200]
java.lang.IllegalArgumentException: invalid version format: ﾽﾅFﾵﾖ;ﾓﾳ￫￀
```

Any help much appreciated.

**Comment by 91pavan** [comment]
Sorry guys for opening the issue, managed to fix it by replacing the localhost part with actual IP of the machine!

Closing this one!

**Comment by sureshrv83** [comment]
I have added below to elastic search config , still get the same exceptions.
http.cors.enabled: true
http.cors.allow-origin: /https?:\/\/localhost/

However http://localhost:9200 works but https://localhost:9200 doesn't work!

Can you please help ? Is there config that I'm missing in elasticsearch ?
