### ISSUE TITLE
Bound the number of search results returned by elasticsearch

### ISSUE THREAD

**Issue by nicktgr15** [elasticsearch/elasticsearch#4026]
Hello,

When making a search request (post) like the following to elasticsearch using kibana I get a java heap space error and my elasticsearch node can't recover. 

{"query":{"filtered":{"query":{"bool":{"should":[{"query_string":{"query":"*"}}]}},"filter":{"bool":{"must":[{"match_all":{}},{"bool":{"must":[{"match_all":{}}]}}]}}}},"highlight":{"fields":{},"fragment_size":2147483647,"pre_tags":["@start-highlight@"],"post_tags":["@end-highlight@"]},"size":<b>1000000</b>,"sort":[{"_id":{"order":"desc"}}]}

<b>Question</b>: Is it possible to somehow restrict the maximum value of "size" that someone can use? In general, Is it possible to bound the number of results returned by elasticsearch to avoid out of memory errors?

I don't want to increase the heap size (currently 1gb) as this would not solve the problem.

Regards,
Nick

**Comment by clintongormley** [comment]
Closing in favour of #9311
