### ISSUE TITLE
If lots of large shards fill up the disk on one node then the cluster won't properly rebalance shards

### ISSUE THREAD

**Issue by nik9000** [elasticsearch/elasticsearch#4790]
If lots of large shards fill up the disk on one node then the cluster won't properly rebalance shards.  It won't move large shards from the full node to less full nodes - it'll grab shards on the less full nodes and swap them back and forth.

**Comment by clintongormley** [comment]
This issue appears to be stale. Please feel free to open a new ticket if you see issues with the disk decider again.
