### ISSUE TITLE
Check if term exists

### ISSUE THREAD

**Issue by Kamapcuc** [elasticsearch/elasticsearch#4880]
For example i have two different analyzers. And i made two "_suggest" requests:
<pre>
{
  "PRODUCT": {
    "text" : "hammer",
    "term" : {
      "field" : "name",
      "suggest_mode": "missing",
    }
  }
}
</pre>
If both requests returns me some options: [...], then i will choose option with max score (similarity) and send to user did you mean "..."?
But what will be my decision if one of requests returns options, and second is not? Does it mean, that term exists and user input is correct and i don't need to bother user with "did you mean" from options from first request. Or it means that there is no such term in index with second analyzer, so i ought to fix misprint with options from first request?

Can you add such functionality, or maybe it already exists?

**Comment by clintongormley** [comment]
No more info provided. Closing
