### ISSUE TITLE
relocating replicas displays wrong information

### ISSUE THREAD

**Issue by faxm0dem** [elasticsearch/elasticsearch#5045]
It seems that a system where a node has been excluded using "shard allocation filtering", the information as given by the rest API is wrong. The cluster in this example is composed of 3 nodes, and NodeB has been filtered
````
$ es shards | awk '$1 == "webclusterlogs-2014.02.04" && $2 == 5 { print }'
webclusterlogs-2014.02.04               5 p STARTED       84661  78.7mb    82580177 134.158.108.171 NodeA
webclusterlogs-2014.02.04               5 r RELOCATING    84661  78.7mb    82578811 134.158.108.25  NodeB -> 134.158.104.214 NodeC
````

How could the data come from NodeB when it doesn't host the shard? Also, when monitoring network activity, it is clear that it is in fact NodeA sending the data to NodeC

Version is from rpm distribution elasticsearch-0.90.10-1.noarch on NodeA and NodeB, and elasticsearch-0.90.7-1.noarch on NodeC

**Comment by clintongormley** [comment]
No more info. Closing
