### ISSUE TITLE
Add support for matching mode when attaching REST handlers

### ISSUE THREAD

**Issue by templth** [elasticsearch/elasticsearch#5191]
At the moment, ElasticSearch does a matching mode `equals` when attaching REST handlers using the method `RestController#registerHandler`:

    	@Inject
	public MyRestHandler(Settings settings, Client client, RestController controller) {
		super(settings, client);

		// Define REST endpoints
		controller.registerHandler(Method.GET, "(...)",this);

In some cases, it's not suitable since we would want to attach an handle on a subset of URIs. For such cases, the matching mode `starts with` would be more suitable:

    controller.registerHandler(Method.GET, "/myuri",
                       RestMatchingMode.STARTS_WITH, this);

This means that all sub URIs (like `/myuri/segment1`, `/myuri/segment2/segment3/segment4`, and so on) would handle by the same class. This would be useful if we want manage URIs in a custom way (URI format, ...) that isn't supported by ElasticSearch. This is typically the case for OData URIs.

To implement such feature, we need to add an enumeration to list all support matching modes:

    public enum RestMatchingMode {
        EQUALS, STARTS_WITH
    }

We also need to update the `RestController` to add the corresponding methods:

    public void registerHandler(RestRequest.Method method,
                                          String path, RestHandler handler) {
        registerHandler(method, path, RestMatchingMode.EQUALS, handler);
    }

    public void registerHandler(RestRequest.Method method, String path,
                                         RestMatchingMode matchingMode, RestHandler handler) {
        (...)
    }

As the matching is handled by the classes `PathTrie` and `TreeNode`, we need to add in it the support of matching mode at both methods insert and retrieve.

    public synchronized void insert(String[] path, int index,
                         RestMatchingMode matchingMode, T value) {
       (...)
       TrieNode<T> node = children.get(key);
       if (node == null) {
            if (index == (path.length - 1)) {
                node = new TrieNode<T>(token, value, this, wildcard, matchingMode);
            } else {
                node = new TrieNode<T>(token, null, this, wildcard, RestMatchingMode.EQUALS);
            }
            children = newMapBuilder(children).put(key, node).immutableMap();
        (...)
    }

    public T retrieve(String[] path, int index, Map<String, String> params) {
        (...)
        if (index == (path.length - 1)) {
            return node.value;
        }

        // In the case of starts with matching, return the value
        if (RestMatchingMode.STARTS_WITH.equals(node.getMatchingMode())) {
            return node.value;
        }
        (...)

Moreover we simply need to add the property matchingMode in the class TreeNode

    public class TrieNode<T> {
        (...)
        private RestMatchingMode matchingMode; 
        (...)

        public TrieNode(String key, T value, TrieNode parent, String wildcard,
                                   RestMatchingMode matchingMode) {
            this.key = key;
            this.wildcard = wildcard;
            this.isWildcard = (key.equals(wildcard));
            this.parent = parent;
            this.value = value;
            this.children = ImmutableMap.of();
            this.matchingMode = matchingMode;
            (...)
        }
        (...)
    }

**Comment by templth** [comment]
@clintongormley Just got the permission from my company! I signed the CLA as an individual contributing under an existing company contributor agreement. I'll check if my company signed its one...

**Comment by templth** [comment]
@clintongormley My company told me that they sign the company CLA ;-)

**Comment by jpountz** [comment]
Closed (see #7923)
