### ISSUE TITLE
Plugin isolation

### ISSUE THREAD

**Issue by costin** [elasticsearch/elasticsearch#5261]
For 1.x, we talked about having class space isolated between plugins so their dependencies don't interact with each other.
To solve this issue, a parent-last `ClassLoader` will be used meaning that each plugin can be loaded into its own `ClassLoader` which will first try to load classes from itself (meaning the plugin class space) and only then fall back to its parent, or the Elasticsearch `ClassLoader`.

Under the current enhancement can have an additional `property` in its `es-plugin.properties` called `isolation` which indicates whether the plugin requires its own class space or not. As of now, all existing plugins lack the property which means the default ES settings will be applied.
ES provides a new setting, `plugin.isolation` which indicates the behaviour to use for plugins that do not specify any isolation. By default this would be true but can be changed to false to revert to the default / 1.0 behaviour.

By enabling isolation out of the box, we theoretically prevent any clashing problems regarding the classpath and at the same time, keep a close eye on problematic plugins. If they appear, folks can turn off `plugin.isolation` (by setting it to false) or simply cherry pick the problematic plugin and configure no isolation for it.

**Comment by salyh** [comment]
Will plugin isolation be targeted for 2.0?

**Comment by clintongormley** [comment]
@salyh I think we've pretty much given up on this idea.  Proved too tricky.

**Comment by jprante** [comment]
Hint: in my deploy plugin, I use classloader isolation https://github.com/jprante/elasticsearch-plugin-deploy

**Comment by nik9000** [comment]
> Hint: in my deploy plugin, I use classloader isolation https://github.com/jprante/elasticsearch-plugin-deploy

Nice!  I think its worth doing if 2.0 doesn't have work to significantly speed up rolling restarts.  I (almost) only care about plugin isolation for reloading and I only care about that because rolling restarts take many many hours.

**Comment by salyh** [comment]
People from apache karaf (and me) thinking about introducing OSGI to elasticsearch for this and other purposes
