### ISSUE TITLE
OSGI ClassLoader

### ISSUE THREAD

**Issue by boliza** [elasticsearch/elasticsearch#6096]
> public static ClassLoader getDefaultClassLoader() {
        ClassLoader cl = null;
        try {
            cl = Thread.currentThread().getContextClassLoader();
        } catch (Throwable ex) {
            // Cannot access thread context ClassLoader - falling back to system class loader...
        }
        if (cl == null) {
            // No thread context class loader -> use class loader of this class.
            cl = Classes.class.getClassLoader();
        }
        return cl;
    }

in osgi the ClassLoader is incorrect。

for example I usring titan0.4.4 with elasticsearch 0.9.5，when elasticsearch throw exception ,sometimes can't load the class Remotetransportexception.

So can provide an interface to set it

**Comment by clintongormley** [comment]
No more info. Closing
