### ISSUE TITLE
Multiple threads creating and closing connections results in random org.elasticsearch.client.transport.NoNodeAvailableException

### ISSUE THREAD

**Issue by jaysonminard** [elasticsearch/elasticsearch#6316]
I have code that has worked consistently well on 1.0.0.RC1 of ES but dies often on 1.1.1 ... it basically has a thread pool of workers doing long running scan/scroll queries (with "_shards:N;_local") and each creates its own TransportClient connection at the start of a run, and closes it at the end.  A finally block guarantees the close is run.  

First, after a bunch of connections are used, somewhere along the way a thread picks up new work item and creates a new transport client and uses the client the first time it causes a  org.elasticsearch.client.transport.NoNodeAvailableException when executing the query for the first time.  The cluster health is fine at the time.  No logs, or errors in any cluster node, cluster state shows healthy, no recovery, index is static at the time with no updates.

The same code worked flawlessly with 1.0.0.RC1 and now fails consistently and quickly, but not repeatable enough to see that it is some specific case in the code, more likely some race condition with the closing of a past connection, opening of new, and the timing of the first query.  Adding pauses seems silly, and 1 second after close and 1 second after open do not resolve it anyway.

Second issue that is new, is that I now also get Netty errors java.lang.OutOfMemoryError: Direct buffer memory with direct memory set to 1G and all connection open/close protected by try..finally blocks so nothing should be leaking.

It appears the creation and closing of TransportClients at higher volume does not bode well for ES at the moment.  I create the clients because I am doing large data extracts from different nodes and shards and am keeping nodes that do not need to be involved from participating for each shard, and previously had issues with clients timing out if they were in a pool and unused for a long time.  But regardless of pooling, there shouldn't be a leak or a break (exception) with create/close connections.

I have noticed this newer StackOverFlow issue as well which seems very similar:
http://stackoverflow.com/questions/23739137

And before people comment "use one client and share for all threads" ... I know that the clients can be used in that way, but I am still worried about this bug and resource leak and this issue is about those, not about designing how this code works.

**Comment by opgalarza** [comment]
Hi @clintongormley,

We are currently facing this issue in our environment. We have a cluster of 4 machines. 1 of them functions as a master and the 3 others as data nodes.  In our code, we spawn 10 threads and each one gets a client instance as follows

run method in the thread

@Override
	public void run() {
		Client client = ESClient.getClient(clusterName,hostName,port);

		List<String> errors = new ArrayList<String>();
		String indexName = outputInfo.getElasticSearch().getIndexName();
		String typeName = outputInfo.getElasticSearch().getTypeName();
		
		for(Map<String, Object> recordToPersist: recordsToPersist){	
			String line = Utils.getJsonFromObject(recordToPersist);
			try{
				ESService.putDocument(client, line, indexName, typeName);
			} catch(Exception e){
				errors.add(line);
			}
		}
    	if(!errors.isEmpty()){
    		logErrors(errors,outputInfo.getElasticSearch().getErrorLogFile());
    	}
	}


This is the putDocument method implementation :+1: 
	public static IndexResponse putDocument(Client client, String jsonString, String indexName, String typeName) {	
		IndexResponse indexResponse = client.prepareIndex(indexName, typeName).setSource(jsonString).execute().actionGet();		
		return indexResponse;
	}

and at some point we get the following exception :+1: 

org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:278)
at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:197)
at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106)
at org.elasticsearch.client.support.AbstractClient.index(AbstractClient.java:98)
at org.elasticsearch.client.transport.TransportClient.index(TransportClient.java:334)
at org.elasticsearch.action.index.IndexRequestBuilder.doExecute(IndexRequestBuilder.java:313)
at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
at com.manwin.cloud.service.ESService.putDocument(ESService.java:39)
at com.manwin.cloud.elasticsearch.ElasticSearchPersistentWorker.run(ElasticSearchPersistentWorker.java:85)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:722)

We are using elasticsearch version 1.4.1. Hope this helps. In case you need more information please let me know.

Cheers
Omar

**Comment by clintongormley** [comment]
@opgalarza presumably your nodes are being overwhelmed by the indexing requests - you want to look at the cluster logs, rather than the client logs.

**Comment by opgalarza** [comment]
Ok @clintongormley , I will check that part in the cluster logs and keep you posted.

Cheers
Omar

**Comment by jaysonminard** [comment]
My code had no indexing other way, was read-only on the index.

**Comment by jaysonminard** [comment]
and I'm not on that client project so would have to start from scratch to re-create a scenario ... too much time has passed.

**Comment by clintongormley** [comment]
@jaysonminard yeah - i'm thinking that this issue has been resolved.  @opgalarza 's description sounds like a different problem.  thanks for getting back to us and sorry for the long delay :)
