### ISSUE TITLE
Deprecate extracting _routing and _id from document fields

### ISSUE THREAD

**Issue by clintongormley** [elasticsearch/elasticsearch#6730]
Currently routing and ID values can be passed in the query string and url respectively, but they can also be extracted from fields within the document.

This has a significant performance impact because each doc needs to be parsed on the node which receives the index/get/update/delete request in order to know which node should handle the request.

On top of that, there are clashes between (eg) routing values set in fields and parent settings.

We should deprecate the functionality to extract these values from fields, and make it the responsibility of the client code instead.

It should still be possible to set `_routing` to required.  Perhaps we should set this automatically if the user ever passes in a routing or parent value at index time?

Relates to #8870

**Comment by ostefano** [comment]
Can someone confirm me that this is why `copy_to` inside `_id` mappings does not currently work?

**Comment by rjernst** [comment]
This change was made only to master. As far as I can tell, `copy_to` was never supported for the `_id` field.

**Comment by celesteking** [comment]
I had to dig through the bloat over internet in order to get to this information. You should really **DOCUMENT**  that [there will be no substitution for ```path```](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html#_path) and that ```copy_to``` can't be used to "extract" ```_id```.

**Comment by itsnavee** [comment]
is there an alternative to using your own ID to avoid duplicate record publishing
