### ISSUE TITLE
unable to re-nest on same field after reverse nesting 

### ISSUE THREAD

**Issue by Kallin** [elasticsearch/elasticsearch#7038]
I'm having trouble performing a certain aggregation on a nested field.

I have a field of nested type, that holds an array of object. What I want to do is this:

Aggregate on the field to find all the nested documents that contain a certain value, then reverse-nest back to the root, giving me the entire set of root documents which have the nested field object I'm looking for.

Then, further aggregate on that set of documents, against the same nested field, this time against a different value. 

The purpose is to build something like a funnel, where I keep narrowing down the aggregation with more and more criteria, based on that nested field.

What appears to happen though is that when perform my second nested agg, itself with a nested->reverse_nested agg, it looks as though it can't see any of nested fields anymore. If you run this simple CURL, looks at the value of 'into_nested_again'. It's 0, but it should be 3, just like the value of the original 'into_nested' agg. 

```
curl -XDELETE "http://localhost:9200/nested-test"

curl -XPUT "http://localhost:9200/nested-test" -d'
{
  "mappings": {
    "my_type": {
      "properties": {
        "my_nested_field": {
          "type": "nested"
       }
      } 
       
    }
  }
}'

curl -XPOST "http://localhost:9200/nested-test/my_type" -d'
{
  "my_nested_field" : [
    {
      "my_key": "value1"
    }
  ]
}'

curl -XPOST "http://localhost:9200/nested-test/my_type" -d'
{
  "my_nested_field" : [
    {
      "my_key": "value1"
    },
    {
      "my_key": "value2"
    }
  ]
}'

curl -XGET "http://localhost:9200/nested-test/_search" -d'
{
  "aggs": {
    "into_nested": {
      "nested": {
        "path": "my_nested_field"
      },
      "aggs": {
        "by_value1": {
          "filter": {
            "term": {
              "my_nested_field.my_key": "value1"
            }
          },
          "aggs": {
            "by_parent": {
              "reverse_nested": {}
              , "aggs": {
                "into_nested_again": {
                  "nested": {
                    "path": "my_nested_field"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}'
```

**Comment by martijnvg** [comment]
@Kallin Running your example on version 1.4.2 does produce the results you expect. (into_nested_again has doc_count 3) . 

I don't know what version you were using back then, but if the problem still occurs then please re-open this issue.
