### ISSUE TITLE
Proper Debian repository

### ISSUE THREAD

**Issue by jlecour** [elasticsearch/elasticsearch#7883]
Hi,

I've been using Elasticsearch in production for a couple of years, a various Debian (stable) servers.

I really appreciate having a .deb available on your website, and I've cooked myself a small script to upgrade when a new version is released.

It would be even more awesome if you had [a proper Debian repository](https://wiki.debian.org/HowToSetupADebianRepository) set up. We'd have to add it in our `sources.list` file and upgrading would be even easier than it is now.

I'm not familiar with the amount of work necessary for setting up such a repository, but I'm pretty sure all your Debian and Ubuntu users would be pleased and a few of them might even offer help.

I hope you won't file this in the "Unfulfilled Promises and Broken Dreams" [category](https://github.com/rubygems/rubygems/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Unfulfilled+Promises+and+Broken+Dreams%22).

Thanks a ton for making Elasticsearch et al.

**Comment by clintongormley** [comment]
Closing this issue for now.  Feel free to reopen if you want to revive this topic
