### ISSUE TITLE
Duplicate document found while searching with parent/child setup - ES 1.0

### ISSUE THREAD

**Issue by govindm** [elasticsearch/elasticsearch#8003]
elasticsearchserver_node1:7104/metadata/asset/_search?q=_id:641804  returns two documents
But
elasticsearchserver_node1:7104/metadata/asset/641804?parent=80018039 returns only one document

There was not update to the document after initial index.

elasticsearchserver_node1:7104/metadata/asset/_search?q=_id:641804 returns following results

=========

{
    "took": 2,
    "timed_out": false,
    "_shards": {
        "total": 10,
        "successful": 10,
        "failed": 0
    },
    "hits": {
        "total": 2,
        "max_score": 1,
        "hits": [
            {
                "_index": "metadata",
                "_type": "asset",
                "_id": "641804",
                "_score": 1,
                "_source": {
                    "createdDate": 1410901296000,
                    "lastUpdatedDate": 1410901295989,
                    "id": 641804,
                    "status": "NEW",
                    "parentAssetId": 0,
                    "masterAssetId": null,
                    "source": "AUTOMATION",
                    "spaceCode": "creative-services",
                    "originatingAssetId": null,
                    "spaceShareCount": null,
                    "childCount": null,
                    "isAllMainFilesPresent": false,
                    "assetPath": [],
                    "assetExtension": {
                        "assetId": 641804,
                        "territoryCode": "LATAM",
                        "languageCode": null,
                        "partnerProvidedLocalizedName": null,
                        "personId": 0,
                        "characterId": 0
                    },
                    "assetFiles": [],
                    "assetAttributes": [],
                    "sharedSpaceCodes": [],
                    "futureEffectiveDate": null,
                    "assetWindows": [
                        {
                            "partnerId": "dcbd39e0-eff9-11e2-882e-12313924e0a4",
                            "windowStartDate": 1416016800000,
                            "windowEndDate": 1463281200000
                        }
                    ],
                    "assetSchema": "asset",
                    "slaveAsset": false,
                    "publishedDerivativePresent": false,
                    "sharedAcrossSpace": true,
                    "mainFiles": [],
                    "folderTypeAsset": false,
                    "genericAsset": false,
                    "metaTypeAsset": true,
                    "metaId": 80018039,
                    "sourceFiles": [],
                    "futurePublishedDerivativePresent": false,
                    "characterAsset": false,
                    "personAsset": false,
                    "masterAsset": false,
                    "timestamp": 1410901295989,
                    "_parent": "80018039"
                }
            },
            {
                "_index": "movie_metadata",
                "_type": "asset",
                "_id": "641804",
                "_score": 1,
                "_source": {
                    "_index": "metadata",
                    "_type": "asset",
                    "_id": "641804",
                    "_score": 1,
                    "_source": {
                        "createdDate": 1410901296000,
                        "lastUpdatedDate": 1410901295989,
                        "id": 641804,
                        "status": "NEW",
                        "parentAssetId": 0,
                        "masterAssetId": null,
                        "source": "AUTOMATION",
                        "spaceCode": "creative-services",
                        "originatingAssetId": null,
                        "spaceShareCount": null,
                        "childCount": null,
                        "isAllMainFilesPresent": false,
                        "assetPath": [],
                        "assetExtension": {
                            "assetId": 641804,
                            "territoryCode": "LATAM",
                            "languageCode": null,
                            "partnerProvidedLocalizedName": null,
                            "personId": 0,
                            "characterId": 0
                        },
                        "assetFiles": [],
                        "assetAttributes": [],
                        "sharedSpaceCodes": [],
                        "futureEffectiveDate": null,
                        "assetWindows": [
                            {
                                "partnerId": "dcbd39e0-eff9-11e2-882e-12313924e0a4",
                                "windowStartDate": 1416016800000,
                                "windowEndDate": 1463281200000
                            }
                        ],
                        "assetSchema": "asset",
                        "slaveAsset": false,
                        "publishedDerivativePresent": false,
                        "sharedAcrossSpace": true,
                        "mainFiles": [],
                        "folderTypeAsset": false,
                        "genericAsset": false,
                        "metaTypeAsset": true,
                        "metaId": 80018039,
                        "sourceFiles": [],
                        "futurePublishedDerivativePresent": false,
                        "characterAsset": false,
                        "personAsset": false,
                        "masterAsset": false,
                        "timestamp": 1410901295989,
                        "_parent": "80018039"
                    }
                }
            }
        ]
    }
}

========

elasticsearchserver_node1:7104/metadata/asset/641804?parent=80018039  returns the following result

{
    "_index": "movie_metadata",
    "_type": "asset",
    "_id": "641804",
    "_version": 1,
    "found": true,
    "_source": {
        "createdDate": 1410901296000,
        "lastUpdatedDate": 1410901295989,
        "id": 641804,
        "status": "NEW",
        "parentAssetId": 0,
        "masterAssetId": null,
        "source": "AUTOMATION",
        "spaceCode": "creative-services",
        "originatingAssetId": null,
        "spaceShareCount": null,
        "childCount": null,
        "isAllMainFilesPresent": false,
        "assetPath": [],
        "assetExtension": {
            "assetId": 641804,
            "territoryCode": "LATAM",
            "languageCode": null,
            "partnerProvidedLocalizedName": null,
            "personId": 0,
            "characterId": 0
        },
        "assetFiles": [],
        "assetAttributes": [],
        "sharedSpaceCodes": [],
        "futureEffectiveDate": null,
        "assetWindows": [
            {
                "partnerId": "dcbd39e0-eff9-11e2-882e-12313924e0a4",
                "windowStartDate": 1416016800000,
                "windowEndDate": 1463281200000
            }
        ],
        "assetSchema": "asset",
        "slaveAsset": false,
        "publishedDerivativePresent": false,
        "sharedAcrossSpace": true,
        "mainFiles": [],
        "folderTypeAsset": false,
        "genericAsset": false,
        "metaTypeAsset": true,
        "metaId": 80018039,
        "sourceFiles": [],
        "futurePublishedDerivativePresent": false,
        "characterAsset": false,
        "personAsset": false,
        "masterAsset": false,
        "timestamp": 1410901295989,
        "_parent": "80018039"
    }
}

====

**Comment by clintongormley** [comment]
There's a good chance this was related to this issue: https://github.com/elasticsearch/elasticsearch/issues/8788

I'll close this one for now, feel free to reopen if you see the same thing on v1.4.4 or above.

thanks
