### ISSUE TITLE
dynamic parser tries to handle empty string as date or time

### ISSUE THREAD

**Issue by kritik** [elasticsearch/elasticsearch#8022]
I have no mapping and data is 
```json
{
internal_fields: {
  date-of-last-physical: [""]
}
}
```

Sometimes I get an error
```json
{"error"=>
  "MapperParsingException[failed to parse [internal_fields.date-of-last-physical]]; nested: MapperParsingException[failed to parse date field [], tried both date format [dateOptionalTime], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: \"\"]; ",
 "status"=>400}
```

I think it shouldn't fail on empty string as it is empty string and cannot be any date :)
ES 1.3.2

**Comment by brwe** [comment]
@kritik I cannot reproduce this. Can you give more details on what you do?

**Comment by kritik** [comment]
Sorry, but not any more.  We converted this stuff form ES to PostgreSQL JSON, as we had really big models and after some data inserted next ES were very slow. Mapping was switched off.

Closing this issue? May be it was connected  to specific version and not existing in repo any more?
