### ISSUE TITLE
Add option to increase maxDeterminizedStates in Lucene

### ISSUE THREAD

**Issue by mikemccand** [elasticsearch/elasticsearch#8357]
With https://issues.apache.org/jira/browse/LUCENE-6046 (to be in 4.10.3, once it's eventually released) we added protection to the various APIs (AutomatonQuery, RegexpQuery, etc.) that attempt to determinize an automaton, to give up when too many states would be created (e.g. the "exponential" worst-cases) instead of trying to consume tons of RAM/CPU.

The default limit is 10,000 states, but there could be real use cases that need a higher limit.

Once 4.10.3 is released and we've upgraded we need to expose control for this new limit in Elasticsearch's rest/client APIs when creating automaton queries.

**Comment by mikemccand** [comment]
Now that 4.10.3 is released, and a user on ES list hit an Automaton bug fixed 4.10.3 (https://issues.apache.org/jira/browse/LUCENE-6046), I think we should port this back for 1.4.3 as well?

**Comment by nik9000** [comment]
If you are backporting automaton issues it'd be easier to backport the
whole thing.  I suppose its a matter of complexity of the backport.

On Wed, Feb 4, 2015 at 3:24 PM, Michael McCandless <notifications@github.com

**Comment by mikemccand** [comment]
@nik9000 Yeah my plan is to backport max_determinized_states as well; it's really necessary because Lucene defaults the max to 10K states so users that hit that limit need a way to increase it.
