### ISSUE TITLE
java api issue

### ISSUE THREAD

**Issue by rob-tice** [elasticsearch/elasticsearch#8409]
in 1.4.0, if an es client is obtained via node builder and then all of the indexes are dropped and recreated via this client, subsequent data indexing calls appear to fail. 

If you follow this at trace level, each index call results in a message 'primary shard [xxx] is not yet active or we do not know the node it is assigned to [null], scheduling a retry. ' (originating from TransportShardReplicationOperationAction). 

This is not the behaviour in 1.3.4. 

The issue also doesn't manifest itself if a transport client is used instead.

**Comment by bleskes** [comment]
The error message suggest the client node doesn't know where the primaries of the new indices are allocated. It's hard to know why from the current information we have. Since we didn't hear anything so far, I suggest we give it one more week and close it unless we get more info.

**Comment by rob-tice** [comment]
Hi guys.

I added a flag in my app to create a new client if this exception occurred
as I didn't have time to investigate.
I have not seen it in any of the later releases so unless it starts to
occur again I would regard it as closed.

Best

Rob
