### ISSUE TITLE
native script custom explain feature removed in elasticsearch 1.4

### ISSUE THREAD

**Issue by ursvasan** [elasticsearch/elasticsearch#8561]
I see that in issue #7245 , the interface ExplainableSearchScript and its use in ScriptScoreFunction is removed. I use that feature to customize (add all attributes in addition to query and parameters i use  to compute the score in my script) the explain plan of my custom native script. It was fairly useful. 

I am wondering why was it removed. Is there a different way to add my custom details to the explanation of script function ?

**Comment by ghiron** [comment]
@brwe : Could you add it back to v1.4 branch too please ?

**Comment by brwe** [comment]
@ghiron ok, pushed 5b031f67b3dbc908f03a2cbc6ba9e0d7fcd08630 to 1.4

**Comment by ghiron** [comment]
thank you @brwe !

**Comment by ursvasan** [comment]
thanks for adding it back @brwe. LGTM

**Comment by maxjakob** [comment]
Since [ExplainableSearchScript.explain now takes a `float`](https://github.com/elasticsearch/elasticsearch/issues/8561) it is not possible any more to print the full tree of explanations.
@brwe Is there a plan to revert #7245 completely?

**Comment by brwe** [comment]
@maxjakob there is now: https://github.com/elasticsearch/elasticsearch/pull/9826
Can you check if that is what you need?
