### ISSUE TITLE
Aggregate terms sum of array data getting wrong result 

### ISSUE THREAD

**Issue by sreejithsrk** [elasticsearch/elasticsearch#8630]
Hi,
I have data like follows

      "hits" : {
        "total" : 2,
        "max_score" : 1.0,
        "hits" : [ {
          "_index" : "index_testing",
          "_type" : "status",
          "_id" : "535733748264759296",
          "_score" : 1.0,
          "_source":{"text":"sreejith testing big data , testing smap, testing ES","link":[],"hashtag":[],"senti_data":[{"count":1,"sentiment_score":0,"word":"data"},{"count":3,"sentiment_score":0,"word":"testing"},{"count":1,"sentiment_score":0,"word":"big"},{"count":1,"sentiment_score":0,"word":"sreejith"},{"count":1,"sentiment_score":0,"word":"es"},{"count":1,"sentiment_score":0,"word":"smap"}],"truncated":false,"SentimentScore":1,"Sentiment":"positive","source":"<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>","gender":"female","retweet_count":0,"created_at":"2014-11-21T09:57:33.000Z","mention":[],"language":"en","user":{"id":166819950,"profile_image_url_https":"https://pbs.twimg.com/profile_images/458931356345434112/KkMSDG_P_normal.jpeg","location":"","description":"am what am... :P","name":"Sreejith","screen_name":"sreejithsga","profile_image_url":"http://pbs.twimg.com/profile_images/458931356345434112/KkMSDG_P_normal.jpeg"}}
        }, {
          "_index" : "index_testing",
          "_type" : "status",
          "_id" : "535733934550577152",
          "_score" : 1.0,
          "_source":{"text":"sreejith testing hadoop","link":[],"hashtag":[],"senti_data":[{"count":1,"sentiment_score":0,"word":"hadoop"},{"count":1,"sentiment_score":0,"word":"testing"},{"count":1,"sentiment_score":0,"word":"sreejith"}],"truncated":false,"SentimentScore":-1,"Sentiment":"negative","source":"<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>","gender":"female","retweet_count":0,"created_at":"2014-11-21T09:58:18.000Z","mention":[],"language":"en","user":{"id":166819950,"profile_image_url_https":"https://pbs.twimg.com/profile_images/458931356345434112/KkMSDG_P_normal.jpeg","location":"","description":"am what am... :P","name":"Sreejith","screen_name":"sreejithsga","profile_image_url":"http://pbs.twimg.com/profile_images/458931356345434112/KkMSDG_P_normal.jpeg"}}
        } ]
      }
    }

I tried the following query 

    POST http://localhost:9200/index_testing/_search -d'
    {
                "query": {
                  "query_string": {
                     "default_field" : "text",
                     "query" :  "testing"
                  }

                },
                 "filter": {
                    "exists": {
                      "field": "senti_data"
                    }
                },
                "sort": [
                   {
                      "created_at": {
                         "order": "desc"
                      }
                   }
                ],
               "aggs": {
                    "prod_type": {
                        "terms": {
                            "field": "senti_data.word"
                        },
                        "aggs": {
                            "count": {
                                "sum": {
                                    "field": "senti_data.count"
                                }
                            }
                        }
                    }
                },
                "size": 0
            
                
                
    }'

while running this query am getting the following result

    {
       "took": 6,
       "timed_out": false,
       "_shards": {
          "total": 1,
          "successful": 1,
          "failed": 0
       },
       "hits": {
          "total": 2,
          "max_score": 0,
          "hits": []
       },
       "aggregations": {
          "prod_type": {
             "buckets": [
                {
                   "key": "sreejith",
                   "doc_count": 2,
                   "count": {
                      "value": 5
                   }
                },
                {
                   "key": "testing",
                   "doc_count": 2,
                   "count": {
                      "value": 5
                   }
                },
                {
                   "key": "big",
                   "doc_count": 1,
                   "count": {
                      "value": 4
                   }
                },
                {
                   "key": "data",
                   "doc_count": 1,
                   "count": {
                      "value": 4
                   }
                },
                {
                   "key": "es",
                   "doc_count": 1,
                   "count": {
                      "value": 4
                   }
                },
                {
                   "key": "hadoop",
                   "doc_count": 1,
                   "count": {
                      "value": 1
                   }
                },
                {
                   "key": "smap",
                   "doc_count": 1,
                   "count": {
                      "value": 4
                   }
                }
             ]
          }
       }
    }

Issue found 
it returns the incorrect  aggregate sum of "count"

**Comment by clintongormley** [comment]
No more info provided. Closing
