### ISSUE TITLE
Marvel Sense does not work over SSL

### ISSUE THREAD

**Issue by andrewrimmer** [elasticsearch/elasticsearch#8735]
Marvel Sense is not working over ssl, it hangs when it tries to connect to the elasticsearch API.The rest of Marvel seems to be working fine, as does the elasticsearch API if called directly.

I am using a freshly installed elasticsearch 1.4.1 and the latest Marvel. 

Elasticsearch is exposed on the internet over SSL as https://mydomain/.

When I profile the javascript in the browser, I can see that Marvel Sense actually tries to make the calls to the API over http, even though the API and Marval are using https. My Elasticsearch installation is not available over the internet to anything other than https. I have nginx installed, which passes the elasticsearch calls from 443 to 9200. Again this all works fine when calling the Elasticsearch API or the plugins etc.

Marvel Sense ignores the url that is in the config file (plugins/marvel/_site/kibana/config.js). It goes to http even if I hardcode the elasticsearch with a https prefix.

**Comment by bleskes** [comment]
@andrewrimmer this should be solved with Marvel 1.3.0 . If something doesn't work as you expect, feel free to re-open.
