### ISSUE TITLE
WeightedFilterCache.FilterCacheFilterWrapper class should be public

### ISSUE THREAD

**Issue by bittusarkar** [elasticsearch/elasticsearch#8773]
I've implemented an Elasticsearch plugin containing a custom highlighter module. For my requirements, I need to read the information inside `filter` object of the search command. I use that information to decide "what to highlight". I start with `highlighterContext.context.parsedPostFilter().filter()` and try to recursively traverse clauses of `bool` filters. Now, `term` filters and cached `fquery` filters are both wrapped inside the class `WeightedFilterCache.FilterCacheFilterWrapper`. This class has package private visibility. Even its field `filter` is not exposed. As a result I am not able to traverse through the entire filter structure. Unless there is a very good reason to keep this class package private, I would propose to make the class `WeightedFilterCache.FilterCacheFilterWrapper` public and expose its field `filter` with a public `getter` method like `getFilter()` as done by other classes extending from class `Filter`.

**Comment by jpountz** [comment]
This class is really an implementation detail of the filter cache so I don't think we should make it public.
