### ISSUE TITLE
Update to _source documentation

### ISSUE THREAD

**Issue by chuntley** [elasticsearch/elasticsearch#8826]
The current documentation for _source is misleading on the actual ramifications on disabling _source: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-source-field.html

The sentence "Though very handy to have around, the source field does incur storage overhead within the index." makes it seem that the only things _source is good for are fetch requests. Without diving deeper into other parts of the documentation you would not realize that disabling source actually disables the ability to reindex data.

I believe a large notification area should be added to this page explaining that disabling _source will also disable the ability to update mappings and reindex data.

**Comment by clintongormley** [comment]
It sounds like the _source field will no longer be configurable, which removes the need to document the issues with disabling it. Closing in favour of https://github.com/elasticsearch/elasticsearch/issues/8142
