### ISSUE TITLE
Require the full path (without type) for field lookups

### ISSUE THREAD

**Issue by clintongormley** [elasticsearch/elasticsearch#8872]
Currently it is possible to refer to fields using:

* a short name (eg `first`)
* the full path (eg `name.first`)
* the full path with the type prepended (eg `employee.name.first`) which automatically wraps a query clause with a filter on the `_type` field.

This method of field resolution is ambiguous.  

Instead, we will require that the full path is used at all times, and that the type name cannot be prepended.  If the user needs to filter on the `_type` field, then they should include an explicit filter.

Wildcarded field names will still be supported, eg `name.*` or `*.first`. Wildcards will apply to the whole path.

For bwc, we should add a static setting to allow the old method of field resolution in the 2.x series.

Relates to #8870

**Comment by clintongormley** [comment]
I've been thinking about this again.  Users can start specifying full paths right now, so they already have a migration period - they could start changing their queries today.

The only tricky bit is: if a query uses a shortname by mistake, it will return no results, rather than an exception.  While we could warn about missing fields, most people won't look at the logs.

In #6928 we added a strict query parsing mode for filtered aliases and percolator queries, which require fields to exist in the mapping before they can be used.  This is disabled on normal queries. Perhaps we should allow users to specify strict field lookups in their queries, so that exceptions will be thrown if an unknown field is referenced?

**Comment by clintongormley** [comment]
Related: https://github.com/elasticsearch/elasticsearch/pull/9521

**Comment by dadoonet** [comment]
Just a note here. I think this will break some tests in plugins such as lang plugins or rivers. Time to update plugins code I guess :)
