### ISSUE TITLE
Remove the `_boost` field

### ISSUE THREAD

**Issue by clintongormley** [elasticsearch/elasticsearch#8875]
The `_boost` field was deprecated in 1.0.0.RC1 in favour of using the `function_score` query with an ordinary field.  It should be removed in 2.0.0.  Any mapping which includes a `_boost` field should be updated automatically to remove it.

Relates to #8870

**Comment by reuben-sutton** [comment]
@clintongormley Is there a mechanism for automatically updating the mapping like this? I had a look, but couldn't figure it out.

**Comment by clintongormley** [comment]
@reuben-sutton there isn't, currently
