### ISSUE TITLE
Problem with sorting data.

### ISSUE THREAD

**Issue by mariuszzbrowski** [elasticsearch/elasticsearch#8903]
Hi, 

I have a problem with sorting and displaying data on dashboard for the query:

for query:

    curl -XGET 'http://localhost:9200/_all/_search?pretty' -d '{
      "query": {
        "filtered": {
          "query": {
            "bool": {
              "should": [
                {
                  "query_string": {
                    "query": "*"
                  }
                }
              ]
            }
          },
          "filter": {
            "bool": {
              "must": [
                {
                  "range": {
                    "@timestamp": {
                      "from": 1418219301701,
                      "to": 1418305701701
                    }
                  }
                },
                {
                  "fquery": {
                    "query": {
                      "query_string": {
                        "query": "tags:((\"some:tags\"))"
                      }
                    },
                    "_cache": true
                  }
                }
              ]
            }
          }
        }
      },
      "size": 3,
      "sort": [
        {
          "@timestamp": {
            "order": "desc",
            "ignore_unmapped": true
          }
        }
      ]
    }'

I receive 3 rows, 2 with timestamp from yesterday and 1 with current timestamp. 

The problem is if I set to small  limit I don't see data with current day but form yesterday.

Do I have some wrong option in my query or something is missing ? 
Maybe is elasticsearch bug ? 

Please advise,
Mariusz Zbrowski

**Comment by jpountz** [comment]
I'm closing this issue for now, please reopen if you can reproduce it with a newer release.
