### ISSUE TITLE
Pause command in elasticsearch.in.bat not friendly to automated processes

### ISSUE THREAD

**Issue by garvincasimir** [elasticsearch/elasticsearch#8913]
I am using Elasticsearch in a project which is intended to run it in [Azure Worker roles](https://github.com/garvincasimir/Elasticsearch-Azure-PAAS). I run a series of configuration tasks to install java then configure elasticsearch and run it. The problem is when the batch script does not find JAVA_HOME it pauses instead of throwing an error and returning an exit code. Because of this I will assume that this batch script is geared towards people who intend to run elasticsearch manually. I propose a similar batch script elasticsearch-headless.bat which can be initiated by other  automated processes. 

I realize that there is a service.bat but I would lose too much control if I installed Elasticsearch as a service. The runtime needs to respond immediately if the process crashes for example.

**Comment by tlrx** [comment]
@garvincasimir just to keep you informed: the pull request #9160 adds the --silent option.
