### ISSUE TITLE
No quotes for field names, exceptions in clients

### ISSUE THREAD

**Issue by nfx** [elasticsearch/elasticsearch#8929]
When issuing GET /{index}/{type}/{_id} API, i get something like the following structure, which doesn't seem to be a valid JSON:

````
{"_index":"fs_v2","_type":"FileMeta","_id":"XXXX....","_version":1,"found":true,"_source":{
    lastSeen: "2014-05-19T23:12:01.373Z",
    size: 102891,
    mimeType: "application/x-msdownload",
    ...
}}
````

there are quotes around values, but not around field names. What this anomaly is related to?..

**Comment by nfx** [comment]
@clintongormley actually, i have no information how that happened. we don't use attachments, that i can say for sure. I think it might be related somehow to issue of not returning document source during scan/scroll.

**Comment by clintongormley** [comment]
OK - it looks like you inserted bad JSON, which is exactly what gets returned to you.
