### ISSUE TITLE
Completion suggester returns payloads with XContentType that they were received with

### ISSUE THREAD

**Issue by nik9000** [elasticsearch/elasticsearch#8975]
Elasticsearch stores completion suggester payloads as raw bytes encoded in whatever XContentType it received them in.  When it returns them it returns them blind, regardless of the XContentType of the requests.  So if you use the Java API to index the completion payload it'll always come back in smile regardless of the api format requesting it.

**Comment by areek** [comment]
Hi @nik9000, this will be fixed with the rewrite :)

**Comment by clintongormley** [comment]
Closing in favour of #8909
