### ISSUE TITLE
Test scope SUITE and TEST for ElasticSearch integration test cases seems not to be valid.

### ISSUE THREAD

**Issue by orange-jumpsuite** [elasticsearch/elasticsearch#9016]
When running integration test cases at a SUITE scope (@ClusterScope(scope = Scope.SUITE.....) we are seeing several instances of ES being brought up. In fact we see an instance for every test/method. The same is happening for test cases at the TEST scope (@ClusterScope(scope = Scope.TEST). There does not seem to be a difference between SUITE and TEST and how many instances of ES are brought up.

**Comment by clintongormley** [comment]
No more info provided. Closing
