### ISSUE TITLE
Dates can't reference some esoteric but valid dates

### ISSUE THREAD

**Issue by nik9000** [elasticsearch/elasticsearch#9048]
We're looking at providing some kind of structured search for wikidata.org.  It contains dates like
* [13800 million years BCE](http://www.wikidata.org/wiki/Q1#P580)
* [14600 million years BCE](http://www.wikidata.org/wiki/Q321#P580)
* [13798 million years BCE](http://www.wikidata.org/wiki/Q273508#P585)
* [4527 million years BCE](http://www.wikidata.org/wiki/Q405#P571)

And, try as I might, I can't use dates for them.  I know I can still store them as longs containing seconds since epoch but that'll only work backwards.  I can't find any dates hugely in the future on wikidata right now but wouldn't be surprised if I ended up with stuff like
* [10<sup>10<sup>10<sup>10<sup>13</sup></sup></sup></sup> AD](https://en.wikipedia.org/wiki/Terasecond_and_longer#Yottaseconds_and_beyond)

I know these dates are really silly for handling log messages but they matter to me if no one else.

Is this something Elasticsearch should have builtin or should I go make another plugin?

**Comment by jpountz** [comment]
++ @uschindler !

**Comment by jpountz** [comment]
@nik9000 I'm curious whether this idea would address your needs?

**Comment by clintongormley** [comment]
Assuming that this issue has been resolved. Feel free to reopen
