### ISSUE TITLE
Expose ConcurrentMergeScheduler's auto IO throttle & stats

### ISSUE THREAD

**Issue by mikemccand** [elasticsearch/elasticsearch#9133]
With https://issues.apache.org/jira/browse/LUCENE-6119 we're enabling Lucene's ConcurrentMergeScheduler to automatically set an adaptive IO throttle (writes) over time depending on the incoming merge load.

With this, an app that indexes at a slow rate but unluckily suddenly hits a large merge will see that merge aggressively throttled (not using much IO), but apps with intense indexing will see merges run at a higher IO rate or entirely unthrottled, so merges don't fall behind.

The only exposed setting is a boolean (default is true) to enable the adaptive IO throttle; it's a live setting, so I'll expose it as a dynamic setting in Elasticsearch.  I'll also remove the current hardwired throttling: it's too simplistic / dangerous.

With this change, merges also separately track how much time they were stopped (because too many smaller merges need to run) vs paused (due to IO throttle).  I'll cutover Elasticsearch's stats tracking to these...

**Comment by clintongormley** [comment]
nice!
