### ISSUE TITLE
In the search when set the type slower than the speed of not set type very much

### ISSUE THREAD

**Issue by haochun** [elasticsearch/elasticsearch#9137]
hello,
       Recently,i encounter a very strange problem.like the title,In the search,when i set the index and type,it is very slow,but if i does not set the index and type is very fast.example:

![mk87p 4_h2ywse4_g_ e 9u](https://cloud.githubusercontent.com/assets/9320176/5613798/c3768e42-9524-11e4-987d-3560e1dcfd18.jpg)

![r vup130 zzugiorgv9_fc0](https://cloud.githubusercontent.com/assets/9320176/5613808/d58450ce-9524-11e4-8772-c759df848687.jpg)

This strange problem occurred in a few days ago my computer suddenly loses power, the cluster after the restart.but my cluster is health.i do not konw how to solve this strange problem.

**Comment by clintongormley** [comment]
Hi @haochun 

This sounds like an issue that would be better dealt with on the mailing lists, rather than a bug in Elasticsearch.  It sounds like you have a configuration problem (eg not enough heap).

You can find the mailing list here http://elasticsearch.org/community
