### ISSUE TITLE
PluginHandle : allow installation from internal maven repository

### ISSUE THREAD

**Issue by ghiron** [elasticsearch/elasticsearch#9139]
Hi, 

I'd like to be able to install a plugin from my company's maven repository.
Is it better to add this internal maven repo configuration somewhere in configuration files or as a plugin command parameter?
Any advice before I start to do it ? 

Thanks

**Comment by dadoonet** [comment]
Actually you can provide today a URL to the plugin.
Do you really need something else than that?

**Comment by ghiron** [comment]
Of course it's fine ... I misunderstood url parameter meaning. You can close this issue.
Sorry for the noise and thank you for the comment :-)
