### ISSUE TITLE
Recovery: RecoveryTarget does not recover the right file name

### ISSUE THREAD

**Issue by jpountz** [elasticsearch/elasticsearch#9144]
This class reads the file from the network into a temporary file, and then fsyncs the original file name - which does nothing since the file does not exist and FSDirectory silently ignores syncs on unknown files (fixed in https://issues.apache.org/jira/browse/LUCENE-6150).

**Comment by uschindler** [comment]
I fixed this in Lucene 5 and trunk through LUCENE-6150.

**Comment by uschindler** [comment]
Ah you mentioned this already!

**Comment by jpountz** [comment]
Yes, I found about it while upgrading to a more recent Lucene 5 snapshot :)

**Comment by s1monw** [comment]
grrrr....!!!

**Comment by jpountz** [comment]
For the record, this bug was introduced in #8092 which is only on master and 1.x so the bug has not been released.

**Comment by uschindler** [comment]
Hehe, it was useful to fix the staleFiles mess! Thanks for confirmation. I had exectly this problem in mind when looking into this (in addition to the onIndexOutputClosed callback, that made the FSDirectory API crazy).

Maybe leave a comment on the Lucene issue to give us feedback that it was already useful :-)
