### ISSUE TITLE
Retrieve aliases api doesn't always include 'aliases' section

### ISSUE THREAD

**Issue by grantr** [elasticsearch/elasticsearch#9148]
The docs say the `aliases` section is always returned in 1.4:

> added in 1.4.0.beta1.

> The API will always include an aliases section, even if there aren’t any aliases. Previous versions would not return the aliases section.

http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.4/indices-aliases.html#alias-retrieving

And the breaking changes for 1.4 say the same thing:

> The get alias api will return a section for `aliases` even if there are no aliases.

http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.4/breaking-changes-1.4.html

But my testing shows the opposite: the `aliases` section is returned always by pre-1.4 versions, and 1.4 only returns the `aliases` section if aliases exist.

1.3.1:
```
$ curl localhost:9200/
{
  "status" : 200,
  "name" : "Justine Hammer",
  "version" : {
    "number" : "1.3.1",
    "build_hash" : "2de6dc5268c32fb49b205233c138d93aaf772015",
    "build_timestamp" : "2014-07-28T14:45:15Z",
    "build_snapshot" : false,
    "lucene_version" : "4.9"
  },
  "tagline" : "You Know, for Search"
}

$ curl localhost:9200/_aliases
{"test2":{"aliases":{}},"test1":{"aliases":{}}}%
```

1.4.0 and 1.4.2:
```
$ curl localhost:9200
{
  "status" : 200,
  "name" : "Raving Beauty",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.0",
    "build_hash" : "bc94bd81298f81c656893ab1ddddd30a99356066",
    "build_timestamp" : "2014-11-05T14:26:12Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.2"
  },
  "tagline" : "You Know, for Search"
}

$ curl localhost:9200/_aliases
{"test":{}}%
```

Are the docs wrong or is the behavior wrong? (Or maybe I'm wrong)

**Comment by clintongormley** [comment]
@colings86 please take a look at this

**Comment by colings86** [comment]
@grantr thanks for raising an issue for this. You are right that its a bug. I have created PR #9178 to resolve this and make the behaviour consistent with the documentation

**Comment by grantr** [comment]
Thanks @colings86!
