### ISSUE TITLE
No Way to Compare Original Mapping to Stored Mapping

### ISSUE THREAD

**Issue by kalinka64** [elasticsearch/elasticsearch#9150]
In ES there does not appear to be any way for an external client to compare a non-parsed ES mapping to the mapping for a given index/type.  While internally there is the DocumentMappingParser, the only way to make this comparison externally is to create a new index with the mapping string and then see if the two indexes have the same mappings.

Some kind of simple parser that will replicate the transformations done during a mapping put would make such a comparison possible.

**Comment by clintongormley** [comment]
Hi @kalinka64 

Given that the mapping will depend on the version(s) of the nodes that you are using, the only valid reference implementation of the mapping parser is, indeed the running Elasticsearch node (ie doing what you're doing today).

Trying to maintain a separate mapping parser and ensure that it is consistent with the various Elasticsearch versions seems doomed to inconsistency.

What is your use case?

**Comment by clintongormley** [comment]
No more info. Closing
