### ISSUE TITLE
ES cluster: cannot decommission multiple ES nodes

### ISSUE THREAD

**Issue by yedeng** [elasticsearch/elasticsearch#9167]
Hi,

I found that I am not able to do decommissioning over multiple nodes. 
I can do decommissioning over a single node.

I setup an ES cluster with four nodes for testing a simplest decommissioning scenario. One node is the ES master node without saving index shards; other three nodes are data nodes saving index shards. My tests are about applying decommissioning actions to one~two of the three data nodes, and check if index shards are removed from the decommissioned nodes.

I installed ES 1.4.2 on ubuntu 14.04 by following the official guide: 
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/setup-repositories.html

Installed ES version:
> elasticsearch  -v 
Version: 1.4.2, Build: 927caff/2014-12-16T14:11:12Z, JVM: 1.8.0_25

// This cmd below decommissions data node1. 
// This cmd works. Index shards are removed from data node1
curl -XPUT ip_of_master_node:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.exclude._ip" : "ip_of_data_node1"
    }
}'

// This cmd below decommissions data node2.
// This cmd works. Index shards are removed from data node2
curl -XPUT ip_of_master_node:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.exclude._ip" : "ip_of_data_node2"
    }
}'

// This cmd below resets decommission actions.
// This cmd works. Index shards are redistributed to all data nodes.
curl -XPUT ip_of_master_node:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.exclude._ip" : ""
    }
}'

// This cmd below tries to decommission two data nodes.
// This cmd does not work correctly even the response from ES cluster has no error.
// What happened is that only some (not all) index shards are removed from node2.
curl -XPUT ip_of_master_node:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.exclude._ip" : "ip_of_data_node2,ip_of_data_node1"
    }
}' 

// This cmd below tries to decommission two data nodes.
// This cmd does not work correctly even the response from ES cluster has no error.
// What happened is that all index shards are removed from node2; nothing happened to node1.
// Notice that there is a space between two ip addresses.
curl -XPUT ip_of_master_node:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.exclude._ip" : "ip_of_data_node2, ip_of_data_node1"
    }
}'

// This cmd below tries to decommission two data nodes.
// This cmd does not work correctly even the response from ES cluster has no error.
// No index shard is moved after I send this curl cmd. 
curl -XPUT ip_of_master_node:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.exclude._ip" : ["ip_of_data_node2", "ip_of_data_node1"]
    }
}'

I also tried similar curl cmds with "exclude._name", which leads similar results.

**Comment by clintongormley** [comment]
Hi @yedeng 

I can't test this with `_ip` as I only have one IP address, but you said that you're seeing similar problems when using `_name`.

i tried this out with `_name`, and a single index created with the default settings, and everything worked as expected.  Could you provide a complete recreation of the problem using `_name` (so that I can test it out as well), and also provide the output of: `GET /_cat/shards` at each step, so that I can see what you are seeing.

thanks

**Comment by yedeng** [comment]
I setup the ES cluster in AWS cloud, and do the test again.
This time, I firstly try to decommission multiple nodes. Then, I try to decommission single nodes.

//before any decommission action:
GET http://ip.of.master.node:9200/_cat/shards
index               shard prirep state   docs  store  ip             node   
logstash-2015.01.13 4     p      STARTED 278   72.1kb 10.165.74.90   node-2 
logstash-2015.01.13 4     r      STARTED 278   71.9kb 10.237.168.143 node-6 
logstash-2015.01.13 0     p      STARTED 275   72.6kb 10.149.68.176  node-1 
logstash-2015.01.13 0     r      STARTED 275   77.8kb 10.237.168.143 node-6 
logstash-2015.01.13 3     p      STARTED 276     72kb 10.149.68.176  node-1 
logstash-2015.01.13 3     r      STARTED 276   60.2kb 10.165.74.90   node-2 
logstash-2015.01.13 1     p      STARTED 289   62.7kb 10.165.74.90   node-2 
logstash-2015.01.13 1     r      STARTED 289   75.1kb 10.237.168.143 node-6 
logstash-2015.01.13 2     r      STARTED 282   72.9kb 10.149.68.176  node-1 
logstash-2015.01.13 2     p      STARTED 282   72.4kb 10.237.168.143 node-6 


//try to decomission node-1 and node-2.
curl -XPUT ip.of.master.node:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.exclude._name" : "node-1,node-2"
    }
}'
//wait a long time, check shards
GET http://ip.of.master.node:9200/_cat/shards
index               shard prirep state   docs  store  ip             node   
logstash-2015.01.13 4     p      STARTED  278  72.1kb 10.165.74.90   node-2 
logstash-2015.01.13 4     r      STARTED  278  71.9kb 10.237.168.143 node-6 
logstash-2015.01.13 0     p      STARTED  275  72.6kb 10.149.68.176  node-1 
logstash-2015.01.13 0     r      STARTED  275  77.8kb 10.237.168.143 node-6 
logstash-2015.01.13 3     r      STARTED  276  60.2kb 10.165.74.90   node-2
logstash-2015.01.13 3     p      STARTED  276    72kb 10.237.168.143 node-6 
logstash-2015.01.13 1     p      STARTED  289  62.7kb 10.165.74.90   node-2 
logstash-2015.01.13 1     r      STARTED  289  75.1kb 10.237.168.143 node-6 
logstash-2015.01.13 2     r      STARTED  282  72.9kb 10.149.68.176  node-1 
logstash-2015.01.13 2     p      STARTED  282  72.4kb 10.237.168.143 node-6 


//reset "exclude._name"
curl -XPUT ip.of.master.node:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.exclude._name" : ""
    }
}'
//check shards 
GET http://ip.of.master.node:9200/_cat/shards?v
index               shard prirep state   docs  store  ip             node   
logstash-2015.01.13 4     p      STARTED  278  72.1kb 10.165.74.90   node-2 
logstash-2015.01.13 4     r      STARTED  278  71.9kb 10.237.168.143 node-6 
logstash-2015.01.13 0     p      STARTED  275  72.6kb 10.149.68.176  node-1 
logstash-2015.01.13 0     r      STARTED  275  77.8kb 10.237.168.143 node-6 
logstash-2015.01.13 3     r      STARTED  276  60.2kb 10.165.74.90   node-2 
logstash-2015.01.13 3     p      STARTED  276    72kb 10.237.168.143 node-6 
logstash-2015.01.13 1     r      STARTED  289  62.7kb 10.149.68.176  node-1 
logstash-2015.01.13 1     p      STARTED  289  62.7kb 10.165.74.90   node-2 
logstash-2015.01.13 2     r      STARTED  282  72.9kb 10.149.68.176  node-1 
logstash-2015.01.13 2     p      STARTED  282  72.4kb 10.237.168.143 node-6 


//only decommission "node-1"
curl -XPUT ip.of.master.node:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.exclude._name" : "node-1"
    }
}'
//check shards
index               shard prirep state   docs  store ip             node   
logstash-2015.01.13 2     r      STARTED  282 72.3kb 10.165.74.90   node-2 
logstash-2015.01.13 2     p      STARTED  282 72.4kb 10.237.168.143 node-6 
logstash-2015.01.13 0     p      STARTED  275 72.5kb 10.165.74.90   node-2 
logstash-2015.01.13 0     r      STARTED  275 77.8kb 10.237.168.143 node-6 
logstash-2015.01.13 3     r      STARTED  276 60.2kb 10.165.74.90   node-2 
logstash-2015.01.13 3     p      STARTED  276   72kb 10.237.168.143 node-6 
logstash-2015.01.13 1     p      STARTED  289 62.7kb 10.165.74.90   node-2 
logstash-2015.01.13 1     r      STARTED  289 62.7kb 10.237.168.143 node-6 
logstash-2015.01.13 4     p      STARTED  278 72.1kb 10.165.74.90   node-2 
logstash-2015.01.13 4     r      STARTED  278 71.9kb 10.237.168.143 node-6 


//only decommission "node-2"
curl -XPUT ip.of.master.node:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.exclude._name" : "node-2"
    }
}'
//check shards
index               shard prirep state   docs  store ip             node   
logstash-2015.01.13 2     r      STARTED  282 72.3kb 10.149.68.176  node-1 
logstash-2015.01.13 2     p      STARTED  282 72.4kb 10.237.168.143 node-6 
logstash-2015.01.13 0     p      STARTED  275 72.5kb 10.149.68.176  node-1 
logstash-2015.01.13 0     r      STARTED  275 77.8kb 10.237.168.143 node-6 
logstash-2015.01.13 3     r      STARTED  276   72kb 10.149.68.176  node-1 
logstash-2015.01.13 3     p      STARTED  276   72kb 10.237.168.143 node-6 
logstash-2015.01.13 1     p      STARTED  289 62.7kb 10.149.68.176  node-1 
logstash-2015.01.13 1     r      STARTED  289 62.7kb 10.237.168.143 node-6 
logstash-2015.01.13 4     p      STARTED  278   72kb 10.149.68.176  node-1 
logstash-2015.01.13 4     r      STARTED  278 71.9kb 10.237.168.143 node-6

**Comment by clintongormley** [comment]
OK - all that is happening here is that Elasticsearch is unable to satisfy your request, because you need at least two nodes to host the primaries and the replicas.

If you reduce the number of replicas to 0 and set exclude to "node-1,node-2" then it will put all of the shards on node-6 only
