### ISSUE TITLE
feature request: delete index api optional parameter to ignore missing index

### ISSUE THREAD

**Issue by billumina** [elasticsearch/elasticsearch#9169]
It would be nice to have the option to return a http/200 if the index is missing. It's great for being able to re-run scripts during development or before running automated unit tests.

For backwards compatibility this option should be defaulted to false.

Proposing ignore_unavailable to keep consistent with the snapshot api parameters.

Example request:

curl -XDELETE http://localhost:9200/foo?ignore_unavailable=true

**Comment by javanna** [comment]
Hi @billumina , good point, but I think delete index api already supports this option, the request you are sending should in fact return `200` although the `foo` index doesn't exist. The idea is that every api that allows to be executed against multiple indices supports `ignore_unavailable`, as well as `allow_no_indices` and `expand_wildcards`. Have a look [here](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/multi-index.html#multi-index) for more info.

Could you please clarify if you have tried this and whether this works for you? Thanks!

**Comment by billumina** [comment]
I will try it and let you know. I didn’t realize this was an option as I didn’t see it on the delete api page.

Thanks!

**Comment by billumina** [comment]
@ Luca – Thank you so much! This worked perfectly.

From: <Padgett>, ". ." <bpadgett@illumina.com<mailto:bpadgett@illumina.com>>
Date: Wednesday, January 7, 2015 at 7:39 AM
To: elasticsearch/elasticsearch <reply@reply.github.com<mailto:reply@reply.github.com>>, elasticsearch/elasticsearch <elasticsearch@noreply.github.com<mailto:elasticsearch@noreply.github.com>>
Subject: Re: [elasticsearch] feature request: delete index api optional parameter to ignore missing index (#9169)

I will try it and let you know. I didn’t realize this was an option as I didn’t see it on the delete api page.

Thanks!

**Comment by javanna** [comment]
cool thanks for your feedback @billumina I am closing this issue then ;)
