### ISSUE TITLE
Bulk API changed behavior for status code

### ISSUE THREAD

**Issue by matthughes** [elasticsearch/elasticsearch#9173]
At least as far back as 1.3.5, if a _bulk operation had any errors, it would return the most severe error as the HTTP status code.  This changed at least in 1.4.2.  

I have auto_index_create turned off for my indexes:

```
bash-4.1# cat request.txt
{ "index" : { "_index" : "myindex", "_type" : "type1", "_id" : "1" } }
{ "field1" : "value1" }


bash-4.1# curl -v XPUT http://localhost:9200/myindex/event/_bulk --data-binary @request.txt; echo
* getaddrinfo(3) failed for XPUT:80
* Couldn't resolve host 'XPUT'
* Closing connection #0
curl: (6) Couldn't resolve host 'XPUT'
* About to connect() to localhost port 9200 (#0)
*   Trying ::1... connected
* Connected to localhost (::1) port 9200 (#0)
> POST /myindex/event/_bulk HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.15.3 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: localhost:9200
> Accept: */*
> Content-Length: 113
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Content-Length: 187
<
* Connection #0 to host localhost left intact
* Closing connection #0
{"took":1,"errors":true,"items":[{"index":{"_index":"myindex","_type":"type1","_id":"1","status":404,"error":"IndexMissingException[[myindex] missing]"}}]}
```

In 1.3.5 and below I could always count on the HTTP status code being 404 from this call.  Was this an intentional change in behavior?  It looks like it might be related to changes from this issue: #8125

**Comment by matthughes** [comment]
@markharwood Your commit for #8125 did indeed change this behavior.

Did you ever determine why it was hanging?  I did reproduce the test case prior to your commit and sure enough saw the hang, but the thread dump at the time didn't show anything obvious.

I patched v1.4.2 making this one change:

```
TransportBuildAction.java
             } catch (IndexClosedException ice) {
                 unavailableException = ice;
-            } catch (IndexMissingException ime) {
-                // Fix for issue where bulk request references an index that
-                // cannot be auto-created see issue #8125
-                unavailableException = ime;
             }
```
and retried the original test case.  No hang.  And by removing this catch, we get the original 404 behavior back.  Any thoughts on reverting this part of the change?

**Comment by matthughes** [comment]
Here is the thread dump of the original hang: https://gist.github.com/matthughes/f38772caf965ad289b26

It's not clear to me what was actually blocked here.

**Comment by clintongormley** [comment]
Hi @matthughes 

Actually you couldn't always rely on an error code coming back from the bulk API.  The fact that you got one was a bug.  Each action in the bulk response can succeed or fail independently of the others, so exceptions need to be reported at the action level.  Only complete failure of the bulk request (eg server not available) should result in the bulk request returning an exception.

Note: you can check the `errors` key in the response.  It will be true if any individual action failed.
