### ISSUE TITLE
doc['field'].values results differ from Analyze API

### ISSUE THREAD

**Issue by JimminiKin** [elasticsearch/elasticsearch#9180]
I have an issue with analyzers.

After setting a filter and an analyzer and indexing a few docs, I tried analyzing what 'Petite Salle à Manger' analyzes to and I get the following result

```javascript
	{
		tokens: [
			{
				token: "petite",
				start_offset: 0,
				end_offset: 6,
				type: "<ALPHANUM>",
				position: 1
			},
			{
				token: "salle",
				start_offset: 7,
				end_offset: 12,
				type: "<ALPHANUM>",
				position: 2
			},
			{
				token: "a",
				start_offset: 13,
				end_offset: 14,
				type: "<ALPHANUM>",
				position: 3
			},
			{
				token: "manger",
				start_offset: 15,
				end_offset: 21,
				type: "<ALPHANUM>",
				position: 4
			}
		]
	}
```

But, when I try a Match query on the field with the word 'manger', nothing matches even though a document in the index has a value of 'Petite Salle à Manger' for the field. 'manger' also analyzes to 'manger' so it should match.

I tried to fetch the internal values of the field for the document in question. I added a script field containing doc['field'].values and the result are the following

```javascript
	[
		"a",
		"mang",
		"petit",
		"sall"
	]
```

Tried it on 1.4.1 and 1.4.2 with Standard, Hunspell and Phonetic analyzers consecutively.

Simple question : WTF DID I DO WRONG ?

**Comment by rjernst** [comment]
@JimminiKin Could you please show the exact query you are running? As well as your mappings?

**Comment by JimminiKin** [comment]
Sorry for the silly question it was a test mistake ...
