### ISSUE TITLE
Reroute api not working at Elasticsearch-1.3.4

### ISSUE THREAD

**Issue by czervenyvlk** [elasticsearch/elasticsearch#9187]
When I try to relocate one UNASSIGNED shard to a node, command fails with resolving of the node id.
In the error message below, you can see that node id is wrong "NOiHErIFS5Kf_Va8rSC6qw ". It looks like it add a space in the end of the string.

curl -XPOST 'localhost:9200/_cluster/reroute' -d '{ "commands" : [ { "allocate" : { "index" : "logstash-2015.01.07", "shard" : 0, "node" : "NOiHErIFS5Kf_Va8rSC6qw", "allow_primary" : true } } ] }'                                                                                                                        
{"error":"ElasticsearchIllegalArgumentException[failed to resolve [NOiHErIFS5Kf_Va8rSC6qw ], no matching nodes]","status":400}

**Comment by clintongormley** [comment]
Hi @czervenyvlk 

I tried this on 1.3.4 (substituting the current node ID) and it all worked just fine.  I'm wondering if you had some hidden control character in your original request.  Are you able to replicate this?

**Comment by czervenyvlk** [comment]
Hi @clintongormley 
After cluster restart I could not reproduce it with newly generated node id. Do you have an idea why ES included space character in node id?

**Comment by clintongormley** [comment]
Hi @czervenyvlk 

I think it is more likely that there was an extra space (or some hidden unicode character) in the input.  Glad it is working for you.
