### ISSUE TITLE
Getting ArrayOutOfBoundsException Randomly

### ISSUE THREAD

**Issue by KumarSubramanian** [elasticsearch/elasticsearch#9188]
Hi,
I am using Elastic Search v 1.4.1.

When i use scroll (by REST API), I keep getting ArrayOutOfBounds Exception. Here is what i do

1) Execute REST GET to scroll (1st get) - Successfull - Returns a Scroll_Id back
2) Use this Scroll_id to get the Next Result Set - Fails - Throws ArrayOutBounds[3] from ES (get a 500 error back). this happens randomly.

Any help would be immensely helpful.

Thanks,
Kumar Subramanian.

**Comment by clintongormley** [comment]
Hi @KumarSubramanian 

Could you please provide the actual REST requests that you are using (plus the output generated by each request), and the stack trace for the AOB exception.

thanks

**Comment by clintongormley** [comment]
No more info. Closing. Feel free to reopen with more info
