### ISSUE TITLE
Index Alias Create requests eats up heap and timesout

### ISSUE THREAD

**Issue by mosiddi** [elasticsearch/elasticsearch#9192]
Related to #9130 

Since that issue is closed, opening a new one. Very simple scenario - 
ES Cluster: 3 master nodes (A2), 3 data nodes (A6) and 3 query nodes (A2)
No. of indices: ~1400
Data (primary): ~300 GB

State of cluster when the observation happened: Very low rate of query ~0.2/sec, indexing rate ~250 docs/sec and all of these touching only 1 of ~1400 indexes

What happened? There were in total ~500 create index call happened (retry 3 times on failure), on an average ~ 8 -10 per minute, heap grew from 25% to 75% in 10 minutes and came back to 25% (pattern continued). A lot of timeout exceptions seen.

Network I/O was 7 MBps that time in master.

**Comment by mosiddi** [comment]
What I want to know is "create-alias" operation (where we update the index metadata) has dependency on data nodes and since they were busy with the indexing operation they were slow in responding to master. And hence the timeout?

OR something might have gone wrong and I should look deeper into heap?

**Comment by mosiddi** [comment]
http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/finite-scale.html tells me yes that is indeed the case. Please close if that is correct. Otherwise, do tell me if you need any data for further analysis.

**Comment by clintongormley** [comment]
@mosiddi adding an alias requires publishing the cluster state to all nodes in the cluster.  You could create many of them in a single step (which requires a single cluster state update), but you're creating them one by one on a large cluster state (with 14,000 shards, if you've used the default settings)

You don't mention how much heap space is dedicated to each node, but the picture of the heap growing to 75% then dropping to 50% sounds like normal GC behaviour.

This sounds normal to me.

**Comment by mosiddi** [comment]
Thanks @clintongormley and sounds reasonable to me too.
