### ISSUE TITLE
Succes of nested query depends on unrelated data field

### ISSUE THREAD

**Issue by ewrdk** [elasticsearch/elasticsearch#9194]
# Description of problem
We have encountered a very weird problem: We create an index with a mapping containing nested structures. We then make a query using a range on validFrom and validTo dates. This works in the example below (ie. we get a result). When we add a single field (named "dataAdgang") both to the mapping and the data then the query no longer works (an empty result is returned). Reproduced using version 1.4.2.

Working example:
`curl -XPOST --data @mapping-nested-works.json localhost:9200/nestedworks`
`curl -XPOST --data @4000800895-nested-works.json localhost:9200/nestedworks/virksomhed/1`
`curl -XGET --data @nested-query.json http://localhost:9200/nestedworks/_search?pretty`

Example that is not working:
`curl -XPOST --data @mapping-nested-notworking.json localhost:9200/nestednotworking`
`curl -XPOST --data @4000800895-nested-notworking.json localhost:9200/nestednotworking/virksomhed/1`
`curl -XGET --data @nested-query.json http://localhost:9200/nestednotworking/_search?pretty`

# Content of the files

nested-query.json:
`{"filter":{"nested":{"path":"virksomhed.Vrvirksomhed.virksomhedsstatus","query":{"bool":{"must":[{"range":{"gyldigFra":{"lt":"2011-08-20"}}},{"range":{"gyldigTil":{"gt":"2011-08-20"}}}]}}}}}`

mapping-nested-works.json:
`{
    "mappings" : {
      "virksomhed" : {
        "properties" : {
          "Vrvirksomhed" : {
            "properties" : {
              "cvrNummer" : {
                "type" : "string"
              },
              "enhedsNummer" : {
                "type" : "long"
              },
              "enhedstype" : {
                "type" : "string"
              },
              "fejlRegistreret" : {
                "type" : "boolean"
              },
              "fejlVedIndlaesning" : {
                "type" : "boolean"
              },
              "harFremtidigAendring" : {
                "type" : "boolean"
              },
              "livsforloeb" : {
                "type" : "nested",
                "properties" : {
                      "gyldigFra" : {
                        "type" : "date",
                        "format" : "dateOptionalTime"
                      },
                      "gyldigTil" : {
                        "type" : "date",
                        "format" : "dateOptionalTime"
                      },
                  "sidstOpdateret" : {
                    "type" : "date",
                    "format" : "dateOptionalTime"
                  }
                }
              },
              "samtId" : {
                "type" : "long"
              },
              "sidstIndlaest" : {
                "type" : "date",
                "format" : "dateOptionalTime"
              },
              "sidstOpdateret" : {
                "type" : "date",
                "format" : "dateOptionalTime"
              },
              "virksomhedsstatus" : {
                "type" : "nested",
                "properties" : {
                      "gyldigFra" : {
                        "type" : "date",
                        "format" : "dateOptionalTime"
                      },
                      "gyldigTil" : {
                        "type" : "date",
                        "format" : "dateOptionalTime"
                      },
                  "sidstOpdateret" : {
                    "type" : "date",
                    "format" : "dateOptionalTime"
                  },
                  "status" : {
                    "type" : "string"
                  }
                }
              }
            }
          }
        }
      }
    }
}
`

4000800895-nested-works.json:
`{"Vrvirksomhed":{"cvrNummer":10237513,"livsforloeb":[{"gyldigFra":"1972-12-19","gyldigTil":"2002-12-18","sidstOpdateret":"1999-10-16T19:49:47.000+02:00"}],"virksomhedsstatus":[{"status":"NORMAL","gyldigFra":"1972-12-19","gyldigTil":"1991-11-07","sidstOpdateret":"2014-09-24T00:00:00.000+02:00"},{"status":"NORMAL","gyldigFra":"2011-08-19","gyldigTil":"2011-09-01","sidstOpdateret":"2014-09-24T00:00:00.000+02:00"}],"samtId":2,"enhedsNummer":4000800895,"enhedstype":"VIRKSOMHED","sidstIndlaest":"2015-01-05T14:44:58.582+01:00","sidstOpdateret":"2014-11-03T00:00:00.000+01:00","fejlRegistreret":false,"fejlVedIndlaesning":false,"harFremtidigAendring":false}}`

mapping-nested-notworking.json:
`{
    "mappings" : {
      "virksomhed" : {
        "properties" : {
          "Vrvirksomhed" : {
            "properties" : {
              "cvrNummer" : {
                "type" : "string"
              },
              "dataAdgang" : {
                "type" : "long"
              },
              "enhedsNummer" : {
                "type" : "long"
              },
              "enhedstype" : {
                "type" : "string"
              },
              "fejlRegistreret" : {
                "type" : "boolean"
              },
              "fejlVedIndlaesning" : {
                "type" : "boolean"
              },
              "harFremtidigAendring" : {
                "type" : "boolean"
              },
              "livsforloeb" : {
                "type" : "nested",
                "properties" : {
                      "gyldigFra" : {
                        "type" : "date",
                        "format" : "dateOptionalTime"
                      },
                      "gyldigTil" : {
                        "type" : "date",
                        "format" : "dateOptionalTime"
                      },
                  "sidstOpdateret" : {
                    "type" : "date",
                    "format" : "dateOptionalTime"
                  }
                }
              },
              "samtId" : {
                "type" : "long"
              },
              "sidstIndlaest" : {
                "type" : "date",
                "format" : "dateOptionalTime"
              },
              "sidstOpdateret" : {
                "type" : "date",
                "format" : "dateOptionalTime"
              },
              "virksomhedsstatus" : {
                "type" : "nested",
                "properties" : {
                      "gyldigFra" : {
                        "type" : "date",
                        "format" : "dateOptionalTime"
                      },
                      "gyldigTil" : {
                        "type" : "date",
                        "format" : "dateOptionalTime"
                      },
                  "sidstOpdateret" : {
                    "type" : "date",
                    "format" : "dateOptionalTime"
                  },
                  "status" : {
                    "type" : "string"
                  }
                }
              }
            }
          }
        }
      }
    }
}
`

4000800895-nested-notworking.json:
`{"Vrvirksomhed":{"cvrNummer":10237513,"livsforloeb":[{"gyldigFra":"1972-12-19","gyldigTil":"2002-12-18","sidstOpdateret":"1999-10-16T19:49:47.000+02:00"}],"virksomhedsstatus":[{"status":"NORMAL","gyldigFra":"1972-12-19","gyldigTil":"1991-11-07","sidstOpdateret":"2014-09-24T00:00:00.000+02:00"},{"status":"NORMAL","gyldigFra":"2011-08-19","gyldigTil":"2011-09-01","sidstOpdateret":"2014-09-24T00:00:00.000+02:00"}],"samtId":2,"dataAdgang":0,"enhedsNummer":4000800895,"enhedstype":"VIRKSOMHED","sidstIndlaest":"2015-01-05T14:44:58.582+01:00","sidstOpdateret":"2014-11-03T00:00:00.000+01:00","fejlRegistreret":false,"fejlVedIndlaesning":false,"harFremtidigAendring":false}}`

**Comment by em110622** [comment]
I can reproduce the problem using this example on version 1.4.2. Can anyone explain the strange behaviour?

**Comment by jprante** [comment]
The `path` does not assert the correct field name selection within a nested object. You should add the complete path to the field name in a query if you use a field name more than once in a document. 

Like this:

https://gist.github.com/jprante/df600541e4b776f3f7ef

I would try as hard as possible not to use a field name more than once in a mapping. This confuses the field name selection in ES.

**Comment by ewrdk** [comment]
Your resolution does indeed return the correct result. I did try using a complete path, but that also included the prefix "virksomhed." which does not work.

I do however still not understand why an unrelated field could cause the above behaviour. I will close the issue. Thanks for a quick response.

**Comment by jprante** [comment]
The reason is technical: ES stores all field names in a hash map. When field names are created, they are constructed as a full path, say "a.b.c". Abbreviated field names are looked up by an iterator that walks over the full path names and matches for the name. The first match is taken.

When another field is added, the hash map may get reorganized, and the field name iterator find another order in the sequence, and the first match may have changed. The effect is not easy to predict, if you are lucky, the first match of the field name has not changed.

This is a bug, because field name lookup should not depend on a key order of a hash map. I found this bug when switching from Java 7 to Java 8 because Java 8 uses another hash code algorithm.

The best possible workaround - as long as this issue is not fixed - is to take special precaution for the choice of field names so they are unique in a mapping. By doing this, ES will always find the one and only field name.
