### ISSUE TITLE
Configuring dedicated cluster for monitoring

### ISSUE THREAD

**Issue by utk4rsh** [elasticsearch/elasticsearch#9195]
Hi, 

I am trying to setup a topology where I have,

1. One cluster (lets say it has name : "data-cluster") with three nodes (for simplicity all running on same machine but different ports)
            a. localhost:9200
            b. localhost:9400
            c. localhost:9600

2. Another cluster ("monitoring-cluster") with two nodes
           a. localhost:8200
           b: localhost:8400

All nodes in both cluster have marvel installed and are accessible on their respective ports with correct cluster health reports.

However, to have dedicated monitoring stats all nodes on "data-cluster" are configured to send stats to "monitoring-cluster" ( as mentioned in docs : http://www.elasticsearch.org/guide/en/marvel/current/configuration.html )

Below is the configuration on each node of "data-cluster": 

marvel.agent.exporter.es.hosts: ["192.168.2.32:8200", "192.168.2.32:8400"]

Even after this configuraton, the marvel UI on "monitoring cluster" doesn't show nodes and indices of "data-cluster"

Am i missing something? Kindly help, thanks for your time.

**Comment by dadoonet** [comment]
I think it's pretty good. Note that you should also disable marvel on the monitoring cluster nodes.
Also you need to restart data nodes.
Try to clean first your monitoring cluster .marvel* indices.

**Comment by utk4rsh** [comment]
I have re-installing everything, it doesn't work unless I put all the nodes in same cluster (use the same cluster name - "data").

One more strange thing. I changed the es.host to non existing IPs, even then I get the following log in debug mode without any exception or cry for timeouts while connecting etc.

With correct hosts:

[2015-01-08 16:06:58,412][DEBUG][marvel.agent.exporter    ] [ctselk-node-0] initialized with targets: 192.168.2.32:8200, index prefix [.marvel], index time format [YYYY.MM.dd]

[2015-01-08 16:08:28,332][DEBUG][marvel.agent.exporter    ] [ctselk-node-0] initialized with targets: 122.168.2.32:8200, index prefix [.marvel], index time format [YYYY.MM.dd]

Thanks
