### ISSUE TITLE
concurrent search request to elasticsearch

### ISSUE THREAD

**Issue by vipinvijay** [elasticsearch/elasticsearch#9196]
What is the maximum limit on the concurrent search requests with default Elastic search server settings.

I am able to perform only 5 parallel search requests in my application with default settings.

how can we improve the scalability of ES server search requests apart from increasing number of node,shards and queue size in search thread pool.

thanks.

**Comment by dadoonet** [comment]
This space is for issues and feature requests.
You already asked this on the mailing list which is the best place.
You'll find better help there.

**Comment by vipinvijay** [comment]
thanks
