### ISSUE TITLE
set maximum memory usage with ES_HEAT_MAP

### ISSUE THREAD

**Issue by aortmannm** [elasticsearch/elasticsearch#9200]
Hi,

I set the Memory usage with ES_HEAT_MAP to 512m, the java vm is started with the right settings as we can see in the following statement:

```
16990 ?        S  9:23 /opt/local/iris/iris-docs-server/vendor/jdk1.8.0_25/bin/java -Xms512m -Xmx512m -Xss256k -Djava.awt.headl...
```

With prstat the memory usage looks like this:

```
16990 root      955M  850M sleep   59    0   0:09:42 0.3% java/247
```

Why the java vm is still using up to 1GB memory?

**Comment by clintongormley** [comment]
I don't know where you got `ES_HEAT_MAP` from - the correct environment variable is `ES_HEAP_SIZE`

**Comment by aortmannm** [comment]
Eh sorry was a misstake from me I used ES_HEAP_SIZE and it took effect as you can see in my first codeblock in the first post. But it still takes more RAM as it should.

**Comment by clintongormley** [comment]
@aortmannm the JVM uses up more memory than just the heap, so this is expected.

**Comment by aortmannm** [comment]
Did you have any suggestion to optimize the memory usage for a database with around 10000 documents?

And what is the exact meaning of the heap size? What happend if the limit is reached? Does the database crash or just slow down?

**Comment by clintongormley** [comment]
@aortmannm Please ask these questions on the mailing list.
