### ISSUE TITLE
error configuring snapshot repository in S3 US Standard region

### ISSUE THREAD

**Issue by peillis** [elasticsearch/elasticsearch#9202]
According to AWS S3 documentation http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html the empty string is used for create buckets in the US classic region. But configuring an empty region in the snapshot raises this error in elasticsearch:

org.elasticsearch.ElasticsearchIllegalArgumentException: No automatic endpoint could be derived from region []

us-east-1 can't be used because then AWS raise this error:
The specified location-constraint is not valid (Service: Amazon S3; Status Code: 400; Error Code: InvalidLocationConstraint

**Comment by clintongormley** [comment]
Hi @peillis 

I've opened this issue on the AWS plugin repo: https://github.com/elasticsearch/elasticsearch-cloud-aws/issues/163
