### ISSUE TITLE
Index was created with a name 2014

### ISSUE THREAD

**Issue by liycheng** [elasticsearch/elasticsearch#9210]
My index file was created by logstash output:
  elasticsearch_http {
    host => "myhostname"
    index => "appname-index-%{+YYYY.MM.dd}"
    flush_size => 1000
  }
But I saw for recent 2 days the index file was named:
appname-index-2014-01-08
appname-index-2014-01-09
And there is nothing on Kibana page, even search starts from "2014-01-08"

There are a few other index for different applications, with the same logstash output setting, they are just fine.

Don't have any idea about it.

**Comment by liycheng** [comment]
Tried to delete the latest index file for today, and saw index be created with the same name appname-index-2014-01-09 soon.
the system time is all correct.

**Comment by electrical** [comment]
Hi,

This is more a Logstash issue then Elasticsearch.
the logs that end up in that index most likely don't have a year specified in the original timestamp.
The default year is defined at startup of logstash which is most likely in 2014 causing logs without a year to get the 2014 year added.
If you restart Logstash now the logs should end up in the right index for 2015.
We are working on a solution.

More info:

https://github.com/logstash-plugins/logstash-filter-date/issues/3
https://github.com/elasticsearch/logstash/issues/2306
https://github.com/logstash-plugins/logstash-filter-date/pull/4

**Comment by liycheng** [comment]
Thanks Richard 
However, I stopped logstash, deleted the old index, and start the logstash, the new created index name still with a name *2014*
And also I found for previous days, I saw index were named like:
 appname-index-2015-01-02
appname-index-2015-01-03
...
with the correct year

**Comment by clintongormley** [comment]
Hi @liycheng 

This issue is to do with logstash rather than elasticsearch.  

Closing
