### ISSUE TITLE
Problem with setting "size" on query - PHP SDK

### ISSUE THREAD

**Issue by svet88** [elasticsearch/elasticsearch#9215]
I`m using PHP SDK. My code is:

 $params = array();
 $params['index'] = $this->index;
 $params['type'] = $this->type;
 $params["size"] = 50; 
 $params['body']['query']['match']["country"] = 53;
 $results = $client->search($params);

and in the response I got:
 Error 500 transfer closed with XXXXX bytes remaining to read.

I try to put "size" to different numbers.
10 - working
15 - working
18 - working
above 19 - show me error

I put "size = 18" and I send couple of request:
First response - show me 18 result
Second response - show me error
Third response - show me 18 result

**Comment by svet88** [comment]
Thanks for the reponse.
I wrote my own method using cURL and is working.
I send same query to SDK and it give me error
"Error 500 transfer closed with XXXXX bytes remaining to read."

So I`m thinking this is a issue.

**Comment by clintongormley** [comment]
Hi @svet88 

This sounds like an issue with whatever client you're using. Please open the ticket there.
