### ISSUE TITLE
Post Filter on Nested Value

### ISSUE THREAD

**Issue by dev-day** [elasticsearch/elasticsearch#9217]
Hi,

Is it possible to run a post filter on a nested value?

Regards,
Dev

**Comment by dev-day** [comment]
Hi Dadoonet,

Thank you for coming back to me.
I will go through the proper channels (I'm new, sorry!)...
Unless you can assist quickly:

My document is

{"code":"ABC", "variants": [{"sku":"123", "price": 15}], "colour":"blue"}
{"code":"DEF", "variants": [{"sku":"456", "price": 30}], "colour":"red"}

I run aggs for colour and I get red (1) and blue (1).
I have a mapping for variants to be nested.

And I want to post filter on the price

    "post_filter": {
       "nested": {
            "path": "variants",
             "post_filter":{
             "range": {"price":{ "gt": 20.0 }}
             }
         }
    },


The 2nd "post_filter" crashes.
I cannot find any documentation on this.
I've tried the following:
1) Without the 2nd post_filter and using variants.price
2) With filter instead of the 2nd post filter
3) With filter and variants.price.

Can you assist? 
Or would you like me to send this to the mailing list?

Any help will be greatly appreciated.

Regards,
Dev

**Comment by dadoonet** [comment]
Not an issue. Link to ML thread: https://groups.google.com/d/msgid/elasticsearch/79b7583c-6336-495b-bef1-d9ba0a9e0b83%40googlegroups.com?utm_medium=email&utm_source=footer

Closing.
