### ISSUE TITLE
Snapshot module and adding a node

### ISSUE THREAD

**Issue by geoffroya** [elasticsearch/elasticsearch#9222]
Hello

I'm wondering what is the procedure to declare the existing snapshot repository to a newly created node? Is at automatic?

I think this could be part of the documentation.

Let's say I have a 3 nodes cluster, with a "backup" snapshot repo, pointing to /mnt/es/backup. If I add a new node, already having access to /nmt/es/backup, will it "join" seamlessly the repo, or will I have to issue a PUT toward _snapshot/backup?

Thank you for your answer.

Geoff.

**Comment by clintongormley** [comment]
Hi @geoffroya 

Please ask questions like these in the mailing list http://elasticsearch.org/community/

but yes, it will pick up the existing repository settings.
