### ISSUE TITLE
Indices using _timestamp are being dropped on cluster restart

### ISSUE THREAD

**Issue by meash-nrel** [elasticsearch/elasticsearch#9223]
**EDIT: turns out templates aren't the issue - it's _timestamp -- see later comments.**

On my 3 node ES 1.4.1 cluster, I had bulk imported data into several hundred per-day indexes, whose type mappings were created from templates.  These indexes were all missing upon restarting the cluster.  Only one index remained - one that I had created manually (not from a template).  I lost a significant amount of data that was bulk imported over last 2 weeks.

I verified that when indexes are created in advance or on-the-fly from a template, they behave normally and are persisted to disk -- but once the cluster is restarted, **they no longer appear in ES**.  Underlying files (Lucene shards etc) are all still there -- but ES refuses to see them.

Bottom line -
* Creating an index from a template (either on-the-fly or in advance), that index will permanently disappear upon restart.  
* Underlying files are all still there.  ES refuses to load the index.  Any further loading into that same index will clear the existing files and start the index anew.

I installed ES 1.4.2 locally on my Mac and replicated the issue on a single node cluster, using all default settings.

* First create a template test-type, using wildcard it to allow it to affect multiple indices (any index that starts with "test-" with a dash).

```
PUT http://localhost:9200/_template/test-type
{
    "template" : "test-*",
    "order" : 0,
    "settings" : {
        "number_of_shards" : 4,
        "number_of_replicas" : 0, 
        "refresh_interval": "1s"
    },
    "mappings" : {
        "test-type": {
                "_timestamp" : {
                    "enabled" : true,
                    "store": true,
                    "index": "not_analyzed",
                    "format" : "date_time",
                    "default": null, 
                    "path" : "timestamp"
                },
        
                "_all": {
                    "enabled": false
                },
                "_source": {
                    "enabled": false
                },
                "properties": {
                    "node": {
                        "type": "string",
                        "store": true,
                        "index": "not_analyzed"
                    },
                    "power": {
                        "type": "integer",
                        "store": true,
                        "index": "not_analyzed"
                    }
                }
            }
    }
}
```

* I created an index in advance, from my test-type template (index begins "with test-").

```
PUT http://localhost:9200/test-template
{}
```

* Insert a document into index created in advance, plus create 2 new indices on the fly (one from template, one not).

```
PUT http://localhost:9200/test-template/test-type/1
 {
    "timestamp": 1420748020000,
    "node": "n1111",
    "power": 200
}

PUT http://localhost:9200//test-template-onfly/test-type/1
 {
    "timestamp": 1420748020000,
    "node": "n1111",
    "power": 200
}

PUT http://localhost:9200//test_notemplate_onfly/test-type/1
 {
    "timestamp": 1420748020000,
    "node": "n1111",
    "power": 200
}
```

* List indexes

```
GET http://localhost:9200/_cat/indices

yellow open test_notemplate_onfly 5 1 1 0 3.4kb 3.4kb 
green  open test-template-onfly   4 0 1 0 2.9kb 2.9kb 
green  open test-template         4 0 1 0 2.9kb 2.9kb 
```
(test_notemplate_onfly shows as yellow since by default replication=1, but this is a single node cluster)

* Shut down cluster

```
POST http://localhost:9200/_cluster/nodes/_all/_shutdown
```

* Restart cluster and view indexes.

```
GET http://localhost:9200/_cat/indices

yellow open test_notemplate_onfly 5 1 1 0 3.4kb 3.4kb 
```

Where'd the indices go?  Files are all still there - and there is nothing out of the ordinary in the log file when starting ES back up that would indicate failure to load those indexes, etc.

Beyond fixing the issue, would love to know how to get my existing couple hundred ES indexes that still exist on disk back into ES's index metadata, if you have any way to get ES to re-recognize an index it already created but dropped.   Really unfortunate to hit this bug after several weeks of bulk importing, only to find them all magically gone upon restarting cluster.

**Comment by meash-nrel** [comment]
I tried a simpler template and it worked ... so went back to my original template here and starting taking out the mappings piece by piece to see root cause. 

Eliminating this from the template makes it work as intended...
```
"_timestamp" : {
                    "enabled" : true,
                    "store": true,
                    "index": "not_analyzed",
                    "format" : "date_time",
                    "default": null, 
                    "path" : "timestamp"
                },
```

So for some reason using the _timestamp feature in particular is causing this disappearance of indexes...

In order to circumvent the issue, I took out the _timestamp mapping and replaced it with an explicit "date" property instead.   Here is my new template that does NOT cause this issue:
```
{
    "template" : "test-*",
    "order" : 0,
    "settings" : {
        "number_of_shards" : 4,
        "number_of_replicas" : 0, 
        "refresh_interval": "1s"
    },
    "mappings" : {
        "test-type": {
        		"dynamic": false,
                "_all": {
                    "enabled": false
                },
                "_source": {
                    "enabled": false
                },
                "properties": {
                	"timestamp": {
                    	"type": "date",
                        "format": "date_time",
                        "store": true,
                        "index": "not_analyzed"
                    },
                    "node": {
                        "type": "string",
                        "store": true,
                        "index": "not_analyzed"
                    },
                    "power": {
                        "type": "integer",
                        "store": true,
                        "index": "not_analyzed"
                    }
                }
            }
    }
}
```

Indexes created from this template no longer disappear upon cluster restart.  So -- can work around at least to continue to use ES for my desired schema.  (Doesn't bring back my disappeared indexes though...)

**Comment by meash-nrel** [comment]
Make the issue title clearer given the new info that _timestamp is the culprit.

**Comment by meash-nrel** [comment]
Ok more testing of this issue - seems this mapping being in a template was not part of the issue at all, it's solely due to _timestamp in the mapping.   

I created a new index w/o a template but using _timestamp, put in a document, and it too disappeared on cluster restart.

* Create new index and type.
```
PUT http://localhost:9200/new_index
 {
    "settings" : {
        "index" : {
            "number_of_shards" : 1,
            "number_of_replicas" : 0, 
            "refresh_interval": "1s"
        }
    },
    "mappings": {
    	"power": {
	        "_timestamp" : {
	            "enabled" : true,
	            "store": true,
                "index": "not_analyzed",
	            "format" : "date_time",
	            "default": null, 
	            "path" : "timestamp"
	        },
    		"properties": {
    			"node": {
    				"type": "string",
    				"store": true,
    				"index": "not_analyzed"
       			},
       			"power": {
    				"type": "integer",
    				"store": true,
    				"index": "not_analyzed"
       			}
    		}
    	}
    }
}
```

* Add a document.
```
PUT http://localhost:9200/new_index/power/1
 {
    "node": "n1111",
    "power": 200,
    "timestamp": 1420737933000
}
```

* Restart cluster ... and **index is missing**...

* Redo the above, using explicit timestamp property instead of _timestamp.
```
PUT http://localhost:9200/new_index
{
    "settings" : {
        "index" : {
            "number_of_shards" : 1,
            "number_of_replicas" : 0, 
            "refresh_interval": "1s"
        }
    },
    "mappings": {
    	"power": {
    		"properties": {
    			"timestamp": {
    				"type": "date",
    				"format": "date_time",
    				"store": true,
    				"index": "not_analyzed"
    			},
    			"node": {
    				"type": "string",
    				"store": true,
    				"index": "not_analyzed"
       			},
       			"power": {
    				"type": "integer",
    				"store": true,
    				"index": "not_analyzed"
       			}
    		}
    	}
    }
}
```
* Put in data as before, restart cluster ... and index is there.

**Comment by dadoonet** [comment]
Thank you for reporting this with all those details. I can reproduce it.

**Comment by dadoonet** [comment]
There is a NPE which most likely is causing this:

```
java.lang.NullPointerException
	at org.elasticsearch.cluster.metadata.MappingMetaData.initMappers(MappingMetaData.java:358)
	at org.elasticsearch.cluster.metadata.MappingMetaData.<init>(MappingMetaData.java:292)
	at org.elasticsearch.cluster.metadata.IndexMetaData$Builder.fromXContent(IndexMetaData.java:661)
	at org.elasticsearch.gateway.local.state.meta.LocalGatewayMetaState.loadIndex(LocalGatewayMetaState.java:505)
	at org.elasticsearch.gateway.local.state.meta.LocalGatewayMetaState.clusterChanged(LocalGatewayMetaState.java:270)
	at org.elasticsearch.gateway.local.LocalGateway.clusterChanged(LocalGateway.java:207)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:437)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by meash-nrel** [comment]
@dadoonet - looks like you've located it.   Unsure when this appeared as I used _timestamp successfully before, I believe in 1.3.1. 

I assume from your stack trace of the NPE that this is an issue during cluster startup.  Would the fix now bring back the missing indices?   Meaning that now at cluster startup ES would properly load those indices and they'd be available again.

Thanks.

**Comment by dadoonet** [comment]
@meash-nrel I just ran a test. Reproducing the bug with 1.4.2, then upgrading to 1.4.3-SNAPSHOT and the new version was able to read again old data. So `GET new_index` worked again. It means that you will be able to read again your data with the new version.
