### ISSUE TITLE
Allow document to appear in search results without allowing source to be downloaded

### ISSUE THREAD

**Issue by samzhang111** [elasticsearch/elasticsearch#9231]
I'm trying to set up elasticsearch so that it allows users to discover the existence of documents, without having access to the document itself. For example, imagine a site that aggregates academic articles: they allow full-text search over the body, but only present the abstract.

I am trying to set up a system where different user groups have access to different documents, but everyone has access to the entire index.

Asked a question here: http://stackoverflow.com/questions/27872637/elasticsearch-allow-discovery-of-document-without-exposing-source

**Comment by dadoonet** [comment]
Hi. We are trying to keep this space for issues and feature requests.
You should write your question on the mailing list (or on SOF but you already did It). We can help you there.

That said, you could use filtered aliases to filter documents based on a user id or Group id or whatever, add a proxy on top of elasticsearch to authenticate your users and filter then which aliases they can have access to.
Also up coming Shield project could help you a lot. http://www.elasticsearch.org/overview/shield/
