### ISSUE TITLE
node can not be add to cluster

### ISSUE THREAD

**Issue by londonlee** [elasticsearch/elasticsearch#9232]
hi,
   my elasticsearch cluster have 3 nodes. where i close one node and then restart it, this node can not be add  to cluster (only if i restart all 3 nodes and the cluster will be ok).
 guys know pls tell me ,very thank you.

**Comment by dadoonet** [comment]
I would suggest that you first try to ask on the mailing list your question.
It would help a lot if you provide details about what you are exactly doing, such as which version, settings, environment (cloud? Local?), plugins, logs...

From what you wrote for now, I can only tell that I can not reproduce your issue on my machine.

**Comment by clintongormley** [comment]
As @dadoonet said, I'd start in the mailing list

**Comment by lkebin** [comment]
@clintongormley Why not talk about it at here ?

**Comment by lkebin** [comment]
@clintongormley Can you post the url about this question on the google groups ?
