### ISSUE TITLE
Caret in query not working as expected

### ISSUE THREAD

**Issue by iquito** [elasticsearch/elasticsearch#9235]
I am using elasticsearch 1.4.2., and in some queries I tried to use the caret symbol to boost the query keywords, as described in http://lucene.apache.org/core/2_9_4/queryparsersyntax.html under "Boosting a Term". This is my query:

    { 
      "query": {
        "function_score": {
          "query": {
            "multi_match": {
              "query":    "bla^2.5 blubb",
              "type": "most_fields",
              "fields": [ "title^2.5", "preview_text^1.3" ]
            }
          }
        }
      }
    }

The "bla" keyword should be boosted by the factor 2.5. I found out that boosting via caret works as expected if it is a whole number (^2, ^3, ^4), or if it is less than 1 (^0.2, ^0.5). But when using ^2.5, elasticsearch (or lucene) seems to convert the search query to "bla 2.5 blubb", seeming not to recognize the caret boosting, removing the caret and introducing 2.5 as a new keyword.

**Comment by iquito** [comment]
Actually, it doesn't seem to only affect fractions - any type of caret use in the query has unexpected results. The following queries should have the same results, yet do not:

    { 
      "query": {
        "function_score": {
          "query": {
            "multi_match": {
              "query":    "bla^2 blubb^2",
              "type": "most_fields",
              "fields": [ "title^2.5", "preview_text^1.3" ]
            }
          }
        }
      }
    }

    { 
      "query": {
        "function_score": {
          "query": {
            "multi_match": {
              "query":    "bla blubb",
              "type": "most_fields",
              "fields": [ "title^2.5", "preview_text^1.3" ]
            }
          }
        }
      }
    }

If applied to one keyword only, the caret symbol seems to work sort of as expected (documents with that keyword rank higher), but also documents containing the caret value seem to score higher: when using ^2 for a keyword, then documents containing a 2 in the title appear in the first results, when using ^25, then titles with a 25 in them appear in the first results. I cannot really pinpoint it, but the caret usage is not as I would expect it, but I am not sure what elasticsearch actually does do.

**Comment by clintongormley** [comment]
Hi @iquito 

The `mutil_match` query does not use the lucene query string syntax.  You're looking for the `query_string` query instead.

**Comment by fgrosse** [comment]
@clintongormley The documentation on [elastic.co][1] states that you can use the caret field boosting so I am a littlebit confused right now.

If I want to do a match query over multiple fields while boosting individual fields how am I exactly supposed to do that?

[1]: http://www.elastic.co/guide/en/elasticsearch/guide/master/multi-match-query.html#_boosting_individual_fields

**Comment by clintongormley** [comment]
@fgrosse with `multi_match`, you can use carets in the field names, not in the query itself
