### ISSUE TITLE
Elasticsearch @timestamp affects the background document count(bg_count) of significant_terms aggregation

### ISSUE THREAD

**Issue by jhsbeat** [elasticsearch/elasticsearch#9247]
I'm using Elasticsearch version 1.4.2 to get **significant terms** from the data gettered by Logstash.
When I do the job using the request below, it works fine

# Request (works fine)
    curl -XGET http://localhost:9200/logstash-2014.11.11,logstash-2014.11.12,logstash-2014.11.13,logstash-2014.11.14,logstash-2014.11.15,logstash-2014.11.16,logstash-2014.11.17,logstash-2014.11.18,logstash-2014.11.19,logstash-2014.11.20,logstash-2014.11.21,logstash-2014.11.22,logstash-2014.11.23,logstash-2014.11.24,logstash-2014.11.25,logstash-2014.11.26,logstash-2014.11.27,logstash-2014.11.28,logstash-2014.11.29,logstash-2014.11.30,logstash-2014.12.01,logstash-2014.12.02,logstash-2014.12.03,logstash-2014.12.04,logstash-2014.12.05,logstash-2014.12.06,logstash-2014.12.07,logstash-2014.12.08,logstash-2014.12.09,logstash-2014.12.10,logstash-2014.12.11/my_type/_search?pretty -d '{
        "query": {
            "filtered": {
                "filter": {
                    "and": [
                        {
                            "term": {
                                "myfield.raw":"Something"
                            }
                        }
                    ]
                }
            }
        },
        "aggregations": {
            "agg_by_remote_ip": {
                "significant_terms": {
                    "field": "remote_ip"
                }
            }
        }
    }'

# Results (bg_count == 45203)
    ...
    "aggregations" : {
        "agg_by_remote_ip" : {
          "doc_count" : 102,
          "buckets" : [ {
            "key" : "xx.65.xx.112",
            "doc_count" : 102,
            "score" : 10834.56312205343,
            "bg_count" : 45203
          } ]
        }
    }

However, if I add a **range filter which use @timestamp** like below, then **it reduce the bg_count** of the aggregation results.

# Added range filter 

    {
        "range":{
            "@timestamp":{
                "from":"2014-12-10T15:00:00.000+00:00",
                "to":"2014-12-10T18:00:00.000+00:00"
            }
        }
    } 

# Results (bg_count == 1802)
    ...
    "aggregations" : {
        "agg_by_remote_ip" : {
          "doc_count" : 102,
          "buckets" : [ {
            "key" : "xx.65.xx.112",
            "doc_count" : 102,
            "score" : 10834.56312205343,
            "bg_count" : 1802
          } ]
        }
    }

The reduced bg_count value is equal to the result when I use only "logstash-2014.12.10" index.
So, It seems that a range filter which uses @timestamp field **ignores all indices that is not in the range**.

Is there anyway to use @timestamp while the bg count is the same?

Thanks in advance.

**Comment by clintongormley** [comment]
@markharwood any ideas?

**Comment by markharwood** [comment]
This behaviour is documented [here](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-bucket-significantterms-aggregation.html#_approximate_counts)
If fully accurate counts are required then the client has to issue a subsequent query to collect the background stats.

**Comment by jhsbeat** [comment]
The thing I've missed was [here](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-bucket-significantterms-aggregation.html#_single_set_analysis).

background set used for statistical comparisons is the index or indices **from which the results were gathered.**
