### ISSUE TITLE
Getting SnapshotMissingException when trying to delete a snapshot from a repo

### ISSUE THREAD

**Issue by bplsilva** [elasticsearch/elasticsearch#9252]
This is maybe a bug from Elasticsearch, maybe an issue when using the HTTParty gem to call for a snapshot deletion.

When trying to delete a snapshot from a repo (the snapshot exists) the program return this error:

{"error"=>"RemoteTransportException[[NODE_NAME][inet[/xx.xxx.xxx.xxx:xxxx]][cluster:admin/snapshot/delete]]; nested: SnapshotMissingException[[REPO_NAME:SNAPSHOT_NAME] is missing]; nested: FileNotFoundException[Blob object [SNAPSHOT_NAME] not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: ???)]; ", "status"=>404}

However, it does what it was supposed to do, which is deleting the snapshot.

Could it be an issue from Elasticsearch or is it entirely related to HTTParty?

Thanks,
Bruno

**Comment by clintongormley** [comment]
Hi @bplsilva 

Could you try taking the HTTParty gem out of the picture and providing a full replication of the issue using just `curl`?

**Comment by bplsilva** [comment]
Hello @clintongormley,

Thank you for replying.
The issue does not appears when performing a snapshot deletion via curl. I have also replaced the ruby gem that performs the HTTP calls (switching from httparty to http.rb) and stopped having the problem.

I still wonder if there is something in elasticsearch that could make that issue or if it is all about httparty that would maybe perform a query on the object after his deletion.

Anyway, this does not seem to be an bug in elasticsearch.
Thank you once again,
Bruno
