### ISSUE TITLE
cannot use 'iso' as a field name - ES 1.4.2

### ISSUE THREAD

**Issue by mkrogemann** [elasticsearch/elasticsearch#9256]
When I try to index the following JSON snippet, the 'iso' field will not make it into the index:

{
  "location": {
    "coordinates": {
      "lat": 52.5428524,
      "lng": 13.4278572
    },
    "landmark": "Ernst-Thälmann-Park",
    "venue": "Zeiss-Großplanetarium",
    "city": "Berlin",
    "zip": "10405",
    "street": "Prenzlauer Allee",
    "house": "80",
    "iso": "DE",
    "country": "Deutschland"
  }
}

It works as expected when I change the field's name to 'isoCode'.

I did not find any place in the documentation that mentions 'iso' as being reserved or disallowed.

This happens in ElasticSearch 1.4.2 on MacOSX - Mavericks

**Comment by dadoonet** [comment]
Tested on 1.4.2. MacOS:

```
DELETE test
PUT test/doc/1
{
  "iso": "DE"
}
GET test/_search
{
  "query": {
    "match": {
      "iso": "de"
    }
  }
}
```

Everything is fine. Not sure what your issue is but my first guess would be an analysis problem. May be you are using a TermQuery on `iso` with `DE` as a term which obviously won't work?

Closing but feel free to reopen with more details.

**Comment by mkrogemann** [comment]
When I use cURL to index the JSON snippet, it works as expected. When I index the document through Scala, using the ES Java libs, 'iso' will not make it into the index and will not be mapped. I do not specify any analysers. When I find out what's happening here, I will reopen the issue.

**Comment by mkrogemann** [comment]
Totally my fault - sorry for the noise. It works of course
