### ISSUE TITLE
Help needed for index field mapping after index creation

### ISSUE THREAD

**Issue by bvnagaraju** [elasticsearch/elasticsearch#9258]
we have a scenario where we know set of fields that we need at the time of index creation .This we know how do create field mapping at time of index creation .

But ,
 we have other scenario where users can create custom fields after index creation  and dont know what is the field properties of the field user trying to create .Field properties like data type , IsGrouping and others

Not sure how to do it .? If you can help with us sample code , it will be big help .

Also interested knowing thoughts on document schema this case

**Comment by dadoonet** [comment]
Please see my comment on the same issue #9257

**Comment by bvnagaraju** [comment]
Thank you,can you point me to mailing list

**Comment by dadoonet** [comment]
http://www.elasticsearch.org/help
