### ISSUE TITLE
Too many files for a index

### ISSUE THREAD

**Issue by zhihuiFan** [elasticsearch/elasticsearch#9267]
In my case,  a index have 1016 files while its size is only 27G.  How can I reduce the number of file for a index to avoid using up all the open file handlers?

[root@lvs2b1c-dlqncu5v9t mongodlog-index-2014.12.01]# pwd
/datalog01/elasticsearch/dblogsearch/nodes/0/indices/mongodlog-index-2014.12.01
[root@lvs2b1c-dlqncu5v9t mongodlog-index-2014.12.01]# ls
0  1  2  3  4  _state
[root@lvs2b1c-dlqncu5v9t mongodlog-index-2014.12.01]# find . | wc -l
1016
[root@lvs2b1c-dlqncu5v9t mongodlog-index-2014.12.01]# du -sh .
27G	.

Here is some sample files. 

[root@lvs2b1c-dlqncu5v9t index]# ls /datalog01/elasticsearch/dblogsearch/nodes/0/indices/mongodlog-index-2014.12.01
0  1  2  3  4  _state
[root@lvs2b1c-dlqncu5v9t index]# pwd
/datalog01/elasticsearch/dblogsearch/nodes/0/indices/mongodlog-index-2014.12.01/0/index
[root@lvs2b1c-dlqncu5v9t index]# ls
_1qsy_es090_0.blm     _1ulw.fnm             _1vq6_es090_0.doc     _1w42_Lucene49_0.dvd  _1wnr_es090_0.pos     _1wtu_Lucene49_0.dvm  _1x4o_es090_0.tim     _1x4y.fnm             _1x58_Lucene49_0.dvd
_1qsy_es090_0.doc     _1ulw_Lucene49_0.dvd  _1vq6_es090_0.pos     _1w42_Lucene49_0.dvm  _1wnr_es090_0.tim     _1wtu.nvd             _1x4o_es090_0.tip     _1x4y_Lucene49_0.dvd  _1x58_Lucene49_0.dvm
_1qsy_es090_0.pos     _1ulw_Lucene49_0.dvm  _1vq6_es090_0.tim     _1w42.nvd             _1wnr_es090_0.tip     _1wtu.nvm             _1x4o.fdt             _1x4y_Lucene49_0.dvm  _1x58.nvd
_1qsy_es090_0.tim     _1ulw.nvd             _1vq6_es090_0.tip     _1w42.nvm             _1wnr.fdt             _1wtu.si              _1x4o.fdx             _1x4y.nvd             _1x58.nvm
_1qsy_es090_0.tip     _1ulw.nvm             _1vq6.fdt             _1w42.si              _1wnr.fdx             _1wzo_es090_0.blm     _1x4o.fnm             _1x4y.nvm             _1x58.si
_1qsy.fdt             _1ulw.si              _1vq6.fdx             _1wgu_es090_0.blm     _1wnr.fnm             _1wzo_es090_0.doc     _1x4o_Lucene49_0.dvd  _1x4y.si              _1x59.cfe
_1qsy.fdx             _1vfw_es090_0.blm     _1vq6.fnm             _1wgu_es090_0.doc     _1wnr_Lucene49_0.dvd  _1wzo_es090_0.pos     _1x4o_Lucene49_0.dvm  _1x4z.cfe             _1x59.cfs
_1qsy.fnm             _1vfw_es090_0.doc     _1vq6_Lucene49_0.dvd  _1wgu_es090_0.pos     _1wnr_Lucene49_0.dvm  _1wzo_es090_0.tim     _1x4o.nvd             _1x4z.cfs             _1x59.si
_1qsy_Lucene49_0.dvd  _1vfw_es090_0.pos     _1vq6_Lucene49_0.dvm  _1wgu_es090_0.tim     _1wnr.nvd             _1wzo_es090_0.tip     _1x4o.nvm             _1x4z.si              _1x5a.cfe
_1qsy_Lucene49_0.dvm  _1vfw_es090_0.tim     _1vq6.nvd             _1wgu_es090_0.tip     _1wnr.nvm             _1wzo.fdt             _1x4o.si              _1x57.cfe             _1x5a.cfs
_1qsy.nvd             _1vfw_es090_0.tip     _1vq6.nvm             _1wgu.fdt             _1wnr.si              _1wzo.fdx             _1x4p.cfe             _1x57.cfs             _1x5a.si
_1qsy.nvm             _1vfw.fdt             _1vq6.si              _1wgu.fdx             _1wtu_es090_0.blm     _1wzo.fnm             _1x4p.cfs             _1x57.si              segments_1k
_1qsy.si              _1vfw.fdx             _1w42_es090_0.blm     _1wgu.fnm             _1wtu_es090_0.doc     _1wzo_Lucene49_0.dvd  _1x4p.si              _1x58_es090_0.blm     segments.gen
_1ulw_es090_0.blm     _1vfw.fnm             _1w42_es090_0.doc     _1wgu_Lucene49_0.dvd  _1wtu_es090_0.pos     _1wzo_Lucene49_0.dvm  _1x4y_es090_0.blm     _1x58_es090_0.doc     write.lock
_1ulw_es090_0.doc     _1vfw_Lucene49_0.dvd  _1w42_es090_0.pos     _1wgu_Lucene49_0.dvm  _1wtu_es090_0.tim     _1wzo.nvd             _1x4y_es090_0.doc     _1x58_es090_0.pos
_1ulw_es090_0.pos     _1vfw_Lucene49_0.dvm  _1w42_es090_0.tim     _1wgu.nvd             _1wtu_es090_0.tip     _1wzo.nvm             _1x4y_es090_0.pos     _1x58_es090_0.tim
_1ulw_es090_0.tim     _1vfw.nvd             _1w42_es090_0.tip     _1wgu.nvm             _1wtu.fdt             _1wzo.si              _1x4y_es090_0.tim     _1x58_es090_0.tip
_1ulw_es090_0.tip     _1vfw.nvm             _1w42.fdt             _1wgu.si              _1wtu.fdx             _1x4o_es090_0.blm     _1x4y_es090_0.tip     _1x58.fdt
_1ulw.fdt             _1vfw.si              _1w42.fdx             _1wnr_es090_0.blm     _1wtu.fnm             _1x4o_es090_0.doc     _1x4y.fdt             _1x58.fdx
_1ulw.fdx             _1vq6_es090_0.blm     _1w42.fnm             _1wnr_es090_0.doc     _1wtu_Lucene49_0.dvd  _1x4o_es090_0.pos     _1x4y.fdx             _1x58.fnm

**Comment by dadoonet** [comment]
You should ask questions like this on the mailing list as it's not an issue or a feature request.

That said, you could first decrease the number of shards or add more nodes to your cluster.

Closing.
