### ISSUE TITLE
ElasticSearch Plugins with its own thread pools

### ISSUE THREAD

**Issue by anandsrini85** [elasticsearch/elasticsearch#9268]
When custom analyzer plugin with its own set of thread pools are installed into the ElasticSearch, the following error is observed. The elasticsearch fails to initialize and threads are stopped. IconAnalyzer calls the thread to run some text analysis.

org.elasticsearch.indices.IndexCreationException: [index] failed to create index

        at org.elasticsearch.indices.InternalIndicesService.createIndex(Internal
IndicesService.java:301)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNew
Indices(IndicesClusterStateService.java:313)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterC
hanged(IndicesClusterStateService.java:182)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.r
un(InternalClusterService.java:431)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecu
tor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
        at org.elasticsearch.index.analysis.IconAnalyzer.<init>(IconAnalyzer.jav
a:38)

**Comment by clintongormley** [comment]
I'm guessing your code is doing something wrong.  Without seeing your code, there's not much advice we can give.

**Comment by anandsrini85** [comment]
Thanks. Solved the issue with the code. Quick question regarding the thread pools, if the plugin runs its  own thread pool will it consume the thread pool of ES?

**Comment by clintongormley** [comment]
Please ask questions like these on the mailing list.
