### ISSUE TITLE
[CI-Failure] Failure to clear ID cache in SimpleChildQuerySearch test

### ISSUE THREAD

**Issue by markharwood** [elasticsearch/elasticsearch#9270]
http://build-us-00.elasticsearch.org/job/es_core_master_centos/2270/

Can be reproduced. 

REPRODUCE WITH  : mvn clean test -Dtests.seed=34AF4406203E7487 -Dtests.class=org.elasticsearch.search.child.SimpleChildQuerySearchTests -Dtests.method="testClearIdCacheBug" -Des.logger.level=DEBUG -Des.node.mode=network -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=512m -Dtests.jvm.argline="-server -XX:+UseParallelGC -XX:-UseCompressedOops" -Dtests.locale=es_CU -Dtests.timezone=America/Cayman -Dtests.processors=4
Throwable:
java.lang.AssertionError: 
Expected: <0L>
     got: <1360L>

    __randomizedtesting.SeedInfo.seed([34AF4406203E7487:D44F97762EE7882B]:0)
    [...org.junit.*]
    org.elasticsearch.search.child.SimpleChildQuerySearchTests.testClearIdCacheBug(SimpleChildQuerySearchTests.java:362)
    [...sun.*, java.lang.reflect.*, com.carrotsearch.randomizedtesting.*]
    org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:50)
    org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:46)

**Comment by markharwood** [comment]
Another FieldData cache-clearing issue - related?
http://build-us-00.elasticsearch.org/job/es_core_master_metal/6983

**Comment by dakrone** [comment]
This is related also:
http://build-us-00.elasticsearch.org/job/es_core_master_centos/2301/

I dug into this a little bit the other day, while it looks like a breaker failure, it's actually something were clearing the field data cache does not actually remove everything from the cache. The size remained higher than 0 despite running `.invalidateAll()` followed by `.cleanUp()` on the `Cache<>` object

**Comment by markharwood** [comment]
I think there's a concurrency issue - 6983 fails with -Des.node.mode=local but passes when this isn't set.
I started logging the steps these two modes take and got these outputs (Tx means thread x):


Failing test (-Des.node.mode=local)

    T2,shard0 TransportClearIndicesCacheAction start clearing caches on index test
    T3,shard1 TransportClearIndicesCacheAction start clearing caches on index test
    T1,shard0 TransportClearIndicesCacheAction start clearing caches on index test
    T2,shard0	IndexFieldDataServiceclear() calling fieldData.clear() for index test names=field 
    T4,shard1 TransportClearIndicesCacheAction start clearing caches on index test
    T1,shard0	IndexFieldDataServiceclear() calling fieldData.clear() for index test names=field 
    T2,shard0		PagedBytesIndexFieldData.clear() calling cache IndexFieldCache.clear(field)
    T1,shard0		PagedBytesIndexFieldData.clear() calling cache IndexFieldCache.clear(field)
    T1,shard0	IndexFieldDataServiceclear() calling fieldData.clear() for index test names=field2 
    T1,shard0		PagedBytesIndexFieldData.clear() calling cache IndexFieldCache.clear(field2)
    T2,shard0		IndexFieldCache.clear(field) - checking seg 203933760 on index cache [test] for field field node=node_s0
    T2,shard0			IndexFieldCache.clear(field) - found field, clearing
    T2,shard0	IndexFieldDataServiceclear() calling fieldData.clear() for index test names=field2 
    T2,shard0		PagedBytesIndexFieldData.clear() calling cache IndexFieldCache.clear(field2)


Passing test (non-local mode)

    T1,shard0 TransportClearIndicesCacheAction start clearing caches on index test
    T4,shard1 TransportClearIndicesCacheAction start clearing caches on index test
    T2,shard0 TransportClearIndicesCacheAction start clearing caches on index test
    T3,shard1 TransportClearIndicesCacheAction start clearing caches on index test
    T4,shard1	IndexFieldDataServiceclear() calling fieldData.clear() for index test names=field 
    T1,shard0	IndexFieldDataServiceclear() calling fieldData.clear() for index test names=field 
    T4,shard1		PagedBytesIndexFieldData.clear() calling cache IndexFieldCache.clear(field)
    T1,shard0		PagedBytesIndexFieldData.clear() calling cache IndexFieldCache.clear(field)
    T4,shard1		IndexFieldCache.clear(field) - checking seg 546713328 on index cache [test] for field field node=node_s0
    T1,shard0		IndexFieldCache.clear(field) - checking seg 1675861830 on index cache [test] for field field node=node_s1
    T4,shard1	IndexFieldDataServiceclear() calling fieldData.clear() for index test names=field2 
    T1,shard0			IndexFieldCache.clear(field) - found field, clearing
    T4,shard1		PagedBytesIndexFieldData.clear() calling cache IndexFieldCache.clear(field2)
    T4,shard1		IndexFieldCache.clear(field2) - checking seg 546713328 on index cache [test] for field field2 node=node_s0
    T4,shard1			IndexFieldCache.clear(field2) - found field, clearing
    T1,shard0	IndexFieldDataServiceclear() calling fieldData.clear() for index test names=field2 
    T1,shard0		PagedBytesIndexFieldData.clear() calling cache IndexFieldCache.clear(field2)

Note that in the failing test, shard 1 is not cleared. I started debugging to dig deeper but this changed the sequencing of behaviours and the test passed which indicates some kind of concurrency issue here.

**Comment by markharwood** [comment]
Spent a while looking into this dumping the IDs of the various instances of keys and caches being created and by which threads. It looks like in the scenarios where it fails there is a spurious "onRemoval" event being triggered almost as soon as a new entry is added to the cache:

    [2015-01-16 15:52:03,298][INFO ][org.elasticsearch.cluster.metadata] [node_s0] [test] creating index, cause [api], templates [random_index_template], shards [2]/[1], mappings []
    [2015-01-16 15:52:03,608][INFO ][org.elasticsearch.cluster.metadata] [node_s0] [test] update_mapping [type] (dynamic)
    elasticsearch[node_s1][search][T#2]  starting load of resource for key [k=83759445 f=field r=1062805872 ifc=663461528ifc.cache=1143203330]
    elasticsearch[node_s1][search][T#2]	  ShardFieldData increasing ram used  by 284 src=1853463147 for field field
    elasticsearch[node_s1][search][T#2]		finished loading leafReader for key=[k=83759445 f=field r=1062805872 ifc=663461528ifc.cache=1143203330]
    elasticsearch[node_s1][search][T#5] guava cache  removalListener.onRemoval  key [k=83759445 f=field r=1062805872 ifc=663461528ifc.cache=1143203330]
    elasticsearch[node_s1][search][T#5] listener decrementing the ram used by 284 bytes
    elasticsearch[node_s1][search][T#5]  starting load of resource for key [k=335974664 f=field r=1062805872 ifc=663461528ifc.cache=1143203330]
    elasticsearch[node_s1][search][T#5]	  ShardFieldData increasing ram used  by 284 src=991669885 for field field
    elasticsearch[node_s1][search][T#5]		finished loading leafReader for key=[k=335974664 f=field r=1062805872 ifc=663461528ifc.cache=1143203330]
    elasticsearch[node_s0][search][T#6]  starting load of resource for key [k=1473214828 f=field2 r=1685032431 ifc=1041451583ifc.cache=1982647933]
    elasticsearch[node_s0][search][T#6]	  ShardFieldData increasing ram used  by 284 src=2007543079 for field field2
    elasticsearch[node_s0][search][T#6]		finished loading leafReader for key=[k=1473214828 f=field2 r=1685032431 ifc=1041451583ifc.cache=1982647933]
    elasticsearch[node_s0][search][T#8]		finished loading leafReader for key=[k=1746987438 f=field2 r=1685032431 ifc=1041451583ifc.cache=1982647933]
    elasticsearch[node_s1][management][T#1] TransportClearIndicesCacheAction start clearing caches on index test
    elasticsearch[node_s0][management][T#2] TransportClearIndicesCacheAction start clearing caches on index test
    elasticsearch[node_s0][management][T#4] TransportClearIndicesCacheAction start clearing caches on index test
    elasticsearch[node_s1][management][T#2] TransportClearIndicesCacheAction start clearing caches on index test
    elasticsearch[node_s1][management][T#1]		663461528 IndexFieldCache.clear(field) - being called on keys  in indexService 862694802 cache=1143203330
    elasticsearch[node_s1][management][T#1]		1649436317 IndexFieldCache.clear(field2) - being called on keys  in indexService 862694802 cache=1143203330
    elasticsearch[node_s0][management][T#2]		209780696 IndexFieldCache.clear(field) - being called on keys test/field2  in indexService 1763492945 cache=1982647933
    elasticsearch[node_s1][management][T#1]		IndexFieldCache663461528 clear() starting...
    elasticsearch[node_s0][management][T#2]		1041451583 IndexFieldCache.clear(field2) - being called on keys test/field2  in indexService 1763492945 cache=1982647933
    elasticsearch[node_s1][management][T#1]		IndexFieldCache1649436317 clear() starting...
    elasticsearch[node_s0][management][T#2]		IndexFieldCache.clear([k=1473214828 f=field2 r=1685032431 ifc=1041451583ifc.cache=1982647933])  invalidating key...
    elasticsearch[node_s0][management][T#2] guava cache  removalListener.onRemoval  key [k=1473214828 f=field2 r=1685032431 ifc=1041451583ifc.cache=1982647933]
    elasticsearch[node_s0][management][T#2] listener decrementing the ram used by 284 bytes
    elasticsearch[node_s0][management][T#2]		IndexFieldCache209780696 clear() starting...
    elasticsearch[node_s0][management][T#2]		IndexFieldCache1041451583 clear() starting...
    [2015-01-16 15:52:03,962][INFO ][org.elasticsearch.indices.stats] [IndexStatsTests#testFieldDataStats]: cleaning up after test
    [2015-01-16 15:52:03,967][INFO ][org.elasticsearch.cluster.metadata] [node_s0] [test] deleting index
    [2015-01-16 15:52:03,968][INFO ][org.elasticsearch.test.store] [node_s1] [test][0] Shard state before potentially flushing is STARTED
    [2015-01-16 15:52:03,970][INFO ][org.elasticsearch.test.store] [node_s1] [test][0] flush finished in beforeIndexShardClosed
    [2015-01-16 15:52:03,971][INFO ][org.elasticsearch.test.store] [node_s1] [test][0] start check index
    [2015-01-16 15:52:03,977][INFO ][org.elasticsearch.test.store] [node_s1] [test][0] end check index
    elasticsearch[node_s1][clusterService#updateTask][T#1]IndexFieldCache.close() is invalidating reader 1062805872 cache=1143203330 field=field
    elasticsearch[node_s1][clusterService#updateTask][T#1] guava cache  removalListener.onRemoval  key [k=335974664 f=field r=1062805872 ifc=663461528ifc.cache=1143203330]
    elasticsearch[node_s1][clusterService#updateTask][T#1] listener decrementing the ram used by 284 bytes

A healthy run (with local mode turned off) only has onRemoval being triggered as part of normal clear() operations:

   
    [2015-01-16 15:49:28,346][INFO ][org.elasticsearch.cluster.metadata] [node_s0] [test] creating index, cause [api], templates [random_index_template], shards [2]/[1], mappings []
    elasticsearch[node_s0][clusterService#updateTask][T#1]	IndexFieldDataService mapping update!!!!!! 
    [2015-01-16 15:49:28,877][INFO ][org.elasticsearch.cluster.metadata] [node_s0] [test] update_mapping [type] (dynamic)
    elasticsearch[node_s0][search][T#2]  starting load of resource for key [k=1395989926 f=field r=809938711 ifc=541039787ifc.cache=1143842807]
    elasticsearch[node_s0][search][T#2]	  ShardFieldData increasing ram used  by 284 src=697242378 for field field
    elasticsearch[node_s0][search][T#2]		finished loading leafReader for key=[k=1395989926 f=field r=809938711 ifc=541039787ifc.cache=1143842807]
    elasticsearch[node_s1][search][T#4]  starting load of resource for key [k=1054474989 f=field r=770618889 ifc=57543777ifc.cache=1526085079]
    elasticsearch[node_s1][search][T#4]	  ShardFieldData increasing ram used  by 284 src=1514726632 for field field
    elasticsearch[node_s1][search][T#4]		finished loading leafReader for key=[k=1054474989 f=field r=770618889 ifc=57543777ifc.cache=1526085079]
    elasticsearch[node_s1][search][T#7]  starting load of resource for key [k=1825474479 f=field2 r=770618889 ifc=96321810ifc.cache=1526085079]
    elasticsearch[node_s1][search][T#7]	  ShardFieldData increasing ram used  by 284 src=1798187511 for field field2
    elasticsearch[node_s1][search][T#7]		finished loading leafReader for key=[k=1825474479 f=field2 r=770618889 ifc=96321810ifc.cache=1526085079]
    elasticsearch[node_s1][search][T#10]		finished loading leafReader for key=[k=2007543079 f=field2 r=770618889 ifc=96321810ifc.cache=1526085079]
    elasticsearch[node_s1][management][T#2] TransportClearIndicesCacheAction start clearing caches on index test
    elasticsearch[node_s0][management][T#1] TransportClearIndicesCacheAction start clearing caches on index test
    elasticsearch[node_s0][management][T#2] TransportClearIndicesCacheAction start clearing caches on index test
    elasticsearch[node_s1][management][T#1] TransportClearIndicesCacheAction start clearing caches on index test
    elasticsearch[node_s0][management][T#1]		541039787 IndexFieldCache.clear(field) - being called on keys test/field  in indexService 6571565 cache=1143842807
    elasticsearch[node_s1][management][T#2]		57543777 IndexFieldCache.clear(field) - being called on keys test/field2 test/field  in indexService 760250745 cache=1526085079
    elasticsearch[node_s0][management][T#1]		IndexFieldCache.clear([k=1395989926 f=field r=809938711 ifc=541039787ifc.cache=1143842807])  invalidating key...
    elasticsearch[node_s1][management][T#2]		IndexFieldCache.clear([k=1054474989 f=field r=770618889 ifc=57543777ifc.cache=1526085079])  invalidating key...
    elasticsearch[node_s0][management][T#1] guava cache  removalListener.onRemoval  key [k=1395989926 f=field r=809938711 ifc=541039787ifc.cache=1143842807]
    elasticsearch[node_s1][management][T#2] guava cache  removalListener.onRemoval  key [k=1054474989 f=field r=770618889 ifc=57543777ifc.cache=1526085079]
    elasticsearch[node_s0][management][T#1] listener decrementing the ram used by 284 bytes
    elasticsearch[node_s1][management][T#2] listener decrementing the ram used by 284 bytes
    elasticsearch[node_s0][management][T#1]		1746987438 IndexFieldCache.clear(field2) - being called on keys  in indexService 6571565 cache=1143842807
    elasticsearch[node_s1][management][T#2]		96321810 IndexFieldCache.clear(field2) - being called on keys test/field2  in indexService 760250745 cache=1526085079
    elasticsearch[node_s0][management][T#1]		IndexFieldCache541039787 clear() starting...
    elasticsearch[node_s1][management][T#2]		IndexFieldCache.clear([k=1825474479 f=field2 r=770618889 ifc=96321810ifc.cache=1526085079])  invalidating key...
    elasticsearch[node_s0][management][T#1]		IndexFieldCache1746987438 clear() starting...
    elasticsearch[node_s1][management][T#2] guava cache  removalListener.onRemoval  key [k=1825474479 f=field2 r=770618889 ifc=96321810ifc.cache=1526085079]
    elasticsearch[node_s1][management][T#2] listener decrementing the ram used by 284 bytes
    elasticsearch[node_s1][management][T#2]		IndexFieldCache57543777 clear() starting...
    elasticsearch[node_s1][management][T#2]		IndexFieldCache96321810 clear() starting...
    [2015-01-16 15:49:29,057][INFO ][org.elasticsearch.indices.stats] [IndexStatsTests#testFieldDataStats]: cleaning up after test
    [2015-01-16 15:49:29,064][INFO ][org.elasticsearch.cluster.metadata] [node_s0] [test] deleting index
    [2015-01-16 15:49:29,066][INFO ][org.elasticsearch.test.store] [node_s1] [test][0] Shard state before potentially flushing is STARTED
    [2015-01-16 15:49:29,068][INFO ][org.elasticsearch.test.store] [node_s1] [test][0] flush finished in beforeIndexShardClosed
    [2015-01-16 15:49:29,070][INFO ][org.elasticsearch.test.store] [node_s1] [test][0] start check index
    [2015-01-16 15:49:29,077][INFO ][org.elasticsearch.test.store] [node_s1] [test][0] end check index
    elasticsearch[node_s1][clusterService#updateTask][T#1]IndexFieldCache.close() is invalidating reader 770618889 cache=1526085079 field=field
    elasticsearch[node_s1][clusterService#updateTask][T#1]IndexFieldCache.close() is invalidating reader 770618889 cache=1526085079 field=field2
    [2015-01-16 15:49:29,085][INFO ][org.elasticsearch.test.store] [node_s0] [test][0] Shard state before potentially flushing is STARTED
    [2015-01-16 15:49:29,086][INFO ][org.elasticsearch.test.store] [node_s0] [test][0] flush finished in beforeIndexShardClosed
    [2015-01-16 15:49:29,087][INFO ][org.elasticsearch.test.store] [node_s0] [test][0] start check index
    [2015-01-16 15:49:29,088][INFO ][org.elasticsearch.test.store] [node_s0] [test][0] end check index
    elasticsearch[node_s0][clusterService#updateTask][T#1]IndexFieldCache.close() is invalidating reader 809938711 cache=1143842807 field=field
