### ISSUE TITLE
Distinguish different exception types in bulk response

### ISSUE THREAD

**Issue by Hocdoc** [elasticsearch/elasticsearch#9274]
I want to distinguish different exception types of failed documents in the bulk response with the Java client.

F.ex. I want to ignore all documents that failed with a `DocumentAlreadyExistsException` but retry docs that failed for other reasons.

I wish there would be a `exceptionClassName` field in the `BulkItemResponse.Failure` class to distinguish exception types without needing to parse the fragile failure message.

(See my [Stackoverflow question](http://stackoverflow.com/questions/27922390/catch-a-specific-elasticsearch-exception-from-a-bulkrequest) for a concrete example where this would be useful).

**Comment by clintongormley** [comment]
Related to #3303

Parseable exceptions have long been on the "want" list.  Labelling for discussion.

**Comment by colings86** [comment]
Closing in favour of #3303
