### ISSUE TITLE
integer overflow, if sorting by date and date = null

### ISSUE THREAD

**Issue by frad00r4** [elasticsearch/elasticsearch#9276]
sorry for my english :(
query example:
```javascript
 {"query": {"query_string":{"fields":["name^2","text","user"],"query":"messages"}},"highlight":{"fields":{"text":{"number_of_fragments":0},"user":{"number_of_fragments":0}}},"sort":[{"ts_date":{"order":"desc"}}]}
```

in the output elements which "ts_date: null" contain:
"sort": [-9223372036854776000]
where int (32 bit) catches the error "integer overflow"

**Comment by clintongormley** [comment]
Hi @frad00r4 

It seems that your integer overflow in happening on the client side? Dates are longs, not integers.

**Comment by frad00r4** [comment]
Client size php - json_decode.
minimal: -9223372036854775808

**Comment by clintongormley** [comment]
@frad00r4 i don't know what you mean.  where are you seeing this error? in your PHP code or in the elasticsearch log?

**Comment by frad00r4** [comment]
I realized that long in java little more than php, and this caused a problem. Google finds many such problems. The problem is not elastcisearch.
