### ISSUE TITLE
Is there a feature where I can all documents in a family

### ISSUE THREAD

**Issue by bvnagaraju** [elasticsearch/elasticsearch#9289]
Hi,
I have question on document relations 

one document can have multiple child's. and now I have to address below searches and achieve the mentioned expected results .

1)
search on any child documents(meaning have a query that qualifies child documents) and retrieve the child ,parent and all of the child's of the parents

2)

search on any parent documents and retrieve parent and all of the child documents

3) search on any parent documents and just retrieve only qualified parent documents

4) search on any child documents  and just retrieve only qualified child documents

Is there any existing feature that help in achieving this ? any ideas /thoughts would be very useful ?
also please provide some sample code if possible

**Comment by dadoonet** [comment]
Answer was provided on the mailing list which is the Best place for questions: https://groups.google.com/d/msgid/elasticsearch/b7e564f3-9338-4078-93ba-34fa1e208735%40googlegroups.com?utm_medium=email&utm_source=footer
