### ISSUE TITLE
terms aggregation on the _id

### ISSUE THREAD

**Issue by yukiman76** [elasticsearch/elasticsearch#9298]
i am unable to do an aggregation on _id
py script below to show 

q11 = {
    "aggs": {
        "ids": {
            "terms": {
                "field": "_id",
                "size": 10
            }
        }
    }
} 

uri = 'https://10.164.113.186/logstash-2014.08.01/_search?search_type=count'
r = requests.get(uri, data=json.dumps(q11), verify=False)
print r.text

u'{"took":9,"timed_out":false,"_shards":{"total":7,"successful":7,"failed":0},"hits":{"total":900711,"max_score":0.0,"hits":[]},"aggregations":{"ids":{"buckets":[]}}}'

are aggressions on _id allowed

**Comment by jpountz** [comment]
They are currently supported only if the field is indexed (which defaults to false). Please note that fielddata for this field will require a lot of memory given that values are typically unique.

Please use the mailing-list for questions in the future, thanks!

**Comment by lukens** [comment]
In case anyone ends up finding this answer when searching for whether you can use `_id` in a terms aggregation, it may be useful to note that if the `_id` isn't indexed, you can instead aggregate on `_uid` which may be sufficient for your needs (and includes the id in it, as it is of the form `<_type>#<_id>`).

**Comment by dougmolineux** [comment]
@lukens Thank you, this helped me a ton! :)

**Comment by davidrapin** [comment]
@lukens Looking for the same kind of solution, but there was a problem for me : this solution will **not** deduplicate documents with the same `_uid` that are from different types (my use-case).

e.g.: multi-type query (types: `t1` and `t2`)
```JSON
POST idx1/t1,t2/_search?q=*
{
  "aggs":{
    "dedup" : {
      "terms":{
        "field": "_uid"
       },
       "aggs":{
         "dedup_docs":{
           "top_hits":{
             "size":1
           }
         }
       }    
    }
  }
}
``` 

Response (the type is included in the `_uid` aggregation key for some reason):
```JSON
{
   [...]
   "aggregations": {
      "dedup": {
         "doc_count_error_upper_bound": 0,
         "sum_other_doc_count": 0,
         "buckets": [
            {
               "key": "t1#1",
               "doc_count": 1,
               "dedup_docs": {
                  "hits": {
                     "total": 1,
                     "max_score": 1,
                     "hits": [
                        {
                           "_index": "idx1",
                           "_type": "t1",
                           "_id": "1",
                           "_score": 1,
                           "_source": {
                              "f1": "v1"
                           }
                        }
                     ]
                  }
               }
            },
            {
               "key": "t1#2",
               "doc_count": 1,
               "dedup_docs": {
                  "hits": {
                     "total": 1,
                     "max_score": 1,
                     "hits": [
                        {
                           "_index": "idx1",
                           "_type": "t1",
                           "_id": "2",
                           "_score": 1,
                           "_source": {
                              "f1": "v1"
                           }
                        }
                     ]
                  }
               }
            },
            {
               "key": "t2#1",
               "doc_count": 1,
               "dedup_docs": {
                  "hits": {
                     "total": 1,
                     "max_score": 1,
                     "hits": [
                        {
                           "_index": "idx1",
                           "_type": "t2",
                           "_id": "1",
                           "_score": 1,
                           "_source": {
                              "f1": "v1"
                           }
                        }
                     ]
                  }
               }
            }
         ]
      }
   }
```
