### ISSUE TITLE
apt repository doesn't support non-x86 architectures

### ISSUE THREAD

**Issue by dannf** [elasticsearch/elasticsearch#9299]
elasticsearch kindly provides a repository for APT-based distributions:
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/setup-repositories.html

However, this repository currently only provides metadata (Packages files) for the "amd64" and "i386" architectures. The deb itself is Binary:all, and therefore can be installed on other architectures. Would it be possible to also provide metadata for other architectures supported by APT? I'm personally most interested in the arm64 (ARMv8) architecture, but the other architectures maybe useful to others.

Perhaps this could be handled with a wildcard URL (/binary-*/Packages.gz) but if not, for reference, I've included the full set of supported or in-devel Linux-based ports below. Obviously most of them are not likely targets for a production elasticsearch cluster, but who am I to judge :)

If this is not feasible, please consider documenting a workaround for such users by adding an arch tag to the sources.list entry like so to tell apt to override the arch string:
deb [arch=amd64] http://packages.elasticsearch.org/elasticsearch/

alpha
armel
armhf
hppa
ia64
m68k
mips
mipsel
powerpc
powerpcspe
ppc64
ppc64el
s390
s390x
sh4
sparc
sparc64
x32

**Comment by electrical** [comment]
Very interesting issue. I was completely unaware of this.
I think we should document the workaround rather then creating more metadata that may or may not be used.

@spinscale what are your thoughts on this?

**Comment by dannf** [comment]
If you'd prefer to only enable metadata for architectures that you know are being used, then I'd just ask adding arm64 to that list - I can confirm that it is being used.

**Comment by jpountz** [comment]
This is an architecture that we do not test on currently, so I would be a bit worried to provide packages for an architecture that we do not test.

**Comment by colings86** [comment]
Closing this as we don;t want to provide packages for architecture which we are not testing. On these architectures Elasticsearch can still be installed from the zip or tar.gz distributions
