### ISSUE TITLE
polygon filter is not accurate for geo_point type

### ISSUE THREAD

**Issue by ivanlw** [elasticsearch/elasticsearch#9301]
Hi, I have a large mount of data that have already been indexed into ES, I tried a query using polygon filter for a small polygon, it works fine and returns 824 hits.

However, I tried to separate the polygon into two half, left and right. The query for the left half polygon returns 0 record, while the query for right half polygon returns all the records, which is 824. 
And then I tried a query for an even smaller polygon, which is about 1/20 of the right half and inside the right half, it also returns 824 hits. So there must be something wrong here, can anyone tell me the possible reason?

P.S. I didn't set **precision** option, which value would be 1cm by default, I think this is accurate enough. I also didn't set **lat_lon** and **geo_hash** which means they are all false by default, but according to the document [here](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-geo-point-type.html), setting these two values can only help the query more efficient, they have nothing to do with the accuracy.

**Comment by clintongormley** [comment]
Hi @ivanlw 

Please ask questions like these in the mailing list.  This issues list is for bug fixed and feature requests.

thanks

**Comment by ivanlw** [comment]
Thanks, sorry for that.
