### ISSUE TITLE
Sorting with nested_filter does not work with inner nested document

### ISSUE THREAD

**Issue by pickypg** [elasticsearch/elasticsearch#9305]
Using an inner nested filter within a `nested_filter` for `sort`ing does not work (tested in 1.4.2) and it silently fails to handle the inner nested filter.

The corresponding test code is commented out at https://github.com/elasticsearch/elasticsearch/tree/v1.4.2/src/test/java/org/elasticsearch/nested/SimpleNestedTests.java#L1171

Example follows:

```
PUT /test
{"mappings":{"type":{"properties":{"officelocation":{"type":"string"},"users":{"type":"nested","properties":{"first":{"type":"string"},"last":{"type":"string"},"workstation":{"type":"nested","properties":{"stationid":{"type":"string"},"phoneid":{"type":"string"}}}}}}}}}

PUT /test/type/1
{"officelocation":"glendale","users":[{"first":"fname1","last":"lname1","workstation":[{"stationid":"s1","phoneid":"p1"},{"stationid":"s2","phoneid":"p2"}]},{"first":"fname2","last":"lname2","workstation":[{"stationid":"s3","phoneid":"p3"},{"stationid":"s4","phoneid":"p4"}]},{"first":"fname3","last":"lname3","workstation":[{"stationid":"s5","phoneid":"p5"},{"stationid":"s6","phoneid":"p6"}]}]}

PUT /test/type/2
{"officelocation":"glendale","users":[{"first":"fname4","last":"lname4","workstation":[{"stationid":"s1","phoneid":"p1"},{"stationid":"s2","phoneid":"p2"}]},{"first":"fname5","last":"lname5","workstation":[{"stationid":"s3","phoneid":"p3"},{"stationid":"s4","phoneid":"p4"}]},{"first":"fname1","last":"lname1","workstation":[{"stationid":"s5 ss","phoneid":"p5"},{"stationid":"s6","phoneid":"p6"}]}]}

GET /test/_search
{
  "fields": "_id",
  "sort": [
    {
      "users.first": {
        "order": "asc"
      }
    },
    {
      "users.first": {
        "order": "asc",
        "nested_path": "users",
        "nested_filter": {
          "nested": {
            "path": "users.workstation",
            "filter": {
              "term": {
                "users.workstation.stationid": "s5"
              }
            }
          }
        }
      }
    }
  ]
}
```

This returns

```
{
   "took": 9,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 2,
      "max_score": null,
      "hits": [
         {
            "_index": "test",
            "_type": "myType",
            "_id": "1",
            "_score": null,
            "sort": [
               "fname1",
               null // <- should be "fname3"
            ]
         },
         {
            "_index": "test",
            "_type": "myType",
            "_id": "2",
            "_score": null,
            "sort": [
               "fname1",
               null // <- should be "fname1"
            ]
         }
      ]
   }
}
```

Here is the nested filter as a query:

```
GET /test/_search
{"query":{"filtered":{"filter":{"nested":{"path":"users","filter":{"nested":{"path":"users.workstation","filter":{"term":{"users.workstation.stationid":"s5"}}}}}}}}}
```

**Comment by navneet83** [comment]
A possible workaround for this problem would be to index inner "workstation" object **both** as nested fields and as flattened object field.This can be achieved by setting **"include_in_parent"** to **true**.
Here is the updated schema (note the ```"include_in_parent":"true"``` under **workstation** :
```PUT /test```
```json
{"mappings":{"type":{"properties":{"officelocation":{"type":"string"},"users":{"type":"nested","properties":{"first":{"type":"string"},"last":{"type":"string"},"workstation":{"type":"nested", "include_in_parent":"true" ,"properties":{"stationid":{"type":"string"},"phoneid":{"type":"string"}}}}}}}}}
```
Here is the updated query:
```POST test/_search```
```json
{
  "fields":"_id",
  "sort":[
    {
      "users.first":{
        "order":"asc"
      }
    },
    {
      "users.first":{
        "order":"asc",
        "nested_path":"users",
        "nested_filter":{
          "term":{
            "users.workstation.stationid":"s5"
          }
        }
      }
    }
  ]
}
```
This returns:
```json
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : null,
    "hits" : [ {
      "_index" : "test123",
      "_type" : "type",
      "_id" : "2",
      "_score" : null,
      "sort" : [ "fname1", "fname1" ]
    }, {
      "_index" : "test123",
      "_type" : "type",
      "_id" : "1",
      "_score" : null,
      "sort" : [ "fname1", "fname3" ]
    } ]
  }
}
```

**Comment by martijnvg** [comment]
The reason why the sorting goes wrong here is that the nested query is dependant about the nested context it is placed in. If a nested query has no other nested query above it, it assumes that it is should link back to the main/root document. If a nested query is placed under another nested query then it assumes it should link back to nested level that belong to the path the parent nested query has been set to. Nested sorting doesn't set this nested context and therefor the nested query doesn't link back to the `users` level, but to the root level instead.

We need to make sure that nested sorting sets the nested level properly, so that other nested queries know about this. The tricky bit is here that due to how the sorting elements gets parsed (in a streaming manner), the nested filter may be parsed before the `path` field has been parsed, so in order to do this properly the filter should be parsed after the `path` field has been parsed.

**Comment by angelatsai** [comment]
I encountered the same problem, too. 

The include_in_parent workaround can solve this problem only when you don't need the relations defined in workstation nested object.

For example, if you need to filter by workstation {"stationid":"s5","phoneid":"p6"}, user {"first":"fname3","last":"lname3","workstation":[{"stationid":"s5","phoneid":"p5"},{"stationid":"s6","phoneid":"p6"}]} in the first document would match, even there's no {"stationid":"s5","phoneid":"p6"} in his workstations.
