### ISSUE TITLE
Feature request: sort by count of elements in array 

### ISSUE THREAD

**Issue by aeryaguzov** [elasticsearch/elasticsearch#9307]
There are some options for sort when field is array: 
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-sort.html#_sort_mode_option

It will be great to have "count" mode, when value for array is calculated as array length.

**Comment by clintongormley** [comment]
Hi @aeryaguzov 

A count might not be accurate, as only unique terms will be taken into account, eg [1,1,1,1] would have a count of 1

I suggest just indexing the count as a separate field (as this is a value known at index time)

**Comment by tuckerpm** [comment]
In my current scenario, getting 1 would solve our problem and be much better than reindexing all of our data.

**Comment by pencilcheck** [comment]
So if the index already built, what would be the solution to this problem? Scripting somehow doesn't work.
