### ISSUE TITLE
cluster.routing.allocation.disk.threshold_enabled accepts wrong values

### ISSUE THREAD

**Issue by konradkonrad** [elasticsearch/elasticsearch#9309]
I found this on **1.1.2** -- if it is already fixed in later versions feel free to close:

The cluster-settings-API happily accepts the string `"true"` for the `cluster.routing.allocation.disk.threshold_enabled` setting. But -- otherwise I wouldn't file this issue -- `"true"` is not interpreted as boolean `TRUE`. This makes for a rather dangerous and difficult to spot user error. Since there is already some parsing in place, that neglects wrong settings, I would expect a non boolean-y string value in the settings JSON to be neglected for boolean settings. I haven't tested other cluster settings were this could occur.

Example settings:

    curl http://localhost:9200/_cluster/settings?pretty
    {
        "persistent":{
            "cluster":{
                "routing":{
                    "allocation":{
                        "disk":{
                            "watermark":{
                                "low":"0.85",
                                "high":"0.95"
                            },
                            "threshold_enabled":"true"
                        }
                    }
                }
            }
        }
    }

With the above settings, the disk.watermark setting is inactive!

**Comment by dakrone** [comment]
@konradkonrad thanks for finding this, I will fix it

**Comment by konradkonrad** [comment]
Wow! That was fast, thanks @dakrone :)
