### ISSUE TITLE
Discuss : Boost for synonyms

### ISSUE THREAD

**Issue by utk4rsh** [elasticsearch/elasticsearch#9314]
Let's say S1, S2, S3, S4 are synonyms (to be more precise related terms). However S2 is closer in meaning to S1 than S3 and S4. 

So basically the requirement is to define S1, S2, S3, S4 with some sense of proximity with one another. The way I see, this can be done in elasticsearch if I can attach boost to all Si in order of their proximity in meaning.

So that when I search the keyword S1, in the search results, S1 comes first, S2 comes second and S3 comes last on score.

Any help would be great.
Thanks, 
Utkarsh.

**Comment by utk4rsh** [comment]
Anyone with any pointers on how to achieve this?

**Comment by clintongormley** [comment]
Hi @utk4rsh 

While this is possible in Lucene, using payloads, it would require a bunch of custom code, custom token filters, custom queries etc.  It is unlikely that we will support this out of the box unless Lucene adds support for this first.

You could achieve something similar using different fields for different weights of synonyms - crude but simple.

**Comment by babadofar** [comment]
I would add the synonyms at query time, constructing a query using boost, function score or similar, where you can set weights for matching towards individual terms.
