### ISSUE TITLE
Disk-Based Shard Allocation not rebalancing shards when High Watermark Threshold is hit.

### ISSUE THREAD

**Issue by EagleDelta2** [elasticsearch/elasticsearch#9319]
When the disk space on nodes (usually between 1-3 nodes) in our 40 node cluster start to hit the cluster.routing.allocation.disk.watermark low and high thresholds (set to the defaults of 85% and 90%), disk-based shard allocation doesn't properly rebalance the shards until we execute the following two commands:

<pre><code>
curl -XPUT localhost:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.disk.threshold_enabled" : false
    }
}'
</code></pre>

followed by:

<pre><code>
curl -XPUT localhost:9200/_cluster/settings -d '{
    "transient" : {
         "cluster.routing.allocation.disk.threshold_enabled" : true
     }
}'
</code></pre>

Once we complete what is effectively turning disk-based shard allocation off, then on again, everything starts working as expected.

We are running Elasticsearch 1.3.4
I did not see any similar issues reported or fixed for any other version.

**Comment by dakrone** [comment]
@EagleDelta2 this was an issue with the service that updated the cluster disk information, it was defaulting to "off" even though the disk decider was changed to default to true.

I've looked at the code and this was fixed in 1.3.5+

**Comment by dakrone** [comment]
Here's the specific commit it was resolved in: 4683e3c41799da22f75368189ea812317e3f46fd

**Comment by dakrone** [comment]
Going to close this, feel free to re-open if desired.
