### ISSUE TITLE
Apply index-level field changes to all types automatically

### ISSUE THREAD

**Issue by ppf2** [elasticsearch/elasticsearch#9321]
Filing as a different use case to consider for this ticket https://github.com/elasticsearch/elasticsearch/issues/6732 on improving cluster/index settings.

It looks like if an index has multiple types, each with the same field defined, when enabling eager loading of global ordinals, changing just 1 type is sufficient given that global ordinals are across segments in the index (does not have to go and change all the types for the same field).  This can potentially create a confusion for the get mapping will only indicate that eager loading is enabled for the field in the type that is modified.  Wonder if it makes sense for put mapping to automatically apply the change to all types in the index so setting 1 type will cause it to apply the change to all types so that the get mapping will show this accordingly?  

https://gist.github.com/ppf2/fd6100670410809f523e

**Comment by clintongormley** [comment]
Hi @ppf2 

This is already being dealt with via #8870
