### ISSUE TITLE
JsonParseException[Unrecognized character escape ' ']

### ISSUE THREAD

**Issue by pankajagrawal16** [elasticsearch/elasticsearch#9324]
Hi,

I am trying to use elastic search to perform a free form search. Some thing like 

http://IP:PORT/index/_type/_search?size=1000&source={"query":{"query_string":{"query":"name:*test\ me*"}}}"

So i am expecting all the rows with name have "test me" in it.

But get:

error: "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[iGgtwDQhSvmnktuaUQexUA][customerws-customer][3]: SearchParseException[[customerws-customer][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"name:*test\ me*"}}}"]]]; nested: QueryParsingException[[customerws-customer] Failed to parse]; nested: JsonParseException[Unrecognized character escape ' ' (code 32) at [Source: [B@1b9e7028; line: 1, column: 48]]; }{[iGgtwDQhSvmnktuaUQexUA][customerws-customer][4]: SearchParseException[[customerws-customer][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"name:*test\ me*"}}}"]]]; nested: QueryParsingException[[customerws-customer] Failed to parse]; nested: JsonParseException[Unrecognized character escape ' ' (code 32) at [Source: [B@1b9e7028; line: 1, column: 48]]; }{[iGgtwDQhSvmnktuaUQexUA][customerws-customer][1]: SearchParseException[[customerws-customer][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"name:*test\ me*"}}}"]]]; nested: QueryParsingException[[customerws-customer] Failed to parse]; nested: JsonParseException[Unrecognized character escape ' ' (code 32) at [Source: [B@1b9e7028; line: 1, column: 48]]; }{[iGgtwDQhSvmnktuaUQexUA][customerws-customer][2]: SearchParseException[[customerws-customer][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"name:*test\ me*"}}}"]]]; nested: QueryParsingException[[customerws-customer] Failed to parse]; nested: JsonParseException[Unrecognized character escape ' ' (code 32) at [Source: [B@1b9e7028; line: 1, column: 48]]; }{[iGgtwDQhSvmnktuaUQexUA][customerws-customer][0]: SearchParseException[[customerws-customer][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"name:*test\ me*"}}}"]]]; nested: QueryParsingException[[customerws-customer] Failed to parse]; nested: JsonParseException[Unrecognized character escape ' ' (code 32) at [Source: [B@1b9e7028; line: 1, column: 48]]; }]"

**Comment by pankajagrawal16** [comment]
Working on 1.3.x version

**Comment by clintongormley** [comment]
Hi @pankajagrawal16 

I tried this on 1.3.0 as well, and it gives the same error message.

In order to get `test\ me` through the REST API, you need to escape the \ like this:

    curl -XGET "http://localhost:9200/_search?" -d'
    {
      "query": {
        "query_string": {
          "query": "name:test\\ me"
        }
      }
    }'

**Comment by pankajagrawal16** [comment]
I  tried the same but it gives results like its comparing for test\ OR me

**Comment by clintongormley** [comment]
@pankajagrawal16 that's correct.  Compare the output from these two validate-query requests:

    GET _validate/query?explain
    {
      "query": {
        "query_string": {
          "query": "name:test\\ me"
        }
      }
    }

returns: `"name:test name:me"`, while:

    GET _validate/query?explain
    {
      "query": {
        "query_string": {
          "query": "name:test me"
        }
      }
    }

returns: `"name:test _all:me"`

This is not a bug.  This is the way that querying an analyzed string field works.  The value is passed to the analyzer, which analyzes `test me` into the terms `test`, and `me`.

If you want to find `test` followed by `me`,  you need a phrase query:

    GET _search
    {
      "query": {
        "query_string": {
          "query": "name:\"test me\""
        }
      }
    }

**Comment by pankajagrawal16** [comment]
@clintongormley 

Agreed. But what I was looking for was:

If name is like : "i am trying to test me"

another name as : "I am trying tost me also"

another name as : "I am trying to st me also"

and if i query "st me", it should return me all three rows row. But the "name:\"test me\"" returns me only 1st and 3rd one. Not 2nd one.

Basically what I am looking for is a free form search, if query string is contained in name.

Hope you could help me with this. It would be of great help.
