### ISSUE TITLE
Closed shards left unassigned after opening index following ES upgrade

### ISSUE THREAD

**Issue by pickypg** [elasticsearch/elasticsearch#9325]
After upgrading to 1.4.2, there is an issue where previously closed indices that get reopened leave _all_ of their shards as `UNASSIGNED` even though `"cluster.routing.allocation.enable" : "all"` is set.

Manually rerouting all of the shards to the exact same node that they are already on works, so it is unclear why they start out `UNASSIGNED`.

I cannot reproduce it locally, so this may need to just be closed.

**Comment by clintongormley** [comment]
I can't replicate this either.  Any more details?

**Comment by pickypg** [comment]
@clintongormley None other than it is consistent for the people it's happening too.

I am enabling DEBUG logging for `action.admin.indices.open` to try to catch the failure, which should probably be logged as a warning:

https://github.com/elasticsearch/elasticsearch/blob/v1.4.2/src/main/java/org/elasticsearch/action/admin/indices/open/TransportOpenIndexAction.java#L98

**Comment by clintongormley** [comment]
@pickypg any more info or can this be closed?

**Comment by pickypg** [comment]
Nope, this can be closed. This could not be reproduced.
