### ISSUE TITLE
Field data frequency filter value

### ISSUE THREAD

**Issue by masaruh** [elasticsearch/elasticsearch#9327]
According to document, max/min values can be specified as absolute number or percentage.

And according to this https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/index/fielddata/plain/AbstractIndexOrdinalsFieldData.java#L118
, if a number is >= 1.0, it's considered as absolute number.

However, we often think 1.0 == 100%. Shouldn't it use ">" instead of ">="?
(By doing that, we won't be able to use min=1 as absolute number but it doesn't have any effect anyway)

In any case, adding document on this threshold would help.

**Comment by clintongormley** [comment]
Hi @masaruh 

Good point.  Would you be interested in sending a PR?

**Comment by masaruh** [comment]
Yes, I'll create a PR.
