### ISSUE TITLE
Node Count Mismatch in Cluster Status

### ISSUE THREAD

**Issue by jenapravat** [elasticsearch/elasticsearch#9332]
I created 4 nodes in a cluster: one master-data node,  two data nodes and one client node. When I run CURL command for cluster status, I see the following details:
Total no. of nodes = 4
Master Only = 0
Data Only = 2
Master Data = 1
Client = 0

I guess the client node count should have been 1

![es](https://cloud.githubusercontent.com/assets/4567797/5775982/72426646-9da7-11e4-8963-9e0b5424ff9a.png)

**Comment by clintongormley** [comment]
Hi @jenapravat 

A client node is specified as `node.client: true`,  rather than setting master and data to false.

That's why you're seeing the discrepancy.
