### ISSUE TITLE
Date histogram - Getting different results for buckets every-time the query is run

### ISSUE THREAD

**Issue by amruthkesav** [elasticsearch/elasticsearch#9333]
Hi I am using date histogram query in this fashion
        
    {
        "size": 0,
        "timeout": 120000,
        "aggs": {
            "filter_wrapper": {
                "aggs": {
                    "timestamp": {
                        "date_histogram": {
                            "field": "timestamp",
                            "interval": "60.0m",
                            "time_zone": "+05:30"
                        },
                        "aggs": {
                            "Net_Units": {
                                "sum": {
                                    "field": "net_units"
                                }
                            }
                        }
                    }
                },
                "filter": {
                    "and": [
                        {
                            "range": {
                                "timestamp": {
                                    "gte": 1421260200000,
                                    "lt": 1421346599000
                                }
                            }
                        },
                        {
                            "and": [
                                {},
                                {
                                    "terms": {
                                        "super_category": [
                                            "HomeDecor",
                                            "HomeFurnishing",
                                            "HomeImprovementTool",
                                            "HouseHold"
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                }
            }
        }
    }

One of the buckets is returning different result on every run

On the 1st run it gave this - 

    {
        key_as_string: 2015-01-15T11:30:00.000Z
        key: 1421321400000
        doc_count: 1505
        Net_Units: {
            value: 1418
        }
    }

If I run the query again and again I get this occasionally

    {
        key_as_string: 2015-01-15T11:30:00.000Z
        key: 1421321400000
        doc_count: 1423
        Net_Units: {
            value: 1375
        }
    }

Looks like the number of documents examined for the aggregation itself is mismatching.

This is the index status when the query was fired

    {
        index: {
            primary_size_in_bytes: 29353091854
            size_in_bytes: 59508084118
        }
        translog: {
            operations: 21542
        }
        docs: {
            num_docs: 52530831
            max_doc: 60617583
            deleted_docs: 8086752
        }
        merges: {
            current: 0
            current_docs: 0
            current_size_in_bytes: 0
            total: 1163319
            total_time_in_millis: 85319972
            total_docs: 782345554
            total_size_in_bytes: 605584878237
        }
        refresh: {
            total: 6501097
            total_time_in_millis: 173868772
        }
        flush: {
            total: 17782
            total_time_in_millis: 2120436
        }
        shards: {
            0: [
                {
                    routing: {
                        state: STARTED
                        primary: true
                        node: o9roxqp5Qs6ZITvepJCDTw
                        relocating_node: null
                        shard: 0
                        index: f_scp_oms
                    }
                    state: STARTED
                    index: {
                        size_in_bytes: 5599632911
                    }
                    translog: {
                        id: 1409740133203
                        operations: 1326
                    }
                    docs: {
                        num_docs: 10507345
                        max_doc: 11622029
                        deleted_docs: 1114684
                    }
                    merges: {
                        current: 0
                        current_docs: 0
                        current_size_in_bytes: 0
                        total: 234922
                        total_time_in_millis: 17348559
                        total_docs: 148914491
                        total_size_in_bytes: 117112040612
                    }
                    refresh: {
                        total: 3051652
                        total_time_in_millis: 76429882
                    }
                    flush: {
                        total: 7699
                        total_time_in_millis: 828736
                    }
                }
                {
                    routing: {
                        state: STARTED
                        primary: false
                        node: 4fBi7WiBSYei42iGyNVLyg
                        relocating_node: null
                        shard: 0
                        index: f_scp_oms
                    }
                    state: STARTED
                    index: {
                        size_in_bytes: 5707077556
                    }
                    translog: {
                        id: 1409740133198
                        operations: 4449
                    }
                    docs: {
                        num_docs: 10505767
                        max_doc: 11775261
                        deleted_docs: 1269494
                    }
                    merges: {
                        current: 0
                        current_docs: 0
                        current_size_in_bytes: 0
                        total: 112612
                        total_time_in_millis: 8886822
                        total_docs: 94811362
                        total_size_in_bytes: 71078185520
                    }
                    refresh: {
                        total: 456090
                        total_time_in_millis: 10018330
                    }
                    flush: {
                        total: 1356
                        total_time_in_millis: 141418
                    }
                }
            ]
            1: [
                {
                    routing: {
                        state: STARTED
                        primary: false
                        node: CH7tOBUCSzmIyiO_bQcq9Q
                        relocating_node: null
                        shard: 1
                        index: f_scp_oms
                    }
                    state: STARTED
                    index: {
                        size_in_bytes: 6165560358
                    }
                    translog: {
                        id: 1409740133254
                        operations: 4990
                    }
                    docs: {
                        num_docs: 10508000
                        max_doc: 12657246
                        deleted_docs: 2149246
                    }
                    merges: {
                        current: 0
                        current_docs: 0
                        current_size_in_bytes: 0
                        total: 6771
                        total_time_in_millis: 629412
                        total_docs: 5655838
                        total_size_in_bytes: 4363216808
                    }
                    refresh: {
                        total: 28497
                        total_time_in_millis: 680439
                    }
                    flush: {
                        total: 58
                        total_time_in_millis: 5569
                    }
                }
                {
                    routing: {
                        state: STARTED
                        primary: true
                        node: NtCQtOj6TbCZhOtRXc-TsQ
                        relocating_node: null
                        shard: 1
                        index: f_scp_oms
                    }
                    state: STARTED
                    index: {
                        size_in_bytes: 6165600927
                    }
                    translog: {
                        id: 1409740133255
                        operations: 526
                    }
                    docs: {
                        num_docs: 10508000
                        max_doc: 12656056
                        deleted_docs: 2148056
                    }
                    merges: {
                        current: 0
                        current_docs: 0
                        current_size_in_bytes: 0
                        total: 43654
                        total_time_in_millis: 3960933
                        total_docs: 37337683
                        total_size_in_bytes: 28101440785
                    }
                    refresh: {
                        total: 165483
                        total_time_in_millis: 4504477
                    }
                    flush: {
                        total: 601
                        total_time_in_millis: 80196
                    }
                }
            ]
            2: [
                {
                    routing: {
                        state: STARTED
                        primary: false
                        node: 8feFE_czSOSG6Volvrg17A
                        relocating_node: null
                        shard: 2
                        index: f_scp_oms
                    }
                    state: STARTED
                    index: {
                        size_in_bytes: 6520241401
                    }
                    translog: {
                        id: 1409740133014
                        operations: 101
                    }
                    docs: {
                        num_docs: 10505438
                        max_doc: 13473487
                        deleted_docs: 2968049
                    }
                    merges: {
                        current: 0
                        current_docs: 0
                        current_size_in_bytes: 0
                        total: 58741
                        total_time_in_millis: 4736398
                        total_docs: 43401787
                        total_size_in_bytes: 33349547432
                    }
                    refresh: {
                        total: 466161
                        total_time_in_millis: 12714445
                    }
                    flush: {
                        total: 1356
                        total_time_in_millis: 174188
                    }
                }
                {
                    routing: {
                        state: STARTED
                        primary: true
                        node: wiGuvgYFTQW_yN8aWqTMfw
                        relocating_node: null
                        shard: 2
                        index: f_scp_oms
                    }
                    state: STARTED
                    index: {
                        size_in_bytes: 5613227919
                    }
                    translog: {
                        id: 1409740133021
                        operations: 4565
                    }
                    docs: {
                        num_docs: 10506496
                        max_doc: 11643481
                        deleted_docs: 1136985
                    }
                    merges: {
                        current: 0
                        current_docs: 0
                        current_size_in_bytes: 0
                        total: 155413
                        total_time_in_millis: 10855943
                        total_docs: 98868285
                        total_size_in_bytes: 76311439708
                    }
                    refresh: {
                        total: 481274
                        total_time_in_millis: 15566507
                    }
                    flush: {
                        total: 1363
                        total_time_in_millis: 185328
                    }
                }
            ]
            3: [
                {
                    routing: {
                        state: STARTED
                        primary: false
                        node: 92-ZpTAeQpOSp5orwn2AQg
                        relocating_node: null
                        shard: 3
                        index: f_scp_oms
                    }
                    state: STARTED
                    index: {
                        size_in_bytes: 6109367546
                    }
                    translog: {
                        id: 1409740133323
                        operations: 1301
                    }
                    docs: {
                        num_docs: 10502892
                        max_doc: 12679433
                        deleted_docs: 2176541
                    }
                    merges: {
                        current: 0
                        current_docs: 0
                        current_size_in_bytes: 0
                        total: 133019
                        total_time_in_millis: 9724210
                        total_docs: 83235787
                        total_size_in_bytes: 65998616212
                    }
                    refresh: {
                        total: 470023
                        total_time_in_millis: 13486243
                    }
                    flush: {
                        total: 1360
                        total_time_in_millis: 198709
                    }
                }
                {
                    routing: {
                        state: STARTED
                        primary: true
                        node: GzGVrwdURXSGXAIhRvc7SA
                        relocating_node: null
                        shard: 3
                        index: f_scp_oms
                    }
                    state: STARTED
                    index: {
                        size_in_bytes: 6319438857
                    }
                    translog: {
                        id: 1409740133326
                        operations: 446
                    }
                    docs: {
                        num_docs: 10502892
                        max_doc: 13035768
                        deleted_docs: 2532876
                    }
                    merges: {
                        current: 0
                        current_docs: 0
                        current_size_in_bytes: 0
                        total: 154860
                        total_time_in_millis: 9967135
                        total_docs: 80535899
                        total_size_in_bytes: 66278258139
                    }
                    refresh: {
                        total: 480530
                        total_time_in_millis: 15116009
                    }
                    flush: {
                        total: 1363
                        total_time_in_millis: 187720
                    }
                }
            ]
            4: [
                {
                    routing: {
                        state: STARTED
                        primary: false
                        node: lDSfV78VR2SwKAYuAmVtaQ
                        relocating_node: null
                        shard: 4
                        index: f_scp_oms
                    }
                    state: STARTED
                    index: {
                        size_in_bytes: 5652745403
                    }
                    translog: {
                        id: 1409740133193
                        operations: 1524
                    }
                    docs: {
                        num_docs: 10506098
                        max_doc: 11643535
                        deleted_docs: 1137437
                    }
                    merges: {
                        current: 0
                        current_docs: 0
                        current_size_in_bytes: 0
                        total: 109249
                        total_time_in_millis: 8770793
                        total_docs: 91359115
                        total_size_in_bytes: 67361165648
                    }
                    refresh: {
                        total: 425467
                        total_time_in_millis: 9998433
                    }
                    flush: {
                        total: 1275
                        total_time_in_millis: 150416
                    }
                }
                {
                    routing: {
                        state: STARTED
                        primary: true
                        node: X5xzx3zlTlOe8GZ-7mrkqg
                        relocating_node: null
                        shard: 4
                        index: f_scp_oms
                    }
                    state: STARTED
                    index: {
                        size_in_bytes: 5655191240
                    }
                    translog: {
                        id: 1409740133195
                        operations: 2314
                    }
                    docs: {
                        num_docs: 10506098
                        max_doc: 11660249
                        deleted_docs: 1154151
                    }
                    merges: {
                        current: 0
                        current_docs: 0
                        current_size_in_bytes: 0
                        total: 154078
                        total_time_in_millis: 10439767
                        total_docs: 98225307
                        total_size_in_bytes: 75630967373
                    }
                    refresh: {
                        total: 475920
                        total_time_in_millis: 15354007
                    }
                    flush: {
                        total: 1351
                        total_time_in_millis: 168156
                    }
                }
            ]
        }
    }

I am using transport client to connect to Elastic search with cluster property set.
Is this a known issue?
Let me know if you need additional info about the problem.

**Comment by jpountz** [comment]
Refresh calls are not sync'ed across the cluster, so it could happen that visible documents to the _search API are not the same on two copies of the same shard. Could it explain your issue?

**Comment by clintongormley** [comment]
also, what version of Elasticsearch are you using?  and do you use delete-by-query?

do the results for that bucket bounce between two numbers, eg 10 -> 12 -> 10 -> 12 ?

are you still indexing into that index?

**Comment by amruthkesav** [comment]
Hi. Thanks for the quick response. 

But once the refresh has happened across the cluster, I should be seeing consistent data right?
But my state is this, the 1st time I get X as value, The next time I get Y and X again in the next run.

**Comment by amruthkesav** [comment]
@clintongormley we are using elastic search 1.2

**Comment by amruthkesav** [comment]
@clintongormley We don't use delete by query. And yes the results for the bucket is bouncing between two values.

**Comment by clintongormley** [comment]
@amruthkesav OK - it appears that, for some reason, your primary and replica shards are out of sync.  If you reduce the number of replicas to zero then back to 1, they should be in sync again.

Lots of changes have been made in recent releases to deal with issues like this, so I'd suggest upgrading Elasticsearch to take advantage of the improvements.

**Comment by amruthkesav** [comment]
Ok will try upgrading and the quick fix you have suggested. Thanks!

-----Original Message-----

**Comment by lmqwudi** [comment]
hi, amruthkesav , do you have already resolve this problem?I got the same problem and I can not find the solution.
