### ISSUE TITLE
ElasticSearch Thread Pools: UIMA Plugin for ElasticSearch

### ISSUE THREAD

**Issue by anandsrini85** [elasticsearch/elasticsearch#9343]
Text Analysis framework such as UIMA provide own thread pool mechanisms. If we are to create a ES plugin with UIMA for a custom analyzer, will it consume the thread pools of ES while indexing the documents?

**Comment by clintongormley** [comment]
Hi @anandsrini85 

Please ask questions like these on the mailing list.  thanks
