### ISSUE TITLE
Relocating shards runs forever

### ISSUE THREAD

**Issue by murugan-sundararaj** [elasticsearch/elasticsearch#9344]
We are using elasticsearch 1.3.0. Here is the cluster config
5 master only nodes
2 data only nodes
1 master and data node

The cluster state was green. The 2 "data only nodes" disk got full and cluster state went to red. I freed up the disk space and brought the cluster state to yellow. But there were two shards relocating and never completed for the whole day. And the marvel index creation (for the next day) started failing at this point and the cluster state went to red again. 

[2015-01-18 12:02:15,272][ERROR][marvel.agent.exporter    ] [es-data-node-2.com] create failure (index:[.marvel-2015.01.18] type: [shard_event]): UnavailableShardsException[[.marvel-2015.01.18][0] [1] shardIt, [0] active : Timeout waiting for [1m], request: org.elasticsearch.action.bulk.BulkShardRequest@98f690]

I was left with no option but to restart the cluster. After restart, the cluster state became green and any relocating shards completed fast.

Please let me know what could have triggered such problem and how to solve it in future.

**Comment by clintongormley** [comment]
Hi @murugan-sundararaj 

You would need to provide the logs and diagnostics related to the indices that weren't recovering.  The only log message you have here is from the Marvel client. It sheds no light on what was happening in the cluster.

Without more info we can't figure out what was going wrong.  That said, I'd advise upgrading, as the 1.4 branch has fixed a number of resiliency issues.

**Comment by clintongormley** [comment]
No more info. Closing

**Comment by dobariya** [comment]
am facing the same problem.
I keep on seeing   "relocating_shards": 2 infinitely 

{
    "cluster_name": "cluster1",
    "status": "green",
    "timed_out": false,
    "number_of_nodes": 3,
    "number_of_data_nodes": 3,
    "active_primary_shards": 2707,
    "active_shards": 5414,
    "relocating_shards": 2,
    "initializing_shards": 0,
    "unassigned_shards": 0,
    "number_of_pending_tasks": 341,
    "number_of_in_flight_fetch": 0
}

Initially i had 2 nodes which were running perfectly awesome but then i was facing OOM,I added one more node and the above status was looping over

**Comment by clintongormley** [comment]
@dobariya did you restart your nodes after the OOM?  

I suggest you open a new issue and provide logs, the output of the recovery API and any other supporting info that you can think of
