### ISSUE TITLE
Make RestController.getHandler(RestRequest) public

### ISSUE THREAD

**Issue by salyh** [elasticsearch/elasticsearch#9349]
RestController.getHandler(RestRequest) is currently a private method, i suggest to make it public because IMHO there is no entry point for a rest layer plugin to determine the request action (=RestHandler) and to populate the restrequest params.

**Comment by javanna** [comment]
Hi @salyh I am not sure I see why a plugin would need to to call this method. I think it should be elasticsearch core that calls it to resolve `RestHandler`s internally and call `handleRequest`, which is the method that plugins need to implement in custom rest handlers. Could you clarify this please?

**Comment by clintongormley** [comment]
No more info. Closing

**Comment by clintongormley** [comment]
Feel free to reopen if you're still interested.
