### ISSUE TITLE
_cat/pending_tasks returns "unknown" tasks

### ISSUE THREAD

**Issue by haardvark** [elasticsearch/elasticsearch#9354]
We experienced a buildup of pending tasks in the cluster this weekend after some nodes dropped.  Eventually, the cluster completely stopped processing tasks altogether.  When I went to check the tasks with _cat/pending_tasks, I saw some tasks that looked to be invalid:

7083   12m URGENT shard-started ([session-2014-12-27][24], node[RlRevMXMSOqc3qORtp3xew], [P], s[INITIALIZING]), reason [after recovery from gateway]
-12   12m unknown  
7092   12m URGENT shard-started ([session-2014-12-31][8], node[vEgbZbjXTVixtbpmh6Dh5A], [P], s[INITIALIZING]), reason [after recovery from gateway] 

When calling _cat/pending_tasks from a node that wasn't the current master, we would occasionally see get a 500 saying "can't deserialize task - no priority exists for [-12]".

It was suggested to us that this has been when different JVM versions are running in the same cluster, but this isn't the case in our deployment.  There is an ES support ticket open for this overall outage (6726) that may provide some more context.

**Comment by clintongormley** [comment]
Apparently the reason for this is as follows: when a task times out, the timeout action is placed onto the pending tasks queue, without an insertion order and source unknown.  This works fine on the master, but serialization to other nodes fails (which is not actually a problem, but isn't pretty).

We should:
* add an insertion order
* handle serialization to other nodes properly
