### ISSUE TITLE
Marvel Sense: GET request for non-existent document creates a new document

### ISSUE THREAD

**Issue by ajerome9** [elasticsearch/elasticsearch#9358]
When the following request is issued from the Marvel Sense interface, it creates a document with id=foo.
```
GET /index_1/type_1/foo
{
  
}
```

Here, /index_1/type_1/ does not have a document with id=foo, and the expectation was that the response would say found=false.

Looking at the network tab in Chrome, it appears that Sense is internally issuing a POST request to elasticsearch, resulting in the creation of a new document.
```
Request:
POST /index_1/type_1/foo HTTP/1.1
{
  
}
Response:
HTTP/1.1 201 Created
```

I noticed this when I had a typo in a request (something like /index_1/type_1/_search**h** instead of /index_1/type_1/_search), and Sense returned a response that said  {...,"created": true}.

With the request body removed, Sense is issuing GET requests, and the result is as expected. However, when the request has a body, a POST request is issued although the user indicated that it was going to be a GET request. (Not sure if this conversion is done to avoid any issues with having a GET request with a body)

**Comment by markwalkom** [comment]
Take a look at http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_empty_search.html#get_vs_post, that explains how ES handles the differences.

**Comment by dadoonet** [comment]
Thanks for reporting.

For this operation, you should not provide a body. SENSE use POST instead of GET as browsers don't support GET with body.
In a next version of Marvel, we will detect user errors and the operation you sent will be sent as a GET because this end point don't use any payload.

**Comment by ajerome9** [comment]
Thanks for your attention.

The concern was about the implicit conversion from GET to POST resulting in unintended consequences (a crud operation instead of an error). Glad to know that the next version of marvel will handle this appropriately.
