### ISSUE TITLE
not_analyzed String search Error

### ISSUE THREAD

**Issue by messias72** [elasticsearch/elasticsearch#9361]
Hi,

I have the following issue when I search on a not_analyzed String.

Mapping:
filename: {
type: "string",
index: "not_analyzed"
}

And there are data like: "filename": "CAPLETTERS_CAPLETTERS_NUMBER.letters.number.letters",

If you search for *NUMBER* in filename it works without any error, but if you search for CAPLETTERS_CAPLETTERS_NUMBER* you get empty results even if it exists. It wouldn't be found.

Even if you search like CAPLETTERS* the result es empty too.
Has anyone the same issue?

Detailed:

field: "filename"
value: "Stream_Flash_Video_129518.log"

query_string: filename:*lash*          -- get results
query_string: filename:*Flash*        -- get no results
query_string: filename:*flash*         -- get no results
query_string: filename:*129518*     -- get results

On an analyzed filed it works.
Best regards
Messias

**Comment by clintongormley** [comment]
Hi @messias72 

Please ask questions like this on the mailing list. This issues list is for bug reports and feature requests.

thanks

**Comment by messias72** [comment]
I Think this is a Bug if the search dosnt find \*Flash\* although it should be found.

**Comment by clintongormley** [comment]
It's not.  Start by reading this section: http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_exact_values_versus_full_text.html
