### ISSUE TITLE
Add `search_after` option to search api for pagination

### ISSUE THREAD

**Issue by martijnvg** [elasticsearch/elasticsearch#9374]
Adding `search_after` option to the search api will allow better deep pagination support for search request that don't use the scroll api.

The `search_after` option should be used to hold the last seen sort value for each search request being executed with the same query (just like updating the `from` option). Although in this case we don't keep open a consistent view of all the shards, like we do with scroll search, it is a good alternative for deep pagination for normal search requests that use `from` option. (actually the only one that doesn't cause jvm heap issues without maintaining open search contexts during subsequent scroll requests)

**Comment by clintongormley** [comment]
+1

**Comment by clintongormley** [comment]
Duplicate of #8192
