### ISSUE TITLE
Replace a master node and using same node.name breaks cluster

### ISSUE THREAD

**Issue by jlintz** [elasticsearch/elasticsearch#9378]
Recently on our logstash ES cluster we were running into memory issues on our master nodes so I went to upgrade the instance sizes on the nodes.  I replaced the 3 instance and re-used the same node.name as before.  After replacing them, the cluster health was green but logstash could not index to the cluster.  There were no errors, in the ES server logs on the master, client or data nodes.  Running logstash in debug showed it was receiving logs but then things seemed to be silently being dropped.  What finally got the cluster back into a working state was restarting ES on all the data nodes.  I assume there is some old IP being cached, but it was odd to not see any errors and the cluster health being reported as green.

Did I do something wrong here?  For the time being I've put a note that in the event of replacing a failed node to just re-use a different hostname.  

I'm running ES 1.3.4 on
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.12.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

**Comment by clintongormley** [comment]
Hi @jlintz 

This sounds like a problem with Logstash connecting to Elasticsearch, rather than with Elasticsearch itself.  There is no problem reusing node-names - people do it all the time.  Perhaps ask about this on the logstash list?
