### ISSUE TITLE
Scroll using REST API

### ISSUE THREAD

**Issue by kul** [elasticsearch/elasticsearch#9380]
ES 1.4.2
I am trying to closely follow http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-scroll.html but still not able to figure out what i am dong wrong here

```sh
#!/bin/sh

strip() {
  s=$1
  s="${s%\"}"
  s="${s#\"}"
  echo $s
}

curl -XPOST localhost:9200/myindex/mytype/1 -d '{"key": "value"}'
curl -XPOST localhost:9200/myindex/mytype/2 -d '{"key": "value"}'
curl -XPOST localhost:9200/myindex/mytype/3 -d '{"key": "value"}'

curl -XDELETE localhost:9200/_search/scroll/_all
echo
echo

scrollid=$(curl -XGET  'localhost:9200/myindex/mytype/_search?scroll=1m' -s -d '{
  "query" : {
    "match_all" : {}
  }
}' | jq '._scroll_id')
scrollid=$(strip $scrollid)

echo "Got scroll id $scrollid"
echo
echo

init=$(curl -XGET "localhost:9200/_search/scroll?scroll=1m&scroll_id=${scrollid}" -s)
echo $init
scrollid=$(echo $init | jq '._scroll_id')
scrollid=$(strip $scrollid)
echo "\n New scrollid id $scrollid"
echo
echo

next=$(curl -XGET "localhost:9200/_search/scroll?scroll=1m&scroll_id=${scrollid}" -s)
echo $next
```

Uses https://stedolan.github.io/jq/ and does the following
1. indexes 3 documents and deletes all existing scrolls
2. gets a scrollid for a match_all query
3. uses that id for search ( as per docs only gets count and zero hits)
4. uses the scroll id from above and again scrolls but this time also same result.

Both 3 and 4 steps generate same ids and same results.

**Comment by clintongormley** [comment]
Hi @kul 

First, the bit about the docs not being returned with the initial search request only applied when you set `search_type=scan`.  Second, you get back 10 docs at a time, and you only have 3 docs. 

So you are retrieving all three results in the first request, which you are throwing away after extracting the scroll_id...

**Comment by kul** [comment]
Ouch! can wait to get https://github.com/elasticsearch/elasticsearch/issues/9326. I guess the java api also has similar behaviour.
