### ISSUE TITLE
[FEATURE REQUEST] - Searchable shard version

### ISSUE THREAD

**Issue by nharraud** [elasticsearch/elasticsearch#9395]
I need to index/update a document in Elasticsearch and wait until it is searchable (refresh has been done). I know that there is a related issue: https://github.com/elasticsearch/elasticsearch/issues/1063

I am searching client side alternatives to forcing refresh and wait for 1 second (as it might take longer).

I have found a (quite ugly) solution which I describe here: http://stackoverflow.com/questions/28111805/elasticsearch-block-until-refresh-wait-for-doc-to-be-searchable-alternatives

To sum up briefly, it waits for the "searchable" document to reach the version returned by elasticsearch when indexing it. To do that it periodically performs GET and HEAD.

There could be a better solution if there was a way to know the current searchable shard's "version". A timestamp would be really nice. It would be updated each time a refresh is performed.

We could then:
- get the searchable shard version when performing indexing tasks.
- periodically GET the new searchable shard version and compare them.

The client libraries could group all requests for a shard version in one request per second which would be cleaner.

I suppose here that all documents in the transaction log are searchable after the refresh is done. I might be wrong and then it wouldn't work.

I don't know if this is feasible or even if it is a good idea as I am sure the issue https://github.com/elasticsearch/elasticsearch/issues/1063 will surely be resolved one day with a better solution. It is just a suggestion as many people seem to have this problem.

**Comment by clintongormley** [comment]
@nharraud given that each document has its own version, the only way to do what you're after is exactly as you describe: ie retrieve the version field from disk.  I think this is a non-starter.  

Better to adopt an eventually consistent approach to these issues, as I describe here: https://github.com/elasticsearch/elasticsearch/issues/1063#issuecomment-71497936
