### ISSUE TITLE
Allow all dynamic index settings to be set dynamically in _cluster/settings

### ISSUE THREAD

**Issue by pickypg** [elasticsearch/elasticsearch#9401]
Currently the only way to configure the slow logs settings for new indices is to modify any templates that exist or to modify your elasticsearch.yml and perform a restart.

It would be nice to be able to set something like

```json
PUT /_cluster/settings
{
  "transient" : {
    "index.search.slowlog.threshold.query.info" : "100ms"
  }
}
```

and then have it picked up by anything as though it were set in the YAML file. (This means that this is _not_ the same as applying it to `/_all/_settings`, which would modify any existing, open index)

This is probably very much related to the improvements planned by #6732

For anyone that needs this now, you _can_ workaround this issue by creating/updating a base catch-all index template:

```json
PUT /_template/base_slowlog_template
{
  "template" : "*",
  "order" : 0,
  "settings" : {
    "index.search.slowlog.threshold.query.info" : "100ms"
  }
}
```

**Comment by clintongormley** [comment]
Hi @pickypg 

This raises the question: if you set this cluster setting, does it affect indices that already exist but don't have this setting specified?  What is wrong with the template approach - to me it makes the scope of the setting clearer (ie it will only apply to new indices).

**Comment by clintongormley** [comment]
No more info. Closing

**Comment by pickypg** [comment]
Somehow I missed the original notification, but I think I agree that workaround above is probably clearer in how it operates.
