### ISSUE TITLE
elasticserach-zookeeper plugin issue with elasticsearch 1.0.0

### ISSUE THREAD

**Issue by shahkina** [elasticsearch/elasticsearch#9404]
I am having problem running elasticsearch zoo keeper plugin with elasticsearch1.0.0. I get the following error upon starting elasticsearch after setting the discovery to zookeeper in the elasticsearch.yml file.
[2015-01-24 22:32:10,564][INFO ][node                     ] [Node1] version[1.0.0], pid[8212], build[a46900e/2014-02-12T16:18:34Z]
[2015-01-24 22:32:10,565][INFO ][node                     ] [Node1] initializing ...
[2015-01-24 22:32:10,579][INFO ][plugins                  ] [Node1] loaded [zookeeper], sites [bigdesk, elasticsearch-kopf-master, head]
{1.0.0}: Initialization Failed ...
- ExecutionError[org.elasticsearch.common.util.concurrent.ExecutionError: org.elasticsearch.common.util.concurrent.ExecutionError: java.lang.NoClassDe
fFoundError: org/elasticsearch/ElasticSearchException]
        ExecutionError[org.elasticsearch.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/elasticsearch/ElasticSearchExcepti
on]
                ExecutionError[java.lang.NoClassDefFoundError: org/elasticsearch/ElasticSearchException]
                        NoClassDefFoundError[org/elasticsearch/ElasticSearchException]
                                ClassNotFoundException[org.elasticsearch.ElasticSearchException

Any help to resolved this is appreciated.

Thanks!

**Comment by dadoonet** [comment]
I think you should open this issue in the plugin repo.
That said, I'm afraid your plugin is too old as it's using ElasticSearchXXX class names which has been renamed in 1.0 by ElasticsearchXXX.

Closing.
