### ISSUE TITLE
Memory Leak Issue

### ISSUE THREAD

**Issue by CostyaRegev** [elasticsearch/elasticsearch#9407]
Hi , 

We have upgraded our Elasticsearch Clusters to 1.4.1 and after a short time we moved one of them to  Es Version 1.4.2.
When we upgraded  Es  Version to 1.4.1 we also upgraded our Java version to 8 only on one of the clusters (The one that was later upgraded to 1.4.2).
Today  we have 2 Different clusters that are running on 2 different Es versions and on 2 different Java Version.
The first has Es Version 1.4.2 and Java 8 , the Second has ES 1.4.1 and Java 7.
It seems that the first cluster needs a full cluster restart every 2 weeks , because the Jvm memory is constantly rising every day , whereas the second cluster is working just fine.

Could it be an issue of a Memory Leak that involves Java 8 ? 

Thanks,
Costya.

**Comment by clintongormley** [comment]
@CostyaRegev why not look at the Elasticsearch stats, or take a heap dump and see what is taking up all of the memory?  Or try changing either the Java version or the ES version to narrow it down.  It's impossible to be any more precise with the information you have provided.

**Comment by clintongormley** [comment]
No more info. Closing
