### ISSUE TITLE
Use _source to reindex data after a mapping update

### ISSUE THREAD

**Issue by tcucchietti** [elasticsearch/elasticsearch#9413]
I've not found issues related to this topic but sorry if it's the case.

If the _source is enabled in a mapping, a nice feature would be to be able to add a parameter (e.g. **reindex**) in PUT mapping request to trigger the data automatic reindexing, based on the _source value. A **wait_for_completion** flag could be added too.

Something like this would be handy :
    `PUT index/type/_mapping?reindex&wait_for_completion=true`

**Comment by clintongormley** [comment]
Hi @tcucchietti 

You can't change existing mappings, so we wouldn't be able to reindex into the same index, but the ability to reindex from source into a new index with new mappings is definitely on the roadmap (#492).  It is currently blocked by #6914, #6069, and #1242, but we are working on all of these.
