### ISSUE TITLE
Aggs: Add offset support to histograms

### ISSUE THREAD

**Issue by jpountz** [elasticsearch/elasticsearch#9417]
Having configurable offsets could be handy with histogram aggregations. Today when you create an histogram aggregation with an interval of X, you get buckets that have 0, X, 2*X, 3*X, ... as labels.

The point of this issue would be to also allow to configure an offset Y so that the generated buckets would be Y, X+Y, 2*X+Y, 3*X+Y, etc.

**Comment by cbuescher** [comment]
So, HistogramParser already has "pre_offset" and "post_offset", those should be used or new general "offset" parameter. Whats the meaning of the former, tried to find it in the reference here (http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html) but couldn't find them.

**Comment by jpountz** [comment]
Good point, for some reason I thought they only existed on the date histogram! Then I think we should try to remove these two options in favour of a single `offset` parameter. `pre_offset` is an offset that is applied before computing the buckets while `post_offset` is applied on the resulting buckets. But actually this should be a single `offset` parameter that you would add to the data before computing the bucket, and substract to the bucket afterwards.

**Comment by cbuescher** [comment]
@jpountz I played around with the pre_ and post_offset yesterday and I think we can implement the simplified offset functionality in terms of these two parameters, regardless if we dont expose Pre/Post offsets to the user (I think they are a bit confusing, maybe just the naming).

Just to make sure I understood the goal of this:
If I have values 1,2,3,4,5,6 and I do a histogram aggregation with interval 3, there would be bins
[0-2] count 2
[3-5] count 3
[6-8] count 1

With offset of +1 I wouldn't move the values but the boundaries of the bins so that we get
[1-3] count 3
[4-6] count 3

If you can check that my idea about how this should work is right I would start by writing a test for the above case and I think it can be solved with using the existing pre/post offsets.

**Comment by jpountz** [comment]
> If you can check that my idea about how this should work is right I would start by writing a test for the above case and I think it can be solved with using the existing pre/post offsets.

Your example looks good to me.

> regardless if we dont expose Pre/Post offsets to the user (I think they are a bit confusing, maybe just the naming).

I agree they are confusing, first because I always need to look back at the code to know how the post_offset is applied (is it substracted or added?), and also because it allows values to not be within bucket boundaries if you have different values for the pre and post offsets. So I'd really like to have a single `offset` parameter, at least in the REST API.

**Comment by cbuescher** [comment]
@jpountz In my current solution I added a new "offset" which basically moves the buckets like described above but internally I'm still using the pre/post_offsets in the HistogramParser. Should I also delete those for 2.0? There are certain things that you can do only by using pre/post_offest (like shifting the whole data together with the buckets using post_offset). If those two parameters should be deleted, should this also go on 1.x?
btw. I wrote new tests in HistogramTests which is already quiet huge. Is there any other good place for tests?

**Comment by jpountz** [comment]
Not sure exactly how to deal with bw compat for these settings. I would assume they are not used much so maybe we could just remove them in 2.0 and leave a note in the migration guide. However, I would not backport to 1.x. cc @clintongormley 

> There are certain things that you can do only by using pre/post_offest (like shifting the whole data together with the buckets using post_offset)

Indeed, but that's the kind of behaviour I would like to remove as it can be confusing since you can have bucket labels that don't match the data that they contain? If you want to apply an offset to your data, I think using scripts would be a more consistent approach?

HistogramTests is the right place for tests. If you feel like there are too many tests in it already, you can add a new eg. HistogramOffsetTests in the same package?

**Comment by clintongormley** [comment]
> Not sure exactly how to deal with bw compat for these settings. I would assume they are not used much so maybe we could just remove them in 2.0 and leave a note in the migration guide. However, I would not backport to 1.x. cc @clintongormley

I don't think these options were ever documented.  I'd definitely make this 2.0 only and not bother about 1.x

**Comment by cbuescher** [comment]
So I'll get rid of pre/post_offset and write some documentation for the new "offset" parameter, maybe using some simple example like the one above.

**Comment by jpountz** [comment]
+1
