### ISSUE TITLE
Unable to disable shard allocation prior to restart nodes when there is an index in memory

### ISSUE THREAD

**Issue by bplsilva** [elasticsearch/elasticsearch#9424]
Hello,
I have been writing a script that for properly restarting all the nodes of an ES cluster and I have noticed a few particular things in the process.

The process is quite simple, it is the same described in the official ES documentation
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/cluster-nodes-shutdown.html#_rolling_restart_of_nodes_full_cluster_restart
For each node in the cluster:
- disable shard allocation
- shut down the node
- restart the service via SSH
- enable back shard allocation once the node rejoins the cluster
- wait for the cluster to be OK before proceeding to the next node

However, one of the indices of the cluster is stored in memory.
When trying to disable shard allocation, we get an IllegalStateException ("Free bytes [X] cannot be less than 0 or greater than total bytes [Y]").

Such behaviour does not happens in a cluster when all the indices are stored on disk.

When using 3 replicas for every shard, shutting down a node with an index in memory should not be a problem, since even if the content is lost during the shutdown, it should be able to retrieve the information from the replicas when the node rejoins the cluster.

I do believe this is an issue from elasticsearch.

Thanks,
Bruno

**Comment by clintongormley** [comment]
Hi @bplsilva 

The memory store has been removed (see https://github.com/elasticsearch/elasticsearch/pull/8536), but we should probably still fix this in the interim.

**Comment by clintongormley** [comment]
I think we're not going to fix this one.  In memory indices have been removed in master, and there are more important issues to work on, so I'm going to close this one.
