### ISSUE TITLE
Dynamic "strict" not working if an undeclared field has null value

### ISSUE THREAD

**Issue by simaov** [elasticsearch/elasticsearch#9444]
Hello.
I have created type mapping with dynamic 'strict'. And I found that a StrictDynamicMappingException exception is not thrown when I try to index a document with an undeclared field and it's value NULL 

##### delete the index
<code>curl -XDELETE localhost:9200/test</code>

##### create the index with mapping and dynamic "strict"
<code>curl -XPOST localhost:9200/test -d '{
    "mappings" : {
        "type1" : {
            "dynamic": "strict",
            "properties" : {
                "field1" : { "type" : "string", "index" : "not_analyzed" }
            }
        }
    }
}'</code>

##### index a document with declared fields - ok
<code>curl -XPUT localhost:9200/test/type1/1 -d '
{ "field1": "test document"}
'</code>

##### index a document with undeclared field - ok,  we have error <code>StrictDynamicMappingException</code>

<code>curl -XPUT localhost:9200/test/type1/1 -d '
{ "field1": "test document",
"field2": "test document"},
'</code>

##### index a document with undeclared field (field2) and it's value NULL,  we have no error <code>StrictDynamicMappingException</code>
<code>curl -XPUT localhost:9200/test/type1/2 -d '
{ "field1": "test document",
"field2": null},
'</code>

##### there is a new (undeclared) field (field2) 
<code>curl -XGET localhost:9200/test/type1/_search -d '
{
    "query": {
        "match_all": {}
    }
}'</code>

**Comment by clintongormley** [comment]
Closed by #9445
