### ISSUE TITLE
Unable to update a _parent mapping for a type in an index once the index exists, even if no _parent mapping is present for the type.

### ISSUE THREAD

**Issue by ieb** [elasticsearch/elasticsearch#9448]
I have many indexes in an ES cluster (due to many tenants of the parent application). Each index contains many types that cannot be determined when the index is created. Once the index is created, its not possible to create further _parent mappings for types that were not known when the index was created. 

From reading other issues in this tracker, I could only find that the index had to be deleted whenever a new _parent mapping for a type was introduced. In this instance the dataset is too large and required to be online many 9's to make deleting all indexes and re-indexing from scratch on every update to the code base, unworkable.

Are there any workarounds ? Do I have to store each type in a separate index ? (even that will be immensely painful for frequent code updates and require the schema to be fixed well in advance.)

The code to set the _parent mapping for a type I am using is of the form.  
  index is the name of the index.
  type is the type
  parentType is the parentType for type.

    if (client.admin().indices().prepareExists(index).get().isExists()) {
       GetMappingsResponse mappings = client.admin().indices().prepareGetMappings(index).setTypes(type).get();
       ImmutableOpenMap<String, ImmutableOpenMap<String, MappingMetaData>> m = mappings.getMappings();
      if ( m.containsKey("1") && m.get("1").containsKey(type) && m.get("1").get(type).hasParentField() ) {
           System.err.println("Parent mapping for  "+index+"/"+type+" already exists");
      } else {
           PutMappingResponse create = client.admin().indices().preparePutMapping(index).setType(type).setSource("_parent", "type="+parentType).get();
    
       ^^^^^^ exception thrown here, note at this point there is no _parent field. The exception message appears misleading ?

           System.err.println("Add Mapping Ok "+create.isAcknowledged());
      }
    } else {
      System.err.println("Index does not exist");
      CreateIndexResponse create = client.admin().indices().prepareCreate(index).addMapping(type, "_parent","type="+parentType).get();
           System.err.println("Created Index with Mapping Ok "+create.isAcknowledged());
    }

Exception is:

    org.elasticsearch.index.mapper.MergeMappingException: Merge failed with failures {[The _parent field's type option can't be changed]}
	at    org.elasticsearch.cluster.metadata.MetaDataMappingService$4.execute(MetaDataMappingService.java:511)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:329)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

Apologies if this has been discussed/dealt with before. I searched all issues but could not find an answer.

Version being used is 1.4.0

**Comment by clintongormley** [comment]
Hi @ieb 

I'm not a Java person, but it is quite possible to add new types with new or existing parent types:

    DELETE test 
    
    PUT /test 
    {
      "mappings": {
        "child": {
          "_parent": {
            "type": "parent"
          }
        },
        "parent": {}
      }
    }
    
    PUT /test/_mapping/new_parent
    {
      "properties": {}
    }
    
    PUT /test/_mapping/new_child
    {
      "_parent": {
        "type": "new_parent"
      }
    }
    
    PUT /test/_mapping/other_child
    {
      "_parent": {
        "type": "parent"
      }
    }
        
    GET /_mapping

It looks like a bug in the way you're doing it.  I suggest asking in the mailing list for help with that.

**Comment by ieb** [comment]
@clintongormley 
I will ask on list, but your example PUT requests are not representative of the bug being reported. 
The failure happens when index and type exist but the type has no _parent field.
In your examples the index exists, but the types don't exist and are created when the mapping is made.

The Java call works if the type does not exist. (as per your PUT examples)

Obviously this "bug" could be "working as designed".... which would be a pity.

**Comment by dadoonet** [comment]
@ieb Indeed. I can reproduce your "issue" using REST. So it's not related to Java API.

```
DELETE test 
PUT test

PUT /test/_mapping/parent
{
  "properties": {}
}

PUT /test/_mapping/child
{
  "properties": {}
}

PUT /test/_mapping/child
{
  "_parent": {
    "type": "new_parent"
  }
}
```

Gives:

```
{
   "error": "MergeMappingException[Merge failed with failures {[The _parent field's type option can't be changed]}]",
   "status": 400
}
```

This is by design. See here: https://github.com/elasticsearch/elasticsearch/blob/1.4/src/main/java/org/elasticsearch/index/mapper/internal/ParentFieldMapper.java#L367-370

**Comment by dadoonet** [comment]
BTW if you have no document already you can remove the type.

```
DELETE test 
PUT test

PUT /test/_mapping/parent
{
  "properties": {}
}

PUT /test/_mapping/child
{
  "properties": {}
}

DELETE test/_mapping/child

PUT /test/_mapping/child
{
  "_parent": {
    "type": "new_parent"
  }
}
```

This is working.

**Comment by clintongormley** [comment]
@ieb ah ok - like I said I'm not a Java person.  As @dadoonet said, this is by design.  You can't change this mapping after the fact.  Even if one shard has no documents in that type, that shard has no way of knowing if the same is true on other nodes.

> BTW if you have no document already you can remove the type.

Note that this functionality is dangerous and will be removed (https://github.com/elasticsearch/elasticsearch/issues/8877)
