### ISSUE TITLE
High Network traffic on Nodes containing Primary Shards

### ISSUE THREAD

**Issue by satishmallik** [elasticsearch/elasticsearch#9452]
I was looking at network usage on Nodes on es cluster.
In my setup 
1) an index has 3 Primary and 2 Replicas. All 3 primaries are located on a single node.
2) It is default write consistency model which is Quorum.

During bulk indexing I am seeing on Marvel,

1) NETWORK TRANSPORT BYTES RECEIVED On Primary node is 118KB/s while on Nodes containing Replica nodes are 2KB/s. 
2) NETWORK TRANSPORT BYTES SENT is same as NETWORK TRANSPORT BYTES RECEIVED.

1) Ideally node containing Primary node should have high NETWORK TRANSPORT BYTES SENT as it needs to send packets to nodes containing replicas.
2) On NETWORK TRANSPORT BYTES RECEIVED, all three data nodes should have similar data as all of the data nodes is receiving same bulk packet.

Could you please explain it to me,

**Comment by clintongormley** [comment]
@satishmallik are you using a java node or transport client, or the REST interface, and which node(s) are you sending your bulk requests to?

For example, I set up two nodes (A and B) and created an index with 1 primary and 1 replica.  The primary is on A, the replica on B.

Then I use the REST interface to send bulk requests to node B.  B has to forward these requests to node A (via the transport layer).  A indexes the documents, then replicates the actions to node B.  A then returns the responses to B, which returns the responses over the REST layer to the client.

My tests showed the following:

    A:
        "rx_size": "12.2mb",
        "tx_size": "2.1mb",

    B:
        "rx_size": "2.1mb",
        "tx_size": "12.2mb",

This is consistent with what we'd expect. (Remember that only the transport layer is measured, not the HTTP layer.)

**Comment by satishmallik** [comment]
I have the following setup,
3 Query Nodes
3 master nodes
3 data nodes

All indexing requests come to query nodes which is also acting as ingestion node.

I am looking data in marvel and am seeing this weird behavior.
