### ISSUE TITLE
Failed to parse query .

### ISSUE THREAD

**Issue by SharmaManish** [elasticsearch/elasticsearch#9454]
I am passing a query in my request .

"a;lksdfj019083)(*)"   and it is getting failed although when i remove "*" it works .

Does lucene don't allow some of the characters while parsing, actually suprising thing is that when i reduced the query to "a)*" even then it is not working , although when i remove ')' and put only "a*" , it works also when i just put "a)" even then it also works what is the issue in my query , 

so the issue is only with the combination of characters ")*"

please help me out ?

**Comment by clintongormley** [comment]
Hi @SharmaManish 

The query string syntax is a mini-language, and it expects its input to be syntactically correct. See http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax

You probably want to use the `match` query instead or, if you want to support some special syntax, you could also look at the `simple_query_string` query.

**Comment by SharmaManish** [comment]
this is my query 

(((\"stew\" OR \"kabobs\" OR \"filet\" OR \"brisket\" OR \"roast\" OR \"steak\" OR \"beef\" OR \"burger\") AND asdfqwer3456\\\\!@#$%dfghtyui%\\\\^\\\\\u0026\\\\(*) AND -\"vegan\")

**Comment by SharmaManish** [comment]
asdfqwer3456\\\\!@#$%dfghtyui%\\\\^\\\\&\\\\(*)

**Comment by SharmaManish** [comment]
a;lksdfj019083\\\\)\\\\(*\\\\)

**Comment by clintongormley** [comment]
@SharmaManish please ask questions like this on the mailing list.  The github issues list is for bug reports and feaure requests.
