### ISSUE TITLE
Possible issue with copy_to name collisions

### ISSUE THREAD

**Issue by kidrecursive** [elasticsearch/elasticsearch#9465]
Hello I'm unsure if this is a bug or not but here is the behavior I was experiencing when using copy_to multiple times in a mapping, I've included part of the mapping below:

```json
"people": {
    "properties": {
        "name": {
            "type": "string",
            "index_analyzer": "autocomplete",
            "search_analyzer": "standard",
            "copy_to": "exact_name"
        },
        "exact_name": {
            "type": "string",
            "index": "not_analyzed"
        }
    }
},
"places": {
    "properties": {
        "name": {
            "type": "string",
            "index_analyzer": "autocomplete",
            "search_analyzer": "standard",
            "copy_to": "exact_name"
        },
        "exact_name": {
            "type": "string",
            "index": "not_analyzed"
        }
    }
}
```
My assumption was that this would be fine since the copies are in subdocs, however the places.exact_name wasn't searchable.  When I changed the copy to value to a different name under places then everything worked as expected.

ES version 1.1.1

**Comment by clintongormley** [comment]
Hi @kidrecursive 

Why don't you think it works?  Seems to work for me (tested on 1.1.1 and 1.4.2):

    DELETE test
    
    PUT test 
    {
      "mappings": {
        "people": {
          "properties": {
            "name": {
              "type": "string",
              "copy_to": "exact_name"
            },
            "exact_name": {
              "type": "string",
              "index": "not_analyzed"
            }
          }
        },
        "places": {
          "properties": {
            "name": {
              "type": "string",
              "copy_to": "exact_name"
            },
            "exact_name": {
              "type": "string",
              "index": "not_analyzed"
            }
          }
        }
      }
    }

    PUT test/people/1
    {
      "name": "John Smith"
    }
    
    PUT test/places/2
    {
      "name": "New York"
    }
    
    GET /test/_search
    {
      "query": {
        "match": {
          "exact_name": "John Smith"
        }
      }
    }
    
    GET /test/_search
    {
      "query": {
        "match": {
          "exact_name": "New York"
        }
      }
    }
    
    GET /test/_search 
    {
      "query": {
        "match": {
          "places.exact_name": "New York"
        }
      }
    }

**Comment by kidrecursive** [comment]
My apologies, I wasn't specific enough with my initial description, I'm making a copy in order to use a filter, and that query is what was not behaving,  like so:

```json
PUT copy_to_test 
{
  "mappings": {
    "things": {
      "properties": {
        "people": {
          "properties": {
            "name": {
              "type": "string",
              "copy_to": "exact_name"
            },
            "exact_name": {
              "type": "string",
              "index": "not_analyzed"
            }
          }
        },
        "places": {
          "properties": {
            "name": {
              "type": "string",
              "copy_to": "exact_name"
            },
            "exact_name": {
              "type": "string",
              "index": "not_analyzed"
            }
          }
        }
      }
    }
  }
}

PUT copy_to_test/things/1
{
  "people": {
    "name": "John Smith"
  },
  "places": {
    "name": "New York"
  }
}

GET copy_to_test/_search
{
  "query": {
    "filtered": {
      "filter": {
        "term": {
          "people.exact_name": "John Smith"
        }
      }
    }
  }
}

GET copy_to_test/_search
{
  "query": {
    "filtered": {
      "filter": {
        "term": {
          "places.exact_name": "New York"
        }
      }
    }
  }
}

PUT copy_to_test_2 
{
  "mappings": {
    "things": {
      "properties": {
        "people": {
          "properties": {
            "name": {
              "type": "string",
              "copy_to": "exact_name"
            },
            "exact_name": {
              "type": "string",
              "index": "not_analyzed"
            }
          }
        },
        "places": {
          "properties": {
            "name": {
              "type": "string",
              "copy_to": "exact_name_2"
            },
            "exact_name_2": {
              "type": "string",
              "index": "not_analyzed"
            }
          }
        }
      }
    }
  }
}

PUT copy_to_test_2/things/1
{
  "people": {
    "name": "John Smith"
  },
  "places": {
    "name": "New York"
  }
}

GET copy_to_test_2/_search
{
  "query": {
    "filtered": {
      "filter": {
        "term": {
          "people.exact_name": "John Smith"
        }
      }
    }
  }
}

GET copy_to_test_2/_search
{
  "query": {
    "filtered": {
      "filter": {
        "term": {
          "places.exact_name_2": "New York"
        }
      }
    }
  }
}
```

**Comment by clintongormley** [comment]
ah ok :)

You're using the short form of the field name, so it tries to find `exact_name` and it just uses the first one it find, which happens to be `person.exact_name`.

Change your mapping to use the full path to the field, ie:

    PUT copy_to_test 
    {
      "mappings": {
        "things": {
          "properties": {
            "people": {
              "properties": {
                "name": {
                  "type": "string",
                  "copy_to": "people.exact_name"
                },
                "exact_name": {
                  "type": "string",
                  "index": "not_analyzed"
                }
              }
            },
            "places": {
              "properties": {
                "name": {
                  "type": "string",
                  "copy_to": "places.exact_name"
                },
                "exact_name": {
                  "type": "string",
                  "index": "not_analyzed"
                }
              }
            }
          }
        }
      }
    }

In fact, the short form of field names is going away. See #8872

**Comment by kidrecursive** [comment]
Thanks!
