### ISSUE TITLE
Problem with context suggester when a document has more than 256 categories

### ISSUE THREAD

**Issue by goldmar** [elasticsearch/elasticsearch#9466]
I use the context suggester for, well, suggestions, and I have more than 256 different categories.

When I try to index a document with 257 categories, I get the following error:

```
{
   "error":"IllegalArgumentException[TokenStream expanded to 257 finite strings. Only <= 256 finite strings are supported]",
   "status":500
}
```

I have uploaded a simple curl example here: https://gist.github.com/goldmar/2c3f64575df420a5413a

**Comment by clintongormley** [comment]
Hi @goldmar 

Yes, this is a hardcoded limit.  

@areek will this still apply in the new suggester?

**Comment by areek** [comment]
This limit will not apply to the new suggester. closing in favour of https://github.com/elasticsearch/elasticsearch/issues/8909

**Comment by goldmar** [comment]
Hi @clintongormley @areek 

Thanks for the response! Do you have an ETA for the new suggester?

Also, please consider adjusting the documentation of the Context Suggester meanwhile. In my opinion this limitation should be mentioned in a big red warning box. Lots of use cases involve more than 256 categories and it's very unfortunate to discover that a solution does not scale after having spent a lot of time implementing it.

**Comment by trevorah** [comment]
Hi @areek, it looks like the limit is still there in the new suggester: https://github.com/elastic/elasticsearch/commit/4a1a03428d7884c185b05c364c6f220237a9567e#diff-75e5e5d55213c0dd7f686432961c1cf8R71

Is the limit still going to be there once elasticsearch v5 is out of alpha?

**Comment by clintongormley** [comment]
@trevorah that's the old completion suggester which is still there for bwc.

**Comment by trevorah** [comment]
@clintongormley ah cool. I'll try the v5 alpha.
