### ISSUE TITLE
In Regex Search  can't put a Unicode char by Suffix

### ISSUE THREAD

**Issue by jaja85926** [elasticsearch/elasticsearch#9493]
This is my Test  on query_string query . 

i'm try use like this Regex  :  "query": "/.*[\\u00A9]Crystallin.*/"  Yeah it can find a some record . 

but my record need a right rule like  "query": "/.*[\\u00A9]Crystallin[\\u00A9].*/". 

when  i use this rule . it always return empty record . i think unicode can't put a Suffix . 

because this   "query": "/.*Crystallin[\\u00A9].*/"  will return empty record too ...

**Comment by clintongormley** [comment]
Hi @jaja85926 

I'm afraid I don't understand your question at all, but it sounds like you are having a problem understanding the regex syntax.  I suggest you try the user forum instead.

I think that perhaps the bit you're not understanding is that your regex has to match the whole term, from beginning to end.

**Comment by jaja85926** [comment]
oh. my question is . if i use this regex pattern  -> .[\u00A9]Crystallin.  it's can get  record when i query , but if i use this regex pattern -> .Crystallin[\u00A9].  , it's will return empty record . And  i'm very sure i have  a record will be hit . Example  i have a  two record .   ABC©Crystallin©ABC  ;  CDE©Crystallin©CDE . when i use first pattern it's will return 2 hits . but if i use second pattern , it's will return empty .  if i put the two record and use Regex Tool to authentication both pattern , All record can be  match with two pattern .

**Comment by clintongormley** [comment]
Hi @jaja85926 

As I said, you should ask about this in the forum, not on this list.  

I suggest that you provide a complete example, including how you create the index, how you index the document, and how you query.  The information you have provided is not sufficient to answer your question.
