### ISSUE TITLE
Seeing many open Elasticsearch connections even after using singleton pattern

### ISSUE THREAD

**Issue by prachicsa** [elasticsearch/elasticsearch#9499]
Hi,

I just the following method for connection creation in ES:
```
    public static Client getClient() {
        if (client == null) {
            synchronized (mutex) {
                settings = ImmutableSettings.settingsBuilder().put(CONFIG_CLUSTER_NAME, CLUSTER_NAME).build();
                client = new TransportClient(settings);
                for (String address : transportAddress ) {
                    ((TransportClient) client).addTransportAddress(new InetSocketTransportAddress(address, transportPort));
                }
                logger.info("Elastic search client initialized");
            }
        }
        logger.info("Returning the existing client");
        return client;
    }
```
But for this application, when I ran `netstat` on that host, I saw many open connections:

    tcp        0      0 ::ffff:*.*.*.*:59380  ::ffff:*.*.*.*:9300   ESTABLISHED 6552/java           
    tcp        0      0 ::ffff:*.*.*.*:48829  ::ffff:*.*.*.*:9300   ESTABLISHED 6552/java           
    tcp        0      0 ::ffff:*.*.*.*:42944  ::ffff:*.*.*.*:9300   TIME_WAIT   -                   
    tcp        0      0 ::ffff:*.*.*.*:42838  ::ffff:*.*.*.*:9300   ESTABLISHED 6552/java           
    tcp        0      0 ::ffff:*.*.*.*:8080   ::ffff:*.*.*.*:57649  ESTABLISHED 6552/java           
    tcp        0      0 ::ffff:*.*.*.*:55154      ::ffff:*.*.*.*:3306       ESTABLISHED 6552/java           
    tcp        0      1 ::ffff:*.*.*.*:36889  ::ffff:*.*.*.*:9300   FIN_WAIT1   -                   
    tcp        0      0 ::ffff:*.*.*.*:42829  ::ffff:*.*.*.*:9300   ESTABLISHED 6552/java           
    tcp        0      0 ::ffff:*.*.*.*:37169  ::ffff:*.*.*.*:9300   TIME_WAIT   -                   
    tcp        0      0 ::ffff:*.*.*.*:59390  ::ffff:*.*.*.*:9300   ESTABLISHED 6552/java           
    tcp        0      0 ::ffff:*.*.*.*:58283  ::ffff:*.*.*.*:9300   TIME_WAIT   -                   
    tcp        0      0 ::ffff:*.*.*.*:59383  ::ffff:*.*.*.*:9300   ESTABLISHED 6552/java           
    tcp        0      0 ::ffff:*.*.*.*:55855  ::ffff:*.*.*.*:9300   TIME_WAIT   -                   
    tcp        0      0 ::ffff:*.*.*.*:48823  ::ffff:*.*.*.*:9300   ESTABLISHED 6552/java           
    tcp        0      1 ::ffff:*.*.*.*:36884  ::ffff:*.*.*.*:9300   FIN_WAIT1   -              

I have removed the ip with *.*.*.*. But there are many more open connections than this.

Questions:
-> How do I manually go and close all these connections?
-> Is there any mistake in connection creation?
-> Sometimes, even if ES is running and connection is also created, it doesn't get any response. After restarting the application, it returns result for the same query. How should I analyze this?

**Comment by kimchy** [comment]
the transport client opens multiple connections to each node it ends up connecting to, not just one. This is done in order to improve the throughput of the execution. The number of connections can be configured (and actually there are several types of them), but I recommend not changing that unless you really have a problem for some reason.

regarding not getting a response, which version are you using?

**Comment by prachicsa** [comment]
We are using version 1.3.1

**Comment by petchema** [comment]
@prachicsa: your use of mutexes is flawed, several threads can see client == null before they block on the mutex

**Comment by clintongormley** [comment]
@prachicsa this sounds like user error - probably best taken up on the user mailing list.  If you find a bug, please feel free to reopen this ticket.
