### ISSUE TITLE
Marvel nodes panel "msearch" and dashboards list "mget" are not working

### ISSUE THREAD

**Issue by abualy** [elasticsearch/elasticsearch#9507]
Hello!
I have installed Marvel in trial mode for a testing cluster of 3 clusters, i can't get the nodes panel to show anything, neither the dashboards list:

![marvel_bug](https://cloud.githubusercontent.com/assets/2552664/5977624/642785ec-a891-11e4-9e3b-0233c752ea2d.jpg)

when i debugged the requests that are not working i found that these requests return an empty response: "Failed to load resource: net::ERR_EMPTY_RESPONSE"
i tested the same request with its payLoad on sense extension and it worked, i tested on different browsers, still the same issue

![marvel_bug2](https://cloud.githubusercontent.com/assets/2552664/5977816/f6b2a4fe-a892-11e4-8224-e07e167d91b1.jpg)

Thank you

**Comment by bleskes** [comment]
That's very peculiar. Anything in the elasticsearch logs?

**Comment by abualy** [comment]
no nothing, i changed the logs level to debug, and nothing there, i digged more and it appears that the nginx redirection that's causing the problem:
i have a redirection from ":9200/" to ":80/es/"  and it when i tested to omit the redirection it works.

**Comment by abualy** [comment]
btw, i have been always working with this  redirection when it comes to elastisearch as i am restricted to have all communication through the 80 port, all the plugins i've worked with had no problem: head, bigdesk,... , i don't know why i faced such a problem with Marvel

**Comment by bleskes** [comment]
@abualy do you also use :80/es as a based for the marvel UI? I also noticed you closed the issue, but is it really solved for you? It should work with the redirection. I think you might need to change your kibana config file under plugin/marvel/_site/kibana/config.js and fix the URL for ES calls to include the sub path.
