### ISSUE TITLE
init script from the debian package version 1.4.2 does not work on ubuntu 14-04. 

### ISSUE THREAD

**Issue by brainbuz** [elasticsearch/elasticsearch#9510]
On a clean install of Ubuntu Server (64) I downloaded and installed the ES .deb 1.4.2.

Running the init script did not successfully start an instance and I found no evidence in either syslog or the elasticsearch log documenting why it failed. But I was able to start ES directly from the command line. Replacing the blocks in the init script for setting JAVA and JAVA_HOME with explicit assignments  resolved the problem.

**Comment by electrical** [comment]
That's weird because non of our tests had any issues so far.

**Comment by brainbuz** [comment]
If I get some time this weekend I'll install some fresh images in my home
lab and some cloud providers to confirm the same issue happens and maybe
take a closer look at the two blocks I removed. If I see a fix, are those
init scripts part of a public repo?

**Comment by electrical** [comment]
The init scripts are in the src/deb and src/rpm repo's.

Cheers.

**Comment by brainbuz** [comment]
I installed the package on two fresh installs at two different clouds and failed to reproduce the issue.  Thanks for responding.
