### ISSUE TITLE
Sum aggregation under nested terms aggregation not accurate

### ISSUE THREAD

**Issue by kul** [elasticsearch/elasticsearch#9516]
The doc mentions that doc count under sum aggregations are approximate. But even sum under a term aggregation is also not accurate. Here is an example using python client ( creates ~500,000 records).

```python
import json
from elasticsearch import Elasticsearch

es = Elasticsearch()

for i in range(1000):
    for j in range(i):
        es.index(index="test", doc_type="test", body= {'type': 'type'+`i`, 'value': 1})

res = es.search(index="test", doc_type="test", body=
        {"aggs": { "type": {
            "terms": {"field": "type", "size": 5},
            "aggs": {"value": {"sum": {"field": "value"}}}}}})

print json.dumps(res['aggregations'], indent=4)
```

Does this implies that any other aggregation under a term aggregation would be approximate?

**Comment by kul** [comment]
Just noticed `As described above, the document counts (and the results of any sub aggregations) in the terms aggregation are not always accurate.`. Is there a way to trade accuracy for query time?

**Comment by kul** [comment]
I think most of the people dont realize that anything under term agg will not be accurate. Although an outrageous suggestion but would it make sense to somehow make usage explicit. e.g. renaming `terms` to `terms_approx`?

**Comment by dadoonet** [comment]
Well. I guess that when you hit only one shard, it's accurate. For example, if you use routing.

My 2 cents.

**Comment by kul** [comment]
Yea, i read the reason for it, makes sense but its such a bummer. setting `size: 0` seems to be the only tradeoff for accuracy I can find. Although this is a odd case with es query and google search shows it has tripped many. :goberserk:

**Comment by kul** [comment]
@dadoonet ah yes! routing is something i need to re look at. Thanks!

**Comment by kul** [comment]
@dadoonet 

```python
import json
from elasticsearch import Elasticsearch

es = Elasticsearch()

for i in range(1000):
    for j in range(i):
        es.index(index="test", doc_type="test", body= {'type': 'type'+`i`,
            'value': 1}, routing='type'+`i`)

res = es.search(index="test", doc_type="test", body=
        {"aggs": { "type": {
            "terms": {"field": "type", "size": 5},
            "aggs": {"value": {"sum": {"field": "value"}}}}}})

print("Got %d Hits:" % res['hits']['total'])
print json.dumps(res['aggregations'], indent=4)
```

Based on the routing tip, accurate results! but i still see `"doc_count_error_upper_bound": 4385`.
Should'nt this value be zero?
