### ISSUE TITLE
automatic string splitting in scripted aggregation is wrong

### ISSUE THREAD

**Issue by ltworf** [elasticsearch/elasticsearch#9530]
Hello,

I've been using scripted aggregations with the newer version of elasticsearch and I've encountered a problem.

Basically strings are automatically split before they are passed to the scripting language, and this is causing my aggregation to act a bit weird.

```
curl -XPUT localhost:9200/test/test/1 -d '
 { "title": "test document", "genre": "science fiction/horror"}
 '


curl -XPOST  localhost:9200/test/_search -d '
{
  "query": {
    "match_all": {}
  },
  "aggs": {
    "genre": {
      "scripted_metric": {
        "init_script": "_agg.genre = [:]",
        "map_script": "for (i=0; i<doc[\"genre\"].size(); i++) _agg.genre.put(doc[\"genre\"][i],_agg.genre.get (doc[\"genre\"][i],0)+1)",
        "reduce_script": "retval = [:];for (i in 0.._aggs.genre.size()) {for ( e in _aggs.genre[i] ) {retval.put(e.key,retval.get(e.key,0)+e.value)}};return retval;"
      }
    }
  }
}
'
```

The aggregation is meant to count how many documents per genre there are, and a document can have multiple genres, all in the same string, separated by a `/` symbol. However the automatic split will also split on ` ` and it will be like there are three genres when there are in fact only two.

I believe it would be best if the string was left untouched and just passed as it is, and the script can split it, if it is necessary, and on the symbols that are supposed to be separators in the specific case.

Best

**Comment by jpountz** [comment]
Aggregations do not automatically split on whitespaces, but indexing does. It seems to me like the only thing that you need to do is to map your `genre` field as `not_analyzed`?

**Comment by ltworf** [comment]
Okay sorry, I thought that the aggregation would work on the source document as it is returned, not on the internal representation

**Comment by jpountz** [comment]
No worries, I understand how it can sometimes be confusing...
