### ISSUE TITLE
ElasticsearchParseException[Failed to derive xcontent from (offset=0, length=0): []] once snapshotting into a full filesystem

### ISSUE THREAD

**Issue by dakrone** [elasticsearch/elasticsearch#9534]
When performing a snapshot into an FS repository that doesn't have enough space, it's possible to run out of space while taking the snapshot, predictably the snapshot process fails, however, in the case that the "finalizing" file cannot be written, Elasticsearch is unable to list or delete the snapshot.

Trying to get the status of _all (or the snapshot that failed) snapshots returns

```
curl -XGET '0:9200/_snapshot/repobkps/_all?pretty'
{
  "error" : "RemoteTransportException[[elasticsearch][inet[/127.0.0.1:9300]][cluster:admin/snapshot/get]]; nested: ElasticsearchParseException[Failed to derive xcontent from (offset=0, length=0): []]; ",
  "status" : 400
} 
```

Listing all of the snapshots shows no snaps are present:

```
curl -XGET '0:9200/_snapshot/repobkps/_status?pretty'
{
  "snapshots" : [ ]
} 
```

The snapshot cannot be deleted either:

```
curl -XDELETE '0:9200/_snapshot/repobkps/snp1'
{"error":"RemoteTransportException[[elasticsearch][inet[/127.0.0.1:9300]][cluster:admin/snapshot/delete]]; nested: ElasticsearchParseException[Failed to derive xcontent from (offset=0, length=0): []]; ","status":400} 
```

**Comment by imotov** [comment]
Changes in #8782 make this failure with running out of disk space no longer possible. But assuming that the snapshot file can still get corrupted or truncated, we need to make it possible to delete such snapshot.
