### ISSUE TITLE
ElasticSearch Aggregating Against FIRST/Max Nested Document

### ISSUE THREAD

**Issue by MartyIce** [elasticsearch/elasticsearch#9536]
I'm using Elastic Search trying to get an aggregation of "last login country" for a set of users, and am not sure whether ES supports this type of aggregation? Here's a rough picture of the mapping:

    User
      UserId
        Sessions (array)
            Session1 - CreateDate, Country
            Session2 - CreateDate, Country

What I'm wanting to do is pass in a date range, and get an output of the logins by country, with ONLY a single session per user. In other words, if the user logged in 3 times during the date range, only 1 of those sessions would count towards the overall count.

The output would look something like the following:

    Country Aggregations
        USA, Count: 10
        Japan, Count: 15
        Spain, Count: 23

I've been looking over nested aggregations, but I'm not sure they can give me what I need. The main problem I'm having is that if a User has multiple Sessions during the date range, each of those sessions contribute to the overall country count. Is there a way to filter this inner list of nested documents down so that only 1 will contribute to the aggregation per User?

**Comment by clintongormley** [comment]
Hi @MartyIce 

No, you can't do this in a single step.  That said, if you are storing sessions as nested documents (which means you are reindexing the document for every session) then you can just store the last country at the top level in the doc, and aggregate on that.

**Comment by anuragpundir** [comment]
Hi martylce , i am also having the same type of problem , have you solved this kind of problem in elastic search where we need to do nested aggregation?

**Comment by anuragpundir** [comment]
hi @clintongormley 
if you could just help me to solve this kind of issue where we can use aggregation on multiple fields to bring the common tags and its count that occurs in different fields on each document.

**Comment by clintongormley** [comment]
@anuragpundir the place to ask questions like these is in the forums: https://discuss.elastic.co/
