### ISSUE TITLE
Enabling TTL Automatically from logstash configuration

### ISSUE THREAD

**Issue by viveksofty** [elasticsearch/elasticsearch#9543]
Hi ., Currently ttl in elasticsearch is automatically disabled ., But If we want to enable it ., We can do it by passing rest api and we able to mapping updation as ttl enabled .,

But If i'm having morethan 50 indices and each indices have more than 100 types as a case 

How can I do it this ttl enabling automatically from logstash

please fix this issue :)

**Comment by clintongormley** [comment]
Hi @viveksofty 

You can already do this automatically with index templates and the `_default_` mapping.  Please ask questions like these on the mailing list instead.

thanks
