### ISSUE TITLE
Filter aggregation vs Term aggregation with filtering values

### ISSUE THREAD

**Issue by aaneja** [elasticsearch/elasticsearch#9552]
I'm building aggregations on a field which has bot a  '.analyzed'  and a '.raw' version.
The analyzer used is the standard analyzer

If I want to build filtered term buckets, what would be more performant
1. Using an 'include' specified on the terms aggregation on the '.raw' field (http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values)
2. Using a filter aggregation on the '.analyzed' version, then building the terms aggregation on the '.raw' field.

How will the performance change
1. If the field is really large
2. If the field is small (< 300 characters)

I know that the semantics of querying on a analyzed field differs from a regex match; but if my users would be okay either way - what is the query which will have better perf on the cluster ?

**Comment by clintongormley** [comment]
Hi @aaneja 

Please ask questions like these on the mailing list.  This issues list is for bug reports and feature requests.

thanks
