### ISSUE TITLE
elasticsearch  many threads agg search, have a bug ,cause error :None of the configured nodes were available

### ISSUE THREAD

**Issue by xwmaiflytek** [elasticsearch/elasticsearch#9554]
hi,elasticserch

in my project ,we found elasticsearch a bug about agg search, 
when there were twice or more threads  use java api aggregation to invoke es at the sametime,
elasticsearch sometime cause error:None of the configured nodes were available,
but one thread never apprear.  we test many times,come to the conclusion .

1.our index data just Fifty million
2.and agg search  just like : select appid,count(id) from msprouterecord group by appid, 
3.our server is 32*core 64g memory
4.ulimit -v -m  -l unlimited -n 204000
5.elasticsearch 1.3.7

this bug no matter with server  configuration and os environment ，always apprear.

please help us resolve quickly,  thank you very much!

**Comment by wxshi** [comment]
yes yes !!

**Comment by alexksikes** [comment]
Hello, your issue might be better answered in the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/elasticsearch). Please make sure you [read this](http://www.elasticsearch.org/help) beforehand. Hope this helps.

**Comment by clintongormley** [comment]
Hi @xwmaiflytek 

As @alexksikes said, questions like these should be asked in the mailing. The github issues list is for bug reports and feature requests.
