### ISSUE TITLE
Specifying analyzer at insert time

### ISSUE THREAD

**Issue by sschuerz** [elasticsearch/elasticsearch#9555]
I found this old discussion on Nabble: http://elasticsearch-users.115913.n3.nabble.com/Specifying-analyzer-language-at-insert-time-td2638121.html

In current elasticsearch versions, is there a way to set the analyzer for a specific field based on the value on another field at insert time?

I have a "lang" field that specifies the language of the document, but currently only one field needs language specific analysis. Using the "_analyzer" field seems to be not a good solution here, because the analyzer would be set for all fields of the document.

Is there maybe a solution using a transform script in the mapping?

Any suggestions?

**Comment by dadoonet** [comment]
Note that _analyzer field will be removed in 2.0. See https://github.com/elasticsearch/elasticsearch/issues/9279

**Comment by sschuerz** [comment]
Another reason for not using the "_analyzer" field ...

**Comment by bleskes** [comment]
You could set an explicit analyzer on each field and only allow the field in question to fall back to the default (which is changing). The problem with this approach is in query time where you have to choose one analyzer. Using one analyzer to query a field parsed with many languages will probably not give you want and cause surprising results. You are better off indeed to have a field variant per language ala `field_en`, `field_de` and using [mapping transform](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-transform.html#mapping-transform) to put the original field in one of these based on the content of `lang`. You can then query all of the language fields (or just some) at query time.

PS - as this is not really an issue but a question, I would like to ask to use the [mailing list](https://groups.google.com/forum/#!forum/elasticsearch) instead. Closing this for now.
