### ISSUE TITLE
IllegalStateException with some 'min-to-max' regexp queries after upgrade to 1.4.2

### ISSUE THREAD

**Issue by wkf** [elasticsearch/elasticsearch#9564]
Hey there. 

After upgrading from elasticsearch 1.3.4 to 1.4.2, I noticed some odd behavior with a particular regexp my application was making. It seems related to the 'min-to-max' qualifier. Also, someone in IRC recommend I mention @mikemccand here. Thanks!

The following works fine:

    curl -XPOST 127.0.0.1:9200/_search -d '{"sort":["path"],"query":{"regexp":{"path":"0(.[0-9]*){0,1}"}}}'
 
The following causes an exception, notice the change from `1` to `2`:

    curl -XPOST 127.0.0.1:9200/_search -d '{"sort":["path"],"query":{"regexp":{"path":"0(.[0-9]*){0,2}"}}}'
 

Here's the response:

    {"error": "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; hardFailures {[0f-WyJPsQSGVoGRSCAH1-w][catalog_0.1][0]: SearchParseException[[catalog_0.1][0]: from[-1],size[-1],sort[<custom:\"path\": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@39c8716>]: Parse Failure [Failed to parse source [{\"sort\":[\"path\"],\"query\":{\"regexp\":{\"path\":\"0(.[0-9]*){0,3}\"}}}]]]; nested: IllegalStateException[from state (2) already had transitions added]; }{[0f-WyJPsQSGVoGRSCAH1-w][catalog_0.2][0]: SearchParseException[[catalog_0.2][0]: from[-1],size[-1],sort[<custom:\"path\": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@511653fa>]: Parse Failure [Failed to parse source [{\"sort\":[\"path\"],\"query\":{\"regexp\":{\"path\":\"0(.[0-9]*){0,3}\"}}}]]]; nested: IllegalStateException[from state (2) already had transitions added]; }{[0f-WyJPsQSGVoGRSCAH1-w][catalog_0.1][1]: SearchParseException[[catalog_0.1][1]: from[-1],size[-1],sort[<custom:\"path\": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@525169ca>]: Parse Failure [Failed to parse source [{\"sort\":[\"path\"],\"query\":{\"regexp\":{\"path\":\"0(.[0-9]*){0,3}\"}}}]]]; nested: IllegalStateException[from state (2) already had transitions added]; }{[0f-WyJPsQSGVoGRSCAH1-w][catalog_0.2][1]: SearchParseException[[catalog_0.2][1]: from[-1],size[-1],sort[<custom:\"path\": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@2e31771f>]: Parse Failure [Failed to parse source [{\"sort\":[\"path\"],\"query\":{\"regexp\":{\"path\":\"0(.[0-9]*){0,3}\"}}}]]]; nested: IllegalStateException[from state (2) already had transitions added]; }{[0f-WyJPsQSGVoGRSCAH1-w][catalog_0.1][2]: SearchParseException[[catalog_0.1][2]: from[-1],size[-1],sort[<custom:\"path\": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@7a434645>]: Parse Failure [Failed to parse source [{\"sort\":[\"path\"],\"query\":{\"regexp\":{\"path\":\"0(.[0-9]*){0,3}\"}}}]]]; nested: IllegalStateException[from state (2) already had transitions added]; }{[0f-WyJPsQSGVoGRSCAH1-w][catalog_0.2][2]: SearchParseException[[catalog_0.2][2]: from[-1],size[-1],sort[<custom:\"path\": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@5641b256>]: Parse Failure [Failed to parse source [{\"sort\":[\"path\"],\"query\":{\"regexp\":{\"path\":\"0(.[0-9]*){0,3}\"}}}]]]; nested: IllegalStateException[from state (2) already had transitions added]; }{[0f-WyJPsQSGVoGRSCAH1-w][catalog_0.1][3]: SearchParseException[[catalog_0.1][3]: from[-1],size[-1],sort[<custom:\"path\": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@56bcf6a7>]: Parse Failure [Failed to parse source [{\"sort\":[\"path\"],\"query\":{\"regexp\":{\"path\":\"0(.[0-9]*){0,3}\"}}}]]]; nested: IllegalStateException[from state (2) already had transitions added]; }{[0f-WyJPsQSGVoGRSCAH1-w][catalog_0.2][3]: SearchParseException[[catalog_0.2][3]: from[-1],size[-1],sort[<custom:\"path\": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@16fdf9f4>]: Parse Failure [Failed to parse source [{\"sort\":[\"path\"],\"query\":{\"regexp\":{\"path\":\"0(.[0-9]*){0,3}\"}}}]]]; nested: IllegalStateException[from state (2) already had transitions added]; }{[0f-WyJPsQSGVoGRSCAH1-w][catalog_0.1][4]: SearchParseException[[catalog_0.1][4]: from[-1],size[-1],sort[<custom:\"path\": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@484338f9>]: Parse Failure [Failed to parse source [{\"sort\":[\"path\"],\"query\":{\"regexp\":{\"path\":\"0(.[0-9]*){0,3}\"}}}]]]; nested: IllegalStateException[from state (2) already had transitions added]; }{[0f-WyJPsQSGVoGRSCAH1-w][catalog_0.2][4]: SearchParseException[[catalog_0.2][4]: from[-1],size[-1],sort[<custom:\"path\": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@711adf93>]: Parse Failure [Failed to parse source [{\"sort\":[\"path\"],\"query\":{\"regexp\":{\"path\":\"0(.[0-9]*){0,3}\"}}}]]]; nested: IllegalStateException[from state (2) already had transitions added]; }]", "status": 400}

**Comment by mikemccand** [comment]
Whoa, no good.  I will dig ... looks like a Lucene bug.

Mike McCandless

http://blog.mikemccandless.com

**Comment by wkf** [comment]
Awesome, thanks for the help!

**Comment by mikemccand** [comment]
OK this exception was fixed in
https://issues.apache.org/jira/browse/LUCENE-6046, which was included in
Lucene 4.10.3.

But Elasticsearch 1.4.2 is still based on Lucene 4.10.2 (1.5.0 will use
4.10.3).

I think we should upgrade Elasticsearch to Lucene 4.10.3 for the next 1.4.x
release; I'll open a PR.

Mike McCandless

http://blog.mikemccandless.com

**Comment by wkf** [comment]
Great, thanks a lot for looking in to this.

**Comment by mikemccand** [comment]
OK this is fixed:
https://github.com/elasticsearch/elasticsearch/commit/6bc797d508dabdf8e9e056c3b5db8148e7777a9c

Will be in Elasticsearch 1.4.3...

Mike McCandless

http://blog.mikemccandless.com
