### ISSUE TITLE
Allow getting parsed cookies from RestRequest

### ISSUE THREAD

**Issue by marko-asplund** [elasticsearch/elasticsearch#9568]
As a REST plugin developer I'd like to have an easy way of getting parsed cookies from an incoming HTTP request. Add a method for getting parsed cookies from RestRequest similar to HttpServletRequest#getCookies

Please see
http://tomcat.apache.org/tomcat-8.0-doc/servletapi/javax/servlet/http/HttpServletRequest.html#getCookies()

**Comment by spinscale** [comment]
Hey there,

you can already do it in a very simple way

```java
CookieDecoder cookieDecoder = new CookieDecoder();
Set<Cookie> cookies = cookieDecoder.decode(request.header(HttpHeaders.Names.COOKIE));
```

The `CookieDecoder` does not hold state, so you can instantiate it once and reuse it and you are basically down to a one-liner.

**Comment by marko-asplund** [comment]
Hi @spinscale,

technically, that works great, thanks!

IMO, it would still make sense to add such a convenience method since for plugin developers it can be quite non-obvious that you have to resort to using APIs found in org.elasticsearch.common.netty.handler.codec.http package.

**Comment by clintongormley** [comment]
Hi @marko-asplund 

I realise that this is a small change, but I'm against adding it to core. Any code we add we then need to test, support and include in bwc considerations.  Given that this isn't something that we use, I think that this burden has to fall on the plugin author who is using it to do so how they see fit.  

hope you understand :)
