### ISSUE TITLE
Tribe node setup

### ISSUE THREAD

**Issue by jpparis-orange** [elasticsearch/elasticsearch#9576]
I encountered two problems when setting up a tribe node
1. I can't set the cluster name of the tribe node
2. (minor) I can't set transport port

Versions used:
* ES: 1.4.2
* java: Java(TM) SE Runtime Environment (build 1.7.0_51-b13), 
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
* OS: MacOSX 10.9.5

You can find a recreation here: https://gist.github.com/jpparis-orange/44e464b8bb09246a4239
(Change ES_BASE to adapt to your environment).
In the recreation, there are 8 comment lines right before launching the tribe node. For each pair of lines, you find the -Des... option to add in the tribe node launch command and the result in the logs. When adding one of the four options, the tribe node will not discover the clusters.

**Comment by clintongormley** [comment]
Hi @jpparis-orange 

Sorry but I just can't follow what you're trying to do here. I think you're trying to do too much all at once, which means that it is not clear where things are going wrong.

**Comment by jpparis-orange** [comment]
Hello @clintongormley 

The gist recreation creates 2 clusters and a tribe node: everything is ok. Then, I'll change the recreation to exhibit the problems.

In the tribe node start (say after line 38), I add the following line 
-Des.cluster.name="T1" \
The tribe node will not connect to the clusters.
Same with -Des.cluster.name="elasticsearch" \

The second problem is about setting transport port. Starting with the recreation, add the following line after line 38
-Des.transport.tcp.port="9900" \
The tribe node will not start.
Same with -Des.transport.tcp.port="9300" \

**Comment by clintongormley** [comment]
OK - to make this easier to follow, start two clusters as follows:

    ./bin/elasticsearch --cluster.name C1 --node.name N1 -d
    ./bin/elasticsearch --cluster.name C2 --node.name N2 -d

Then start a tribe node as follows:

    ./bin/elasticsearch --tribe.t1.cluster.name C1 --tribe.t2.cluster.name C2 --node-name T1

This works, however doing: `GET localhost:9202/_cluster/state?pretty` will return a cluster name of `elasticsearch`, and this cannot be changed, eg:

    ./bin/elasticsearch --tribe.t1.cluster.name C1 --tribe.t2.cluster.name C2 --node-name T1 --cluster.name foo  # tribe node doesn't join the other cluster

Also, trying to set a different transport port for the tribe node doesn't work, eg:

    ./bin/elasticsearch --tribe.t1.cluster.name C1 --tribe.t2.cluster.name C2 --node-name T1 --transport.tcp.port 9900

The above fails with:

    {1.4.2}: Startup Failed ...
    - BindTransportException[Failed to bind to [9900]]
	    ChannelException[Failed to bind to: 0.0.0.0/0.0.0.0:9900]
		    BindException[Address already in use]

**Comment by jpparis-orange** [comment]
That's simpler, and it's what I had in mind: sorry for the complicated recreation. Do you want that I simplify the gist too?

Two complements: 
1. --cluster.name elasticsearch give the same result as --cluster.name foo
2. --transport.tcp.port 9300 give the same result as --transport.tcp.port 9900
