### ISSUE TITLE
Type Aliases

### ISSUE THREAD

**Issue by pickypg** [elasticsearch/elasticsearch#9598]
The idea for a type alias would be similar to an index alias, with an added benefit: you can alias fields to effectively rename them for queries.

The main example would be, imagine that you have a multifield mapped against a title field (e.g., `title` (not_analyzed), `title.en_us`, `title.fr`, etc). Using a type alias you could create the type that creates it -- we'll call it "type".

To facilitate simpler searching however, imagine that you traditionally search on a per language basis. You could use the type alias to search for english title using "title" by having an "english" type alias that renames `title.en_us` to `title`. Naturally, this can lead to fields being hidden and I am not completely decided on how much I like that, but this helps us to work around #8870 while still providing that behavior using type aliases.

**Comment by clintongormley** [comment]
Please let's not overload types and fields any more than they are already. We're trying to tidy this all up with #8870, I don't want to create more redirections.

Really this field-remapping is only relevant to the `query_string` and `simple_query_string` queries.  Any other queries can just use the appropriate names (or a template).  If anything, I'd suggest opening a ticket to support an allowed fields (with remapping) parameter on those two queries only.
