### ISSUE TITLE
Determine document ids on nodes

### ISSUE THREAD

**Issue by prateeka** [elasticsearch/elasticsearch#9618]
During our search performance testing, we see that some of our nodes are having higher churn rate than others. We want to investigate more on this to find out what all data is present on these nodes. Is their any way we can query the nodes to find out the document ids present on these nodes?

**Comment by clintongormley** [comment]
Hi @prateeka 

You can use the search preference to restrict results to a particular node or shard. See http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-preference.html#search-request-preference

**Comment by prateeka** [comment]
Thanks for the below link.

But I still am interested in accessing individual nodes/shards/replicas if
possible. This is for another use case where in elasticsearch could lose
consistency. Considering the financial impacts of consistency loss, we want
to make sure that data is always consistent among replicas. As such, we
would like to query individual replicas and ensure consistency. As such,
please advise.

Thanks.

On Mon, Feb 9, 2015 at 12:10 PM, Clinton Gormley <notifications@github.com>
wrote:

> Hi @prateeka <https://github.com/prateeka>
>
> You can use the search preference to restrict results to a particular node
> or shard. See
> http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-preference.html#search-request-preference
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsearch/elasticsearch/issues/9618#issuecomment-73580490>
> .
>



-- 
Prateek

**Comment by clintongormley** [comment]
@prateeka Read the link that I gave you.  It explains how to do it.

Also, the mailing list is a better place to ask questions like these.  The github issues list is for bug reports and feature requests only
