### ISSUE TITLE
Aggregations: Prevent negative intervals in date_histogram

### ISSUE THREAD

**Issue by cbuescher** [elasticsearch/elasticsearch#9634]
Using a negative numeric `interval` setting in `date_histogram` can lead to OOM erros on 1.4.2:

```
DELETE /_all

PUT /index/doc/1
{
  "date":  "2014/01/01"
}

PUT /index/doc/2
{
  "date":  "2014/03/01"
}

GET /index/doc/_search?search_type=count
{
    "query" : {
        "filtered" : {
            "query" : {
                "match_all" : {}
            }
        }
    },
    "aggs" : {
        "by_time" : {
            "date_histogram" : {
                "field" : "date",
                "interval" : "-60000",
                "min_doc_count" : 0,
                "format" : "yyyy-MM-dd--HH:mm:ss.SSSZ"
            }
        }
    }
}

-->
{
   "error": "ReduceSearchPhaseException[Failed to execute phase [query], [reduce] ]; nested: OutOfMemoryError[Java heap space]; ",
   "status": 503
}
```

**Comment by cbuescher** [comment]
Without the "min_doc_count" there seems to be no problem. Still, negative intervals don't make much sense in date_histogram, so I'll make it raise IllegalArgument exception.

**Comment by cbuescher** [comment]
For `histogram` there is already a check for negative intervals in place in HistogramParser, will just change it so also 0 is not allowed.

**Comment by jpountz** [comment]
> Without the "min_doc_count" there seems to be no problem. Still, negative intervals don't make much sense in date_histogram, so I'll make it raise IllegalArgument exception. 

FYI we prefer using ElasticsearchIllegalArgumentException instead of IllegalArgument whenever possible. The reason is that these exceptions are converted to 400 - Bad request on the rest layer.

**Comment by cbuescher** [comment]
Yes, that's what I actually meant. Is there a good way to test for exceptions in the ElasticsearchIntegrationTest? All the exceptions on shard level seem to get wrapped into a SearchPhaseExecutionException, the only way to check the undelying cause seems to me to check the message string. At least that's what I see a lot in other tests, e.g. SimpleChildQuerySearchTests:
```
...
catch (SearchPhaseExecutionException e) {
            assertThat(e.getMessage(), containsString("[has_child] 'max_children' is less than 'min_children'"));
        }
...
```

**Comment by jpountz** [comment]
Yeah, unfortunately I don't think we can do better (or I'm not aware of it).
