### ISSUE TITLE
Search behavior over all types is inconsistent

### ISSUE THREAD

**Issue by tobigue** [elasticsearch/elasticsearch#9647]
When searching over all types the search behavior is inconsistent in the case when a type, object and field have the same name.

    # Insert a document with type a
    curl -XPUT "http://localhost:9200/test/a/1" -d '{"a": {"a": "asdf"}, "x": {"a": "asdf"}}'

    # Insert a document with type b
    curl -XPUT "http://localhost:9200/test/b/1" -d '{"a": {"a": "asdf"}, "x": {"a": "asdf"}}'

    # We search in all types in field a.a and get 1 result
    curl -XPOST "http://localhost:9200/test/_search" -d '{"query": {"term": {"a.a": "asdf"}}}' | python -mjson.tool

    {
        "hits": {
            "hits": [
                {
                    "_id": "1", 
                    "_index": "test", 
                    "_score": 0.5945348, 
                    "_source": {
                        "a": {
                            "a": "asdf"
                        }, 
                        "x": {
                            "a": "asdf"
                        }
                    }, 
                    "_type": "a"
                }
            ], 
            "max_score": 0.5945348, 
            "total": 1
        }
    }

    # We search in all types in field x.a and get 2 results
    curl -XPOST "http://localhost:9200/test/_search" -d '{"query": {"term": {"x.a": "asdf"}}}' | python -mjson.tool

    {
        "hits": {
            "hits": [
                {
                    "_id": "1", 
                    "_index": "test", 
                    "_score": 0.5945348, 
                    "_source": {
                        "a": {
                            "a": "asdf"
                        }, 
                        "x": {
                            "a": "asdf"
                        }
                    }, 
                    "_type": "a"
                }, 
                {
                    "_id": "1", 
                    "_index": "test", 
                    "_score": 0.5945348, 
                    "_source": {
                        "a": {
                            "a": "asdf"
                        }, 
                        "x": {
                            "a": "asdf"
                        }
                    }, 
                    "_type": "b"
                }
            ], 
            "max_score": 0.5945348, 
            "total": 2
        }
    }

The problem seems to be, that in the first case the first a in the path a.a seems to be interpreted as type (which leads to the same search result as searching in path a.a.a).

A temporary workaround is to search in specific types, if possible:

    curl -XPOST "http://localhost:9200/test/a,b/_search" -d '{"query": {"term": {"x.a": "asdf"}}}'

The **expected behavior** would be that the first search query also returns both documents.

Tested against version: 1.4.2

**Comment by tobigue** [comment]
Tested against version: 1.4.2

**Comment by clintongormley** [comment]
Hi @tobigue 

Yes, this is a known issue.  We're tidying up all of these type/field ambiguities in #8870, and in this case specifically #8872

**Comment by tobigue** [comment]
Ah, super! Sorry I didn't find that myself.
