### ISSUE TITLE
Got RepositoryMissingException when creating a snapshot repository

### ISSUE THREAD

**Issue by inzpektor** [elasticsearch/elasticsearch#9650]
I'm trying to create a snapshot repository with the following command:

curl -XPUT "http://elasticsearchserver1:9200/_snapshot/erstdistribution" -d '{"type": "fs","settings": {"location": "/data/filetrans/backup/erstdistribution"}}'

...but I get

{"error":"RemoteTransportException[[elasticsearchserver1][inet[/10.0.108.7:9300]][cluster:admin/repository/put]]; nested: RepositoryVerificationException[[erstdistribution] [hLDideaFQGeOjujUgCeMsQ, 'RemoteTransportException[[elasticsearchserver2][inet[/10.0.108.71:9300]][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[erstdistribution] store location [/data/filetrans/backup/erstdistribution] is not shared between node [[elasticsearchserver2][hLDideaFQGeOjujUgCeMsQ][elasticsearchserver2.nces.slt.10ni.net][inet[elasticsearchserver2-23/10.0.108.71:9300]]{master=true}] and the master node]; ']]]; ","status":(reverse-i-search)`'

So then I mounted /data/filetrans/backup/erstdistribution over sshfs between the two machines like so:

elasticsearchserver2$ sshfs es@elasticsearchserver1:/data/filetrans/backup /data/filetrans/backup
elasticsearchserver2$ mount
...
es@elasticsearchserver1:/data/filetrans/backup on /data/filetrans/backup type fuse.sshfs (rw,nosuid,nodev,user=es)

When I then try to create the repository again, I got:
{"error":"RepositoryVerificationException[[erstdistribution] [hLDideaFQGeOjujUgCeMsQ, 'RemoteTransportException[[elasticsearchserver2][inet[/10.0.108.71:9300]][internal:admin/repository/verify]]; nested: RepositoryMissingException[[erstdistribution] missing]; ']]]","status":500}

The directory is created if it's not already present, and ownership and permissions are fine.

I should mention, however, that I'm running the ElasticSearch nodes from inside a webapp due to corporate restrictions on deployment procedures.  This means that the directory and all files written by ElasticSearch are owned by the "tomcat" user.

So, is this a bug or am I doing something wrong?

P.S. I apologize in advance for posting here, but I can't seem to find a dedicated ElasticSearch forum associated with elasticsearch.org!?

**Comment by dadoonet** [comment]
> P.S. I apologize in advance for posting here, but I can't seem to find a dedicated ElasticSearch forum associated with elasticsearch.org!?

Yes. See http://www.elasticsearch.org/community
Better ask there.

What elasticsearch tries to do is to create a tmp file on the repository and then try to read it from all the data nodes forming the cluster and then remove the file.
It most likely fails at one of those steps.

You should try to do the same from all nodes with the user which is running elasticsearch and see how it goes. Note that you could skip the verification using `?verify=false` IIRC.
