### ISSUE TITLE
elasticsearch - yellow status and no logs

### ISSUE THREAD

**Issue by caspertz** [elasticsearch/elasticsearch#9651]
we have a 4 node elasticsearch cluster - the head plugin shows green, but the cluster health shows yellow and doesnt want to change to green.  We have 2 "replicas" that are yellow and the stage is translog. we are running version 1.4.1.  We are running on ubuntu and have it set up as a service and it is not generating any log files.

**Comment by clintongormley** [comment]
Hi @caspertz 

Please ask questions like these on the mailing list first, as this github issues list is for bug reports and feature requests.  If you're not getting any logs, perhaps your disks are full? Or the logs are elsewhere?  By default, the Debian package logs to: /var/log/elasticsearch

**Comment by caspertz** [comment]
I have specified a specific directory /data/moloch/logs for the logs - there are no logs there and the disk is not full.

**Comment by clintongormley** [comment]
@caspertz perhaps check the permissions on that directory.  Either way this sounds like a configuration problem that is best discussed on the mailing list.
