### ISSUE TITLE
recovery settings docs: add comments about not being dynamically updateable

### ISSUE THREAD

**Issue by bhenderson** [elasticsearch/elasticsearch#9660]
on http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_important_configuration_changes.html

under recovery settings, it should state that the settings are not dynamically updateable. Also, it would be nice to suggest what to do if you do have these settings set and want to add a node. Also, is the expected_nodes setting for data only nodes, master only?

thank you!

**Comment by clintongormley** [comment]
Closed by https://github.com/elasticsearch/elasticsearch-definitive-guide/commit/7adb42b72534c628b84c8db860857d3195235dcc
