### ISSUE TITLE
remove node api feature request

### ISSUE THREAD

**Issue by bhenderson** [elasticsearch/elasticsearch#9661]
Suggesting a feature where a cluster assumes that all nodes that have joined belong to the cluster permanently. Then it can make decisions about recovery etc. If a node really does need to be removed, an explicit api could take care of it.

this would allow for the cluster to handle settings such as "gateway.expected_nodes" etc.

thank you!

**Comment by martijnvg** [comment]
@bhenderson The best way to deal with bringing down a node temporarily is to disable automatic allocation (setting `cluster.routing.allocation.enable` to `none` via cluster update api). This will disable recovery and allow you to bring down a node change the any static ES setting or system properties. After you brought up the node you can enable automatic allocation (setting `cluster.routing.allocation.enable` to `all` via cluster update api). If you decide to remove that permanently then you just enable automatic shard allocation.

If you shutdown a node gracefully it will send a leave request to the elected master, which removes the node from the cluster and let all other nodes know about it. 

So I don't see a need to add an specific api to remove nodes from a cluster.
