### ISSUE TITLE
Add Scala 2.11.x as default dynamic scripting language

### ISSUE THREAD

**Issue by asanderson** [elasticsearch/elasticsearch#9663]
Replace Groovy with Scala 2.11.x as the default dynamic scripting language assuming it can be security sandboxed. Considering Scala's second-to-none collection classes for big-data analytics and built in distributed cluster support (Akka), it's a better fit than Groovy anyway. ;-)

**Comment by mausch** [comment]
IMHO a script is not the place for "big-data analytics" or Akka... better to just write a plugin if you need that.

**Comment by asanderson** [comment]
Do you know Scala? It's a much better fit for Elasticsearch than Groovy for many reasons. Not to mention that the creator of Groovy said that if he had read a Scala programming book he wouldn't have bothered to create Groovy. Now that Pivotal has dropped financial support for Groovy, Scala would be a perfect replacement.

**Comment by asanderson** [comment]
Also, Elasticsearch is a JVM-based distributed search platform built on Netty, and Akka is a JVM-based distributed actor framework built on Netty. It's would be a perfect marriage!

**Comment by mausch** [comment]
Yes, I do know Scala, in fact I'm now using Scala in a project at work. I also like it much better than Groovy for general development. None of that is relevant here.

**Comment by asanderson** [comment]
No relevant? Really? Well how about just replacing Groovy support with the equivalent Scala support and enabling dynamic scripting? So, you wouldn't want to use any of the Scala collection functions in a query? Much more power than Groovy. And, you can't see how Akka would nicely integrate w/ the Elasticsearch cluster? Or, using a tight Spark integration for analytics? Seems like a match made in heaven, IMHO.

**Comment by mausch** [comment]
As I said before, I don't think scripts are the right place for Akka or Spark integration. Instead, I'd write a plugin: you get a proper development environment, tooling, testing, etc, you can write it in Scala and use Akka or Spark or whatever you want. 
I'd only use a ES script (not talking about native scripts which are basically plugins) for simple single-line expressions.
I never said you shouldn't use Akka or Spark with Elasticsearch or anything like that. No need to get all worked up over something like this.

**Comment by asanderson** [comment]
No worries. I wasn't worked up. I just didn't understand your point. Just to clarify, I meant Scala should be a 1-for-1 replacement for Groovy in ES to include dynamic scripting but not just limited to dynamic scripting (e.g. Scala client, DSL, etc.). Also, it would be great to have an Akka and/or Spark plugin with the same tight ES integration like the Hadoop plugin; i.e. at the cluster level.  So, I guess there are really several potential new feature requests here, but let's at least start with dynamic scripting. ;-)

**Comment by s1monw** [comment]
I am pretty convinced that all general purpose languages have the same problems when it comes to java security. We will evaluate the possibilities that we have here and will take our time to make a good move along the lines. I think before we think about re-enabling dynamic scripting we will need to fix other problems or add better APIs / Services that allow users to pass their scripts in a safe way.  I will close this issue for now (we can reopen if there times are changing on the security end). 

thanks for providing the idea.

**Comment by asanderson** [comment]
Really? You are closing this without any serious consideration? The rationale given for dropping Groovy was,  "after discussing the issue with the Groovy team, we have come to the conclusion that the Groovy language is too dynamic to be properly contained by a sandbox."  i.e. This is a Groovy issue. Scala is a strongly typed language which is quite the opposite of Groovy. Please reopen this request until a *real* analysis can be done; otherwise, it sends a bad message to the community!

**Comment by kimchy** [comment]
I would like to purpose that if someone wants to try it out, it should first be as a plugin, and if someone on this thread is interested, its quite simple to write a plugin that would add for example scala as a language, there are already several out there (like here: https://github.com/elasticsearch/elasticsearch-lang-javascript). There is an open question in my mind if Scala can be successfully sandboxed..., but go ahead and write a plugin that does it?

**Comment by costin** [comment]
Since Spark was mentioned, it's worth pointing out that under Elasticsearch Hadoop umbrella there's a tight integration between Spark and Elasticsearch documented [here](http://www.elasticsearch.org/guide/en/elasticsearch/hadoop/master/spark.html). Provides both a Java and a Scala DSL, support for Spark Core and SparkSQL as well.

**Comment by asanderson** [comment]
@kimchy Roger that. What prompted me submitting #9663 was the assertion that the issue of sandboxing was due to the dynamic nature of Groovy itself after you spoke w/ the Groovy team.  If the issue is actually with any JVM scripting language, then that's a different story, but given the strong typing of Scala, I would suggest that it would be worth having a similar conversation with Martin Odersky et. al. regarding Scala sandboxing. Otherwise, extending Lucene Expressions language would seem much less attractive than the power of Scala, IMHO.  Just my $0.02.

**Comment by asanderson** [comment]
@costin Thanks for the spark support reference. Somehow I missed it. ;-)

**Comment by costin** [comment]
@asanderson Btw, the dev build is published for both Scala 2.11 and 2.10 (useful when using Spark 1.2.x)
