### ISSUE TITLE
Marvel showing same graph for Network transport received and sent  bytes

### ISSUE THREAD

**Issue by satishmallik** [elasticsearch/elasticsearch#9668]
I have the following setup,
3 Query Nodes
3 master nodes
3 data nodes

All indexing requests come to query nodes which is also acting as ingestion node.
I was looking at network usage on Nodes on es cluster.
In my setup 
1) an index has 3 Primary and 2 Replicas. All 3 primaries are located on a single node.
2) It is default write consistency model which is Quorum.

During bulk indexing I am seeing on Marvel,

1) NETWORK TRANSPORT BYTES RECEIVED On Primary node is 118KB/s while on Nodes containing Replica nodes are 2KB/s. 
2) NETWORK TRANSPORT BYTES SENT is same as NETWORK TRANSPORT BYTES RECEIVED.on all nodes.

There are 2 questions here,
1) Is marvel giving correct HTTP data,
2) How can sent and received bytes are same on all nodes?

**Comment by bleskes** [comment]
the issue here is that the Transport Bytes Received chart was wrongly configured to use `transport.tx_size_in_bytes` , the same field Transport Bytes Sent uses. This was fixed with Marvel 1.3.0 . I suggest you upgrade.

**Comment by satishmallik** [comment]
Thanks bleskes for your response

**Comment by bleskes** [comment]
@satishmallik thanks for reporting! you never know.
