### ISSUE TITLE
Separate thread pool for Kibana stats requests

### ISSUE THREAD

**Issue by mausch** [elasticsearch/elasticsearch#9676]
While developing a plugin, somehow [some search requests started hanging](https://groups.google.com/d/msg/elasticsearch/5QHqc9RNsZ0/J1SBNGblFXkJ), which eventually led to the queue filling up and rejecting all requests. Requests from Kibana were of course also rejected, which left me with no information about what was going on in the cluster. 
As this is critical information that shouldn't be affected by any misbehaving search requests, it should probably go in a separate threadpool.

**Comment by bleskes** [comment]
@mausch do you mean Marvel or Kibana?

**Comment by mausch** [comment]
Sorry, I meant Marvel.

**Comment by bleskes** [comment]
no worries. This is exactly the reason why we recommend sending the marvel data to another cluster. Saturated search thread pool is only one of the things that can happen and it's better to keep the data fully separated. See http://www.elasticsearch.org/guide/en/marvel/current/_installation.html#_installing_a_secondary_monitoring_cluster for more details.

I'm going to close it for now. Feel free to reopen if you feel something is not addressed.

**Comment by mausch** [comment]
Thanks!
