### ISSUE TITLE
One node stuck, not responding and brings down the entire cluster

### ISSUE THREAD

**Issue by mkliu** [elasticsearch/elasticsearch#9685]
Hi, we had two incidents of this now. We had dedicated master and client nodes. So the symptom is:
1. Management APIs such as _node, cat are not returning. Default the default 9200 response. If I directly hit the master node, default 9200 is returning 200. But the other APIs are not working.
2. No out of memory exception yet. We set HEAP at 20GB, the but the usage is about 15GB only. ( Could it be because of this? Machine is 32GB memory)
3. I restarted a couple of high memory nodes, and master too, still not recovering. Until I found on some master node logs pointing to a node saying operation cannot be executed on bad node.
4. The bad node's log is missing an entire time period since a couple of hours ago. And in Marvel, the node stopped reporting status around the same time too. Didn't see anything suspicious on Marvel events though.
     4.a. First time this happens, the machine is doing some GC operation and stuck
     4.b Second time this happens there's no obvious problem exception some index operation failing. And this time I checked the field_data size too, it's not big, around 1GB only. 

Any clue or else I should look at?

**Comment by markwalkom** [comment]
I'd suggest that you raise this on the [Elasticsearch list](https://groups.google.com/forum/#!forum/elasticsearch), as the issues raised here are usually related to code problems, not operational ones as this appears to be :)

**Comment by clintongormley** [comment]
As @markwalkom said, you should ask questions like these in the mailing list, rather than in this github issues list, which is for bug reports and feature requests only.

That said with long GCs, I'd check out your swap settings - it sounds like you have swap enabled (and you don't have mlockall working)

**Comment by mkliu** [comment]
Sorry about that, I've sent question to mailing list already too.

**Comment by dlvovsky** [comment]
Sorry to post here, but we're suffering from the same thing in v.1.7.6., and I can't find your post nor the response anywhere.  If someone can point me to this post in the mailing list, I'd be much obliged.
