### ISSUE TITLE
Is reverse_nested aggregation supported in children aggregation?

### ISSUE THREAD

**Issue by yangou** [elasticsearch/elasticsearch#9686]
We have a heavy use case of parent-children index.
When we do children aggregation on the child, we also want to nest another aggregation which is based on the parent document. 

I've seen there is a reverse_nested aggregation supported for nested aggregation, but when I try it in the children aggregation I got this error:
```
 [Reverse nested aggregation [gender] can only be used inside a [nested] aggregation]]; }]"
```

So I'm guessing it's not supported?
Is there any way to achieve that functionality in 1.4.2?

Thanks.

**Comment by martijnvg** [comment]
That is correct, a `reverse_nested` can't be placed in a `children` agg. It can only be places under a `nested` agg. There is no equivalent of the `reverse_nested` aggregator for the parent/child case yet. 

There is no easy workaround, other than modelling your data in such a way that you don't need this aggregator.
