### ISSUE TITLE
Search box in "Embed" iframe

### ISSUE THREAD

**Issue by ZeAleks** [elasticsearch/elasticsearch#9708]
Hi,

Here is another possible improvement. When I share a visualisation or dashboard, I'd like to have a parameter that allow me to include the search box and the filter pan (or not).

That will allow easily to have a full useable report.

Thank you.
Aleks

**Comment by dadoonet** [comment]
I think you are talking about Kibana, right?

You should look at https://github.com/elasticsearch/kibana

**Comment by ZeAleks** [comment]
OH yes sorry ... I miss navigated :)
