### ISSUE TITLE
[Query DSL] Do not consider empty object at the end of array invalid token

### ISSUE THREAD

**Issue by lukas-vlcek** [elasticsearch/elasticsearch#9711]
This might sound weird at start but I actually think is very useful feature, thus filling ticket to keep it around.

When I use search templates it can happen that I need to populate something from parameter that is an array. In some situations this can lead to challenging situation in Query DSL. For example, imagine I need to pass in an array of tags that goes to `or` filter:

    "filter": {
        "or": [
            { "term": { "tag": "param_value1" }},
            { "term": { "tag": "param_value2" }},
            ...
            { "term": { "tag": "param_valueN" }}
        ]
    }

Generating such output from Mustache template does not seem to be easy to me. There are some tricky parts that need to be handled correctly. First, it is not easy to omit whole `or` filter part (or even whole `filter` part in this case) if tags array is empty. Secondly, we need to omit comma after the last element in the array. The best I have come up with so far is the following template:

    "filter": { "or": [ {{#tags}} { "term": { "tag": "{{.}}" }}, {{/tags}} {} ] }

This results into the following output:

    "filter": {
        "or": [
            { "term": { "tag": "param_value1" }},
            { "term": { "tag": "param_value2" }},
            ...
            { "term": { "tag": "param_valueN" }},
            {}
        ]
    }

If the `tags` parameter is empty or missing then it will result into the following:

    "filter": {
        "or": [
            {}
        ]
    }

Ignoring the `{}` token greatly simplify Mustache templating. May be ES is already intelligently doing this but I am not sure if this was intentional or just a luck. If the later I would like to suggest making it an official feature and part of "official" Query DSL grammar.

Hope this makes sense.

**Comment by clintongormley** [comment]
I think this is similar to https://github.com/elasticsearch/elasticsearch/issues/7240

Rather than requiring the empty `{}`, we should just make `and` and `or` with an empty array just return match all.  Actually, this is probably a non-issue because of https://github.com/elasticsearch/elasticsearch/issues/8960

**Comment by lukas-vlcek** [comment]
@clintongormley I have been thinking more about this in the mean time and I found better solution on my end to this problem. I am also not sure if I explained the issue well (or may be it is that ppl did not start using complex search templates yet? as I still see #8308 not fixed). So I think it is ok to close this ticket for now (may be we can get back to it later if needed).

As far as discussion about meaning of empty `{}` in specific cases goes I would personally prefer if it is reported as an error. It seems that this situation happens because various client tools (or Mustache templating) have its limits but this should not be taken as an excuse to make ES query grammar more relaxed. Quite contrary IMO. Just my 2 cents.

**Comment by marshall007** [comment]
@clintongormley @lukas-vlcek I couldn't find any currently open issues still related to this problem, but it definitely exists. There's no straight-forward solution to the trailing comma problem that arises in situations like these:

```js
{
  "aggs": {
    {{#aggregations}}
    "{{.}}": {
      "terms": {
        "field": "{{.}}.raw"
      },
      "aggs": {
        "parent": {
          "cardinality": { "field": "_parent" }
        }
      }
    },
    {{/aggregations}}
  },
  "query": { /* ... */ }
}
```

```js
{
    "id": "template_test",
    "params": {
        "aggregations": ["first_name", "last_name"]
    }
}
```

I think one of two things needs to happen for this to be solved across the board:

1. Have the JSON parser ignore trailing commas (at least in the context of rendering templates).
1. Provide a mustache extension or some other special notation for "first/last element of an array" conditionals.

**Comment by nik9000** [comment]
I'm totally in favor of us being as standard as possible but, man, I'd love the json parser to ignore trailing commas! I'd like it but I don't know if it is the right thing for Elasticsearch. I like all kinds of silly stuff.

**Comment by clintongormley** [comment]
@marshall007 as of 2.4.0, there is now a `toJson` template helper which should do the right thing.  See https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-template.html#_converting_parameters_to_json

**Comment by lukas-vlcek** [comment]
@clintongormley Clint, how does it handle case when the input "clauses" array is empty? Would it render empty "must" array in final JSON? I.e. `{"query":{"bool":{"must": []}}}`.

**Comment by clintongormley** [comment]
@lukas-vlcek yes:

    GET _render/template
    {
      "inline": "{\"query\": { \"bool\": { \"must\": [ {{#toJson}} clause {{/toJson}} ]}}}",
      "params": {
        "clauses": []
      }
    }

returns:

    {
      "template_output": {
        "query": {
          "bool": {
            "must": []
          }
        }
      }
    }

**Comment by lukas-vlcek** [comment]
@clintongormley ok, so the `{{#toJson}} my_id {/toJson}}` in `inline` value needs to match `my_id` found in `"params": { "my_id": [ ... ] }`.

BTW, the doc contains typo: `{{toJson}}` should be `{{#toJson}}`, see the beginning of the paragraph.

Thanks.

**Comment by clintongormley** [comment]
thanks @lukas-vlcek - fixed

**Comment by marshall007** [comment]
@clintongormley are you suggesting that I move the full `aggs` clauses into the `params`? Sort of defeats the purpose of using search templates in the first place, doesn't it?

**Comment by clintongormley** [comment]
No I'm not - I'm suggesting that you use `toJson` to render your array, instead of using mustache loops.  the docs have an example

**Comment by marshall007** [comment]
@clintongormley in my example, I'm building an object body. Do `aggs` support some sort of array notation that I'm unaware of?

**Comment by clintongormley** [comment]
@marshall007 oh i see what you're doing now.  you're stuck with crappy mustache loops i'm afraid.

**Comment by marshall007** [comment]
@clintongormley yea and there is literally no solution to removing the trailing comma from the last element in the loop without doing insane things in your `params`. It would be really trivial for you guys to hack it together on the backend by doing something like this on any array `field`s specified in `params`:

```js
params[field][0].$first = true
params[field][params[field].length - 1].$last = true
```

Then you could do this in the template:

```js
{
  {{#aggregations}}
  "{{.}}": {
    "terms": {
      "field": "{{.}}.raw"
    },
    "aggs": {
      "parent": {
        "cardinality": { "field": "_parent" }
      }
    }
  }{{^.$last}},{{/.$last}}
  {{/aggregations}}
}
```
