### ISSUE TITLE
Documentation for query should use POST not GET verb

### ISSUE THREAD

**Issue by bibhas2** [elasticsearch/elasticsearch#9712]
In the documentation, a query request is made using the ``GET`` verb and with a body entity. Although the HTTP spec does not clearly prevent one from using body entity with ``GET`` it is highly unusual. Many tools and servers do not allow body for ``GET`` requests. Documentation should use ``POST`` for queries which is allowed by ES. Otherwise, it gives the impression that ``GET`` is the only supported verb for query.

Example documentation page:

http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_talking_to_elasticsearch.html

**Comment by dadoonet** [comment]
POST means in REST that you are changing the server state. Which obviously not the case when you search for something. You basically wants to get results.

Which verb would you use to run /_search?q=parameter

I'm pretty sure you would use a GET here.

What troubles you here is that you have GET with a body. But as you know, we also support POST for tools which can not run GET with a body. 

I'd say that it's better to be consistent on REST layer so the documentation is correct IMO.

**Comment by bibhas2** [comment]
I agree that GET is appropriate from a RESTful design point of view. I was quite happy to see the use GET until I realized that many tools (such as Chrome) and servers do not allow entity for GET. At minimum mention in the doc that POST is also supported.

**Comment by dadoonet** [comment]
Do you mean that? http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_empty_search.html#_empty_search

Look the end of the section.

Closing as examples will remain with GET.

**Comment by javanna** [comment]
Also, if you want to stick to GET you can just provide the body as the `source` query string parameter, properly url encoded.
