### ISSUE TITLE
RandomScoreFunction generates numbers > 1.0 for 1.2 & 1.3

### ISSUE THREAD

**Issue by francoisforster** [elasticsearch/elasticsearch#9734]
curl -XPOST 'localhost:9200/_search?pretty=true' -d '{
  "query": {
    "function_score": {
      "functions": [
        {
          "random_score": {}
        }
      ],
      "score_mode": "sum"
    }
  } 
}'

{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.4613643E7,
    "hits" : [ {
      "_index" : "index",
      "_type" : "type",
      "_id" : "1",
      "_score" : 1.4613643E7,
      "_source":{
...}]}
}

This doesn't happen with 1.0 or 1.4

**Comment by rjernst** [comment]
@francoisforster This was purposefully changed in #7446 to address the issue of unknown range of the returned score.  If you need a value > 1, you can apply a weight to the score (e.g a weight of 10 would return random values between 0 and 10).

**Comment by francoisforster** [comment]
How do you apply a weight in 1.3?

**Comment by francoisforster** [comment]
I use random score as a 2nd order function (after a filter function).
I consider this a bug because I can't upgrade from 1.0 to 1.3 without breaking the functionality.
In 1.0 the behavior is correct and in 1.3 I would have to boot the filter function by 100000000, which I can't do with 1.0 since there is not enough precision.

**Comment by rjernst** [comment]
Yes, this was a bug, and was fixed in 1.4.
