### ISSUE TITLE
RemoteTransportException and weird pending_tasks

### ISSUE THREAD

**Issue by nirmalc** [elasticsearch/elasticsearch#9737]
This is related to exception in https://github.com/elasticsearch/elasticsearch/issues/4938 .Though i dont have an exact way to recreate - its happening in 1.3.4 

```
curl -XGET 'http://localhost:9200/_cat/pending_tasks'
{"error":"RemoteTransportException[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.tasks.PendingClusterTasksResponse]]; nested: TransportSerializationException[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.tasks.PendingClusterTasksResponse]]; nested: ElasticsearchIllegalArgumentException[can't find priority for [-33]]; ","status":500}

curl localhost:9200
{
  "status" : 200,
  "name" : "stuff-elasticsearch-XXXXXX",
  "version" : {
    "number" : "1.3.4",
    "build_hash" : "a70f3ccb52200f8f2c87e9c370c6597448eb3e45",
    "build_timestamp" : "2014-09-30T09:07:17Z",
    "build_snapshot" : false,
    "lucene_version" : "4.9"
  },
  "tagline" : "You Know, for Search"
}
```

But pending_tasks?local=true does work and in master node - it shows some weird tasks like ( note one with -1 ) 
```
 883   16m HIGH      refresh-mapping [&cherry-starfruit][[entity]] 
 884   16m HIGH      refresh-mapping [&cloudberry-clementine][[entity]] 
 741    -1 HIGH      unknown 
 816   18m HIGH      refresh-mapping [&cloudberry-clementine][[entity]] 
 887   16m HIGH      refresh-mapping [&apricot-fig][[entity]] 
 888 15.9m HIGH      refresh-mapping [&cloudberry-clementine][[entity]] 
 889 15.9m HIGH      refresh-mapping [&cantaloupe-grape][[entity]] 
 979 13.8m HIGH 

```

Must be related - now the cluster cannot accept new node clients joining or any _cluster wide settings-update.

is it some serialization/deserialization issue ? Already checked java versions in all nodes and node clients..

```
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)
```

**Comment by clintongormley** [comment]
@nirmalc this sounds familiar - i believe these tasks with negative priorities are "task removal tasks", and are not usually serialized in the cluster state.  (I forget why it happens).

This is harmless, but I believe that you no longer see this message in recent versions. @bleskes can confirm?

**Comment by clintongormley** [comment]
@bleskes has confirmed that his has been fixed (https://github.com/elasticsearch/elasticsearch/issues/4938#issuecomment-76466621)

closing, thanks
