### ISSUE TITLE
Terms aggregation: add include_values

### ISSUE THREAD

**Issue by ewgRa** [elasticsearch/elasticsearch#9738]
There is "include" in terms aggregation.

I want filter by array of values. For example record have "categories" field, and I want aggregate only by specific categories, not all categories.

I can make regular expression like "category1id|category2id" and use "include", or use "script" for this, but seems best performance will be reached by intersecting array.

**Comment by jpountz** [comment]
Hi @ewgRa, this has been implemented in #7727 and will be in Elasticsearch 1.5.
