### ISSUE TITLE
Help with 4 node cluster

### ISSUE THREAD

**Issue by sysads** [elasticsearch/elasticsearch#9742]
Hi

I am in need of help on setting up a 4 node elasticsearch servers. I have installed and configured ES on all 4 nodes but I am lost as to what the configuration will be if I want to have all 4 nodes both master and data; node A act as primary shard while node B acts as its replica then node C as primary shard while node D as its own replica.

Thanks

**Comment by ebuildy** [comment]
I am not sure this is how ES replications works. ES will automatically spread primary/replica shards across your nodes.

I am not sure about the idea of having 4 master ^^

What about reading http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_how_primary_and_replica_shards_interact.html ?

**Comment by clintongormley** [comment]
Hi @sysads 

As @ebuildy suggested, I'd start with the documentation then ask any further questions on the mailing list.  This github issues list is for bug reports and feature requests
