### ISSUE TITLE
ElasticSearch - null nested aggregation

### ISSUE THREAD

**Issue by spvemm** [elasticsearch/elasticsearch#9745]
In the below query, if "in_stock_products" returns a "doc_count" of 0, "avg_price" returns a value of "null".

How can one prevent a null value aggregation?

Query:

POST _search/
{
    "aggs" : 
    {
        "in_stock_products" : 
        {
             "filter" : { 
                 "range" : { 
                      "stock" : { 
                          "gt" : 0 
                      } 
                 } 
             },
             "aggs" : { 
                   "avg_price" : { 
                           "avg" : { 
                                 "field" : "price"
                           }
                    } 
             }
       }
   }
}

Result:

"in_stock_products":  {
    "doc_count": 0,
    "avg_price": { 
         "value": null
    }
}

**Comment by clintongormley** [comment]
Hi @spvemm 

You can't.  The agg is null because there were no matching documents.  An avg of zero would be incorrect, because it is pretending that it has calculated a real average.

You need to handle nulls on the application side.
