### ISSUE TITLE
Kibana 4 appears to break if using scripted fields and deleting old logstash indices

### ISSUE THREAD

**Issue by silverl** [elasticsearch/elasticsearch#9751]
Using Kibana 4 RC1 and ES 1.4.3.

I purge logstash indices nightly to maintain a rolling 90-day window of log data.

I created some visualizations and dashboards against my logstash indexes using the basic index pattern [logstash-]YYYY.MM.DD. 

I added scripted fields like:
bytestotal = doc["bytesin"].value + doc["bytesout"].value
@timestamp._hourOfDay	Integer.parseInt(new Date(doc["@timestamp"].value).format("H"))	number	

Everything works fine for that day. The next day, Kibana 4 is throwing errors on the Discover tab and nothing works. Overnight, the oldest index was intentionally deleted by cron.

If I then delete all my scripted fields, Kibana 4 starts working again. I can re-add them, continue on my merry way.

I couldn't find any errors in the node service logs. Couldn't figure out how to extract a meaningful error from the K4 UI.

**Comment by rashidkpc** [comment]
It look like you're using scripts from Beta 3. RC1 and above do not support Groovy scripting due to this ticket: https://github.com/elasticsearch/elasticsearch/issues/9655

**Comment by silverl** [comment]
Can you tell me how you arrived at the conclusion that this is due to scripts from Beta 3?

**Comment by clintongormley** [comment]
Closing this ticket as this is not an Elasticsearch issue.
