### ISSUE TITLE
CircuitBreaking [FIELDDATA] too large but no evictions occurred

### ISSUE THREAD

**Issue by perseo-dev** [elasticsearch/elasticsearch#9752]
After some queries with few filters, ES begins to respond the following error; the error is quite clear, but I don't understand (I'm still ignorant on ES) because ES don't evict others cache items to manage the new queries; if I clear manually the cache, the query will be satisfied; but I would like that ES frees up the memory because otherwise my software have to identify the error and clear programmatically the cache.

"{
   "error": "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[n4m5PSADT2CwxyuxbKpHdw][public_offers][0]: ElasticsearchException[org.elasticsearch.common.breaker.CircuitBreakingException: [FIELDDATA] Data too large, data for [UNIT] would be larger than limit of [633785548/604.4mb]]; nested: UncheckedExecutionException[org.elasticsearch.common.breaker.CircuitBreakingException: [FIELDDATA] Data too large, data for [UNIT] would be larger than limit of [633785548/604.4mb]]; nested: CircuitBreakingException[[FIELDDATA] Data too large, data for [UNIT] would be larger than limit of [633785548/604.4mb]]; }{[lay1SfFATkW_3pFeqfchPw][public_offers][1]: RemoteTransportException[[bi-node-02][inet[/10.0.0.5:9300]][indices:data/read/search[phase/query]]]; ...
   "status": 500
}"

**Comment by clintongormley** [comment]
Hi @perseo-dev 

The fielddata cache really isn't a normal cache, in that you don't want values to be evicted.  Building this cache is very expensive.  Instead, you should look at using doc values instead of fielddata to avoid using up so much of your heap.

For questions about how to use doc values, please consult the docs and ask questions in the mailing list.

**Comment by perseo-dev** [comment]
ok, thank you very much!
