### ISSUE TITLE
[DOCS] Scripted Transforms use inconsistent script parameter for files

### ISSUE THREAD

**Issue by pickypg** [elasticsearch/elasticsearch#9754]
When using the Mapping Transform API, you can specify a script. It's undocumented, but you can also specify it using `script_file`, which is the same as specifying the `file` parameter to a normal script.

We should update the documentation to properly show off the `file` parameter as well as mirror support for both `file` and `script_file` every scripting area (not just a documentation effort, so perhaps it should be a separate issue).

```
PUT /transform-index
{
  "mappings": {
    "type": {
      "transform": [
        {
          "script_file": "blah",
          "lang": "groovy"
        }
      ]
    }
  }
}
```

Also unmentioned, you can still use `script` (just like for normal scripts!):

```
PUT /transform-index
{
  "mappings": {
    "type": {
      "transform": [
        {
          "script": "blah",
          "lang": "groovy"
        }
      ]
    }
  }
}
```

**Comment by colings86** [comment]
I committed a PR a while ago https://github.com/elasticsearch/elasticsearch/pull/7977 which aimed to unified all the parameter names for scripts across all the APIs. It looks like this one might have got missed so the transform API's parser should be updated to use the stuff from this PR. 

At the time we settled on the convention that the options should be `script` for inline scripts, `script_file` for file scripts and `script_id` for indexed scripts. `file` is ambiguous as it's not explicit that it refers to a file for a script, the file could be for something else.

I would say that we should update the transform API to use the ScriptParameterParser like the rest of the script APIs, but I would be -1 for adding the `file` parameter to the docs as this name is effectively deprecated and users should be using `script_file` instead.

**Comment by rjernst** [comment]
+1 to @colings86's suggestion

**Comment by pickypg** [comment]
@colings86 I didn't know about that PR. +1 on your points

**Comment by clintongormley** [comment]
@colings86 can this issue be closed now?

**Comment by colings86** [comment]
@clintongormley yeah I think it can as the script module documentation has been updated to reflect the preferred naming
