### ISSUE TITLE
Aggregation on non indexed fields

### ISSUE THREAD

**Issue by kamaradclimber** [elasticsearch/elasticsearch#9762]
I am trying to make aggregations on time series to get fixed-duration buckets of time.
I need to search based on timestamp (`ts` field) but never on values (`value` field) so my mapping specifies to skip indexing on `value`.
However, when I aggregate, it seesms that ES does not find the `value` field and use count zero instead.

To reproduce (marvel syntax):
- define a mapping template as:
```
PUT _template/test
{
  "template": "test",
  "mappings": {
    "metric" : {
      "properties": {
        "ts": { "type": "date"},
        "value": { "type": "double", "index": "no"}
      }
    }
  }
}
```
- index one document:
```
POST test/metric
{
  "ts": 4,
  "value": 42
}
```
- aggregate:
```
GET test/metric/_search?search_type=count
{
  "aggs": {
    "sum_indexed_field": { // non sense, only here to show aggregation work on indexed field
      "sum": {
        "field" : "ts"
      }
    },
    "sum_nonindexed_field" : {
      "sum" : {
        "field": "value"
      }
    }
  }
}
```

Ouput is rather disappointing:
```
{
   "took": 240,
   "timed_out": false,
   "_shards": {
      "total": 4,
      "successful": 4,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 0,
      "hits": []
   },
   "aggregations": {
      "sum_indexed_field": {
         "value": 4 // ok
      },
      "sum_nonindexed_field": {
         "value": 0 // should get 42 here
      }
   }
}
```

Am I doing something wrong?
Is this due to the way aggregations work?

Note 1 : using `not_analyzed` instead of `no` makes it work.
Note 2 : adding `"doc_values": true` makes it work as well.

But I'd like to understand.

**Comment by kamaradclimber** [comment]
using `not_analyzed` instead of `no` make it work.

But I'd like to understand.

**Comment by jpountz** [comment]
Elasticsearch duplicates your content depending on what it needs to do with it:
 - it has a store which typically stores the `_source` and is useful to give data back
 - it has an inverted index that is used for searching/filtering
 - and finally "fielddata" which is a columnar view on your data that it uses for aggregations and sorting.

This last thing is what is useful in your case. However elasticsearch does not store fielddata by default but builds it in memory from the inverted index on the first time that you need it. This is why you can only sort and aggregate on fields that are indexed by default.

If you don't need to search but only to aggregate on these fields, you can disable indexing (index: no) but you need to tell elasticsearch to store fielddata at indexing time. The name of this feature is called `doc_values`, see http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/doc-values.html.

Also note that `index: no` will prevent you from not only searching for individual terms, but also running range, prefix, wildcard queries or filters.

**Comment by kamaradclimber** [comment]
thanks a lot for the detailed explaination

**Comment by ivanprostran** [comment]
> If you don't need to search but only to aggregate on these fields, you can disable indexing (index: no) but you need to tell elasticsearch to store fielddata at indexing time. The name of this feature is called doc_values,

I have done that but I'm still having the same visualization problem in Kibana v4.2.2 (elastic 2.2.x).

Some field definition is as follows:

"SomeCounterToSumOrAgregate": {
                    "type": "long","store":"yes","index": "no","doc_values": true
    },

and I am not able to sum/aggregate it because ** Kibana doesn't show it.** as already stated in the subject.

If I'm not wrong "doc_values" feature is an optimization for "fielddata" according to the official documentation --> https://www.elastic.co/guide/en/elasticsearch/guide/current/doc-values.html.

...And there is nothing wrong with that, actually Elastic back-end  returns the data properly as stated in documentation, so  this is clearly Kibana's behavior. 

I would appreciate any suggestion on how to make Kibana show  non-indexed fields (visualization)
To be more specific I'm not even clear about  whether it is a bug or feature.
What I understand is the following: I don't need massive unique data (counters, bytes or something like that) to be indexed. It is clearly unnecessary overhead.


Thanks !

**Comment by surabhi1029** [comment]
@kamaradclimber I am trying to use "doc_values": true in my mapping, however it is throwing mapping parser exception: "reason": "Mapping definition for [stats] has unsupported parameters:  [doc_values : true]"

My es version: 6.0.0
payload i am using:
PUT filebeat-6.2.2-2019.03.27
{
	"mappings": {
		"_default_": {
			"_all": {
				"enabled": false
			}
		},
		"doc": {
			"properties": {
				"name": {
					"type": "keyword"
				},
				"dt": {
					"enabled": false
				},
				"cb": {
					"enabled": false
				},
				"cd": {
					"enabled": false
				},
				"delivered_at": {
					"enabled": false
				},
				"app": {
					"type": "keyword"
				},
				"md": {
					"enabled": false
				},
				"read_at": {
					"enabled": false
				},
				"rp": {
					"enabled": false
				},
				"vendor": {
					"enabled": false
				},
				"ch": {
					"type": "keyword"
				},
				"message": {
					"type": "text"
				},
				"nid": {
					"type": "keyword"
				},
				"nm": {
					"type": "keyword"
				},
				"primary_id": {
					"type": "keyword"
				},
				"st": {
					"type": "long"
				},
				"tag": {
					"properties": {
						"key": {
							"type": "keyword",
							"ignore_above": 1024
						},
						"value": {
							"type": "keyword",
							"ignore_above": 1024
						}
					}
				},
				
				"stats": {
				  "type": "object",
				  "enabled": false,
				  "doc_values": true
        }
			}
			
		}
	},
		"_settings": {
    "index.mapping.total_fields.limit": 30000
    
  }
}

Please
