### ISSUE TITLE
Simple Query String Query with flag PREFIX doesnt work

### ISSUE THREAD

**Issue by spajak** [elasticsearch/elasticsearch#9767]
Is there something wrong with `flags` option to `simple_query_string` in the 2nd example? Why this query doesn't work as expected?

This works (expected results):
```
flags: "ALL",
query: "1 zloty Parchim*"
```
This doesn't work (no results):
```
flags: "PREFIX",
query: "1 zloty Parchim*"
```
This works (but useless):
```
flags: "PREFIX",
query: "Parchim*"
```
`default_operator` is `AND` in all cases.

**Comment by dakrone** [comment]
@spajak do you have an example document so I can try to reproduce this?

Also, it might be that you need to enable whitespace in the second example, using `flags: "WHITESPACE|PREFIX" so that spaces are allowed.

**Comment by spajak** [comment]
Yes. WHITESPACE is needed.
Thanks
