### ISSUE TITLE
Clarify term query/filter behavior when _type is not indexed

### ISSUE THREAD

**Issue by ppf2** [elasticsearch/elasticsearch#9782]
From http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-type-field.html#mapping-type-field:

```
The _type field can also not be indexed, and all the APIs will still work except for specific queries (term queries / filters) or faceting done on the _type field.

{
    "tweet" : {
        "_type" : {"index" : "no"}
    }
}
```

From testing, when _type is configured to not be indexed, a query like the following will still return the documents:

```
{
  "query": {
   "term": {
     "_type": {
       "value": "tweet"
     }
   }
  }
}
```

This seems to be consistent with the other documentation page on _uid (http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-uid-field.html) where it says "The _uid field is automatically used when _type is not indexed to perform type based filtering, and does not require the _id to be indexed."

But contradictory to the description provided on the _type doc page (http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-type-field.html#mapping-type-field):
"The _type field can also not be indexed, and all the APIs will still work except for specific queries (term queries / filters) or faceting done on the _type field."

**Comment by clintongormley** [comment]
This is no longer an issue as you can no longer configure the `_type` field (see https://github.com/elasticsearch/elasticsearch/pull/9869)
