### ISSUE TITLE
Is this a right way to find in nested type that a user has  four time done event e1 and has not done event e2?

### ISSUE THREAD

**Issue by sandeep-verma** [elasticsearch/elasticsearch#9785]
Below is Mapping of type user with nested event
{
   "beta": {
      "mappings": {
         "user": {
            "dynamic_templates": [
               {
                  "string_template": {
                     "mapping": {
                        "type": "string",
                        "index": "analyzed",
                        "analyzer": "string_lowercase"
                     },
                     "match": "*",
                     "match_mapping_type": "string"
                  }
               }
            ],
            "_routing": {
               "required": true,
               "path": "_shardId"
            },
            "properties": {              
               "event": {
                  "type": "nested",
                  "properties": {
                     "_date": {
                        "type": "date",
                        "format": "dateOptionalTime"
                     },
                     "count": {
                        "type": "long"
                     },
                     "first_date": {
                        "type": "date",
                        "format": "dateOptionalTime"
                     },
                     "name": {
                        "type": "string",
                        "analyzer": "string_lowercase"
                     },
                     "last_date": {
                        "type": "date",
                        "format": "dateOptionalTime"
                     }
                  }
               }
            }
         }
      }
   }
}

**Comment by clintongormley** [comment]
Hi @sandeep-verma 

Please ask questions like these in the mailing list (and you will need to provide more information than just the mapping).

thanks
