### ISSUE TITLE
Unable to set indices.query.bool.max_clause_count: 2000 or index.query.bool.max_clause_count: 2000

### ISSUE THREAD

**Issue by amalrajcharles** [elasticsearch/elasticsearch#9787]
Hi

I am unable to set max_clause_count. Even if I add indices.query.bool.max_clause_count: 2000 or index.query.bool.max_clause_count: 2000 in elasticsearch.yml. Still it is getting defaulted to 1024.

Bellow is the error message :

'PnRQe9ZOl1w6ys39TRYMJg\\=\\=') OR (assignments.assignmentKey = 'PnRQe9ZOl1w6ys39TRYMJg\\=\\=') OR (assignments.assignmentKey = 'PnRQe9ZOl1w6ys39TRYMJg\\=\\=') OR (assignments.assignmentKey = 'PnRQe9ZOl1w6ys39TRYMJg\\=\\=') OR (assignments.assignmentKey = 'PnRQe9ZOl1w6ys39TRYMJg\\=\\=') OR (assignments.assignmentKey = 'PnRQe9ZOl1w6ys39TRYMJg\\=\\=') OR (assignments.assignmentKey = 'PnRQe9ZOl1w6ys39TRYMJg\\=\\=') OR (assignments.assignmentKey = 'PnRQe9ZOl1w6ys39TRYMJg\\=\\=') OR (assignments.assignmentKey = 'PnRQe9ZOl1w6ys39TRYMJg\\=\\=') OR (assignments.assignmentKey = 'PnRQe9ZOl1w6ys39TRYMJg\\=\\=') OR (assignments.assignmentKey = 'PnRQe9ZOl1w6ys39TRYMJg\\=\\=')\r\n': too many boolean clauses]; nested: TooManyClauses[maxClauseCount is set to 1024]; }]","status":400}

Thanks,
Amalraj

**Comment by clintongormley** [comment]
Hiya

I'm struggling to make it fail with the default settings, but if I set `index.query.bool.max_clause_count` to eg `10`, then i get it to fail with (eg) a `match_phrase_prefix` query.

Perhaps you can demonstrate exactly what it is you are doing?

thanks

**Comment by amalrajcharles** [comment]
Hi,

I had not restarted the elasticsearch service. The settings works as expected.

Thanks
