### ISSUE TITLE
ElasticSearch analyzer not working with nested query

### ISSUE THREAD

**Issue by cgurjar** [elasticsearch/elasticsearch#9788]
I have created an index with the following mapping

    PUT test1
    {
      "mappings": {
        "searchText": {
          "properties": {
            "catalogue_product": {
              "type": "nested",
              "properties": {
                "id": {
                  "type": "string",
                  "index": "not_analyzed"
                },
                "long_desc": {
                  "type": "nested",
                  "properties": {
                    "translation": {
                      "type": "nested",
                      "properties": {
                        "en-GB": {
                          "type": "string",
                          "anlayzer": "snowball"
                        },
                        "fr-FR": {
                          "type": "string",
                          "anlayzer": "snowball"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

I have put one record using

    PUT /test1/searchText/1
    {
      "catalogue_product": {
        "id": "18437",
        "long_desc": {
          "translation": {
            "en-GB": "C120 - circuit breaker - C120H - 4P - 125A - B curve",
            "fr-FR": "Disjoncteur C120H 4P 125A courbe B 15000A"
          }
        }
      }
    }

Then if i do a search for the word
"breaker"
inside

"catalogue_product.long_desc.translation.en-GB"
I get the added record

    POST /test1/searchText/_search
    {
      "query": {
        "nested": {
          "path": "catalogue_product.long_desc.translation",
          "query": {
            "match": {
              "catalogue_product.long_desc.translation.en-GB": "breaker"
            }
          }
        }
      }
    }

if replace the word

"breaker"
with

"breakers"
, I dont get any records in spite of the en-GB field having analyzer=snowball in the mapping

    POST /test1/searchText/_search
    {
      "query": {
        "nested": {
          "path": "catalogue_product.long_desc.translation",
          "query": {
            "match": {
              "catalogue_product.long_desc.translation.en-GB": "breakers"
            }
          }
        }
      }
    }

I am going crazy with this. Where am I going wrong? I tried a new mapping with analyzer as english instead of snowball, but that did not work either :( Any help is appreciated

**Comment by clintongormley** [comment]
You have misspelled `analyzer`...  I have opened #9927 to warn about such issues.

btw you are seriously overusing nested fields - you don't need this many...

**Comment by cgurjar** [comment]
Why? I actually am keeping this similar to the source. I will change it only if
