### ISSUE TITLE
Awkward syntax when using a file script in a terms aggregation

### ISSUE THREAD

**Issue by ludovicc** [elasticsearch/elasticsearch#9793]
Following the release of Elasticsearch 1.4.3 and the disclosed vulnerability of Groovy, I have disabled the Groovy sandbox.
But in some places I used Groovy in some queries, for example:
````javascript
{ 
  "aggs": { 
    "result": { 
      "terms": { 
        "script": "if doc['protocol']?.value doc['protocol'].value + '/' + doc['ip_dstport'].value else doc['ip_dstport'].value" 
      } 
    } 
  } 
}
````
I tried to externalize the groovy script, store in in a file under /etc/elasticsearch/scripts/protocol_label.groovy, then use this aggregation instead, but it doesn't work:
````javascript
{ 
  "aggs": { 
    "result": { 
      "terms": { 
        "file": "protocol_label", 
        "language": "groovy" 
      } 
    } 
  } 
}
````

I found a workaround, but it does not look clean:
````javascript
{ 
  "script_fields": { 
    "dummy": { 
      "file": "protocol_label", 
      "language": "groovy" 
    } 
  },
   "aggs": { 
    "result": { 
      "terms": { 
        "file": "protocol_label", 
        "language": "groovy" 
      } 
    } 
  } 
}
````

**Comment by colings86** [comment]
@ludovicc in the aggregations you need to define file_scripts using the `script_file` parameter instead of `file`. https://github.com/elasticsearch/elasticsearch/pull/7977 standardises this across all the scriptable APIs and will be available from version 1.5

Apologies for the confusion
