### ISSUE TITLE
script_score doesn't take a script filename as argument

### ISSUE THREAD

**Issue by aolieman** [elasticsearch/elasticsearch#9805]
The [`script score`](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#_script_score) function doesn't allow for the scoring script to be loaded from a file. This is, however, paramount for sensitive applications, as described in [this blogpost](http://www.elasticsearch.org/blog/running-groovy-scripts-without-dynamic-scripting/).

@polyfractal has pointed out that the bug is that [`ScoreFunction`](https://github.com/elasticsearch/elasticsearch/blob/1.x/src/main/java/org/elasticsearch/index/query/functionscore/script/ScriptScoreFunctionParser.java#L80-L84) only uses the default inline `script` argument. It should also accept the `file` argument.

It would be nice if the `file` argument could be accepted consistently by functions that use inline scripts. For security's sake.

**Comment by clintongormley** [comment]
Hi @aolieman 

Thanks for reporting.  This has been fixed in #7977

**Comment by aolieman** [comment]
Wonderful! I'll be looking out for the fix in the change log.
