### ISSUE TITLE
creating index using uri

### ISSUE THREAD

**Issue by vahith** [elasticsearch/elasticsearch#9810]
hi,
i am trying to create an index through url without using crul command but it giving bad request,
this is code snippet which i am using               

 String url = "http://localhost:9200/product/apparel/300";
		URL obj = new URL(url);
		HttpURLConnection con = (HttpURLConnection) obj.openConnection();
 
		//add reuqest header
		con.setRequestMethod("POST");
		con.setRequestProperty("Accept-Language", "en-US,en;q=0.5");
 
		String urlParameters = "type:slide,quantity:2";

**Comment by dadoonet** [comment]
Please ask usage questions on the mailing list.
Your code has a lot of errors i'd say:

POST vs PUT
No real payload but parameters (incorrects)
Not a JSON doc

BTW why not using elasticsearch Java API?

Closing as not an issue.
