### ISSUE TITLE
Range filters, date math and time_zone

### ISSUE THREAD

**Issue by mewwts** [elasticsearch/elasticsearch#9814]
Hi guys. 

I've stumbled upon an issue. When specifying the ```time_zone``` parameters in a range filter where ```gte``` and ```lt``` are set using datemath, the time zone is not taken into account when rounding!

The following is part of a filters aggregation, and I expect to be given the week 4 weeks ago, starting on a
sunday at 23:00 UTC time, and ending on sunday 23:00 UTC time with a full week in between. 
```
{
  "filters": {
    "4w": {
      "range": {
        "timestamp": {
          "lt": "now-4w+1w/w",
          "gte": "now-4w/w",
          "time_zone": "+01:00"
        }
      }
    }
  }
}
```
But no, after inspecting the docs that are returned, there are no documents returned between the first sunday 23:00 and monday 00:00 UTC. There are however documents returned between sunday 23:00 and monday 00:00 UTC at the end of the interval.

Is this a bug? Should not timezones be included when doing rounding in date math?

**Comment by cbuescher** [comment]
Will have a look since this might or might not be related to the rounding issues recently solved in #9790.

**Comment by cbuescher** [comment]
@mewwts Which version are you running?

**Comment by cbuescher** [comment]
From a first glance: the rounding in DateMathParser (which seems to be used in range filter) is not related to the TimeZoneRounding which was subject of #9790, so I was wrong in assuming the two issues are related. Seems like rounding in DateMathParser does not take into account time zone correctly.

**Comment by mewwts** [comment]
Hi @cbuescher, thanks for your reply and quick fix!?
I'm running 1.4.2. I was going to take a look at this myself, but I can see you have beat me to it!

**Comment by mewwts** [comment]
Hands down, greatest response ever. Thanks @cbuescher. Now the wait for 1.4.5, I guess?

**Comment by cbuescher** [comment]
So far only on out main branch, but will merge with the current 1.4 branch, so after that's happened it will go into 1.4.5.

**Comment by mewwts** [comment]
Thanks, @cbuescher.

**Comment by cbuescher** [comment]
On branch 1.4 with dff19cb and on 1.x with 8391b51

**Comment by mewwts** [comment]
Thanks @cbuescher.
