### ISSUE TITLE
Type conversion possible in index template?

### ISSUE THREAD

**Issue by nithyanv** [elasticsearch/elasticsearch#9819]
Is it possible to do type conversion input documents? For exampled if the document has a field that is in quotes as "100", can it be converted into integer? I can't seem to make it work. 

>curl -XPUT http://localhost:9200/_template/mytemplate -d '{
>   "template" : "someindex*",
>   "order":    1,
>  "settings" : {
>      "index.cache.field.type" : "soft",
>     "index.refresh_interval" : "5s",
>      "index.store.compress.stored" : true
> },
>  "mappings" : {
>"_default_" : {
>"_all" : {"enabled" : false},
>"properties" : {
>"item_id" :{"type": "string", "index": "not_analyzed" },
>"item_name" : {"type": "string", "index": "not_analyzed" },
>"value" : {"type": "integer"},
>"item_location" : {
>"properties" : {
>"location" : {
>"type" : "geo_point"
>}
>}
>}
>}
>}
>}
>}
>'

Input document 

>{
>  "item_someid":"item_somename",
>  "some_value":"1",
>  "item_location":
>      {"location":"37.8098,-122.418"}
>}

**Comment by clintongormley** [comment]
Geo-points have to be mapped explicitly, or you can use name-based matching to determine which fields should be geo-points.
