### ISSUE TITLE
Template mapping

### ISSUE THREAD

**Issue by nithyanv** [elasticsearch/elasticsearch#9820]
Is there a way of dynamically generating index name in index-template mapping? Like we do in logstash by prefixing date for instance.

>curl -XPUT http://localhost:9200/template/mytemplate -d '{
>"template" : "someindex*",
>"order": 1,
>"settings" : {
>"index.store.compress.stored" : true
>},
>"mappings" : {
>"_default" : {
>"_all" : {"enabled" : false}
>}
>}
>}
>'

**Comment by clintongormley** [comment]
No there isn't - you index into a particular index name, from that we can match templates with wildcards, but we can't change the name of the index itself.
