### ISSUE TITLE
One shard on 1.3.4 -> 1.4.4 gone bad (edit: corrupted index)

### ISSUE THREAD

**Issue by tostasqb** [elasticsearch/elasticsearch#9824]
I Installed a new instance of ES 1.4.4 and copied the /data folder into the new instance. It started to get  some errors like: 
`failed to fetch index version after copying it over`(...)`Preexisting corrupted index`(...)`caused by: CorruptIndexException[codec header mismatch: actual header=0 vs expected header=1071082519`

Trying to fix this, I removed this index on the file system and tried a restore...initially the log reported ok
` restore [repo_name_2015-02-23_0000] is done` but it sent more errors right away
(...)`sending failed shard for`(...)`reason [Failed to start shard, message [IndexShardGatewayRecoveryException[[index_name][0] failed recovery]; nested: IndexShardRestoreFailedException[[index_name][0] restore failed]; nested: IndexShardRestoreFailedException[[index_name][0] failed to restore snapshot [repo_name_2015-02-23_0000]]; nested: IndexShardRestoreFailedException[[index_name][0] Failed to recover index]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=1aj2bdu actual=pebgem`

I checked for the status of the backup and it was ok:

`"index_name" : {
        "shards_stats" : {
          "initializing" : 0,
          "started" : 0,
          "finalizing" : 0,
          "done" : 1,
          "failed" : 0,
          "total" : 1
        },
        "stats" : {
          "number_of_files" : 1,
          "processed_files" : 1,
          "total_size_in_bytes" : 1529,
          "processed_size_in_bytes" : 1529,
          "start_time_in_millis" : 1424646178596,
          "time_in_millis" : 8659
        },
        "shards" : {
          "0" : {
            "stage" : "DONE",
            "stats" : {
              "number_of_files" : 1,
              "processed_files" : 1,
              "total_size_in_bytes" : 1529,
              "processed_size_in_bytes" : 1529,
              "start_time_in_millis" : 1424646178596,
              "time_in_millis" : 8659
            }
          }
        }
      },`

This happened in only one shard/index.

Any advice?

Other notes: 
1 node
93 indices
102 shards
~150 million documents
~30 GB

**Comment by tostasqb** [comment]
I have just re-installed ES 1.3.4 and tried to restore the same backup with the same result.
Guess this index is really corrupted ?. 

My question now is, how come only now this problem is showing? I back up my data daily and it was being shown on a client's application until this upgrade started...not a single error (that I have caught) until now.

**Comment by clintongormley** [comment]
Hi @tostasqb 

The 1.4 branch has many more checksum checks than before, so it is quite possible that a previously undetected corruption is only now being found.  

Sorry that this has happened to you, but given that your backups are also corrupt, I think the only thing left to do is to delete that shard.
