### ISSUE TITLE
small bug in kibana

### ISSUE THREAD

**Issue by oferoh** [elasticsearch/elasticsearch#9833]
Hi I found a small bug in kibana 3 and 4,
when i have Brackets in user name field example 
facebook (US)
facebook (DE)
in kibana object is break it to us ,de 
you can see in the picture below
![image](https://cloud.githubusercontent.com/assets/11095042/6337126/5d8dddda-bbb0-11e4-993a-c16195975323.png)

**Comment by dadoonet** [comment]
I'm sorry but I don't really understand what error you are seeing.
The screen capture does not mention the same text you are describing.

That said:

* if you have a Kibana issue, you'd better open it in Kibana project
* I think it's more a question about your mapping but still unsure as I don't understand what is exactly your issue.

**Comment by oferoh** [comment]
Thank you David,

the example wasn't so good,

the ADV_CAMPAIGN_NAME  = "KandCo(FB)" - the table below 
in the table above you can see that for some reason it split the name "KandCo"  , "fb" same count 8034

Is that clear enough?

**Comment by dadoonet** [comment]
Yes. So I confirm it's not a bug.
You should change your mapping and mark this field as not_analyzed.

**Comment by oferoh** [comment]
Dear David 
im not sure you right please see my code,
all string field are not_analyzed,

DELETE atlas_events
DELETE _river
PUT _river/atlas_events/_meta
{
    "type" : "jdbc",
    "jdbc": {
        "url":"jdbc:sqlserver://localhost;databaseName=gaya",
        "user":"elasticsearch",
        "password":"elasticsearch",
        "sql":"select * from get_data_from_exasol",
        "index" : "atlas_events",
        "type" : "clicks",
            "properties" : {
            "ADV_PROJECT_NAME" : {
      "type" :    "string",
      "index":    "not_analyzed"
    }
  }
        
    }
}
PUT atlas_events/_mapping/clicks
{
  "properties" : {
    "ADV_PROJECT_NAME" : {
      "type" :    "string",
      "index":    "not_analyzed"
    },
    "BROWSER" : {
      "type" :    "string",
      "index":    "not_analyzed"
    },
    "CREATIVE_NAME" : {
      "type" :    "string",
      "index":    "not_analyzed"
    },
    "DEVICE_CLASS_NAME" : {
      "type" :    "string",
      "index":    "not_analyzed"
    },
    "DEVICE_GROUP_NAME" : {
      "type" :    "string",
      "index":    "not_analyzed"
    },
    "OS" : {
      "type" :    "string",
      "index":    "not_analyzed"
    },
    "PRT_CAMPAIGN_NAME" : {
      "type" :    "string",
      "index":    "not_analyzed"
    },
    "PRT_PROJECT_NAME" : {
      "type" :    "string",
      "index":    "not_analyzed"
    }
  }
}

![image](https://cloud.githubusercontent.com/assets/11095042/6345157/069c88b8-bc0b-11e4-87ca-a7ca542f687e.png)

**Comment by dadoonet** [comment]
PUT atlas_events/_mapping/clicks Is incorrect.

PUT atlas_events/clicks/_mapping

Check your mapping with GET atlas_events/clicks/_mapping

**Comment by oferoh** [comment]
still not working 
I did you what you suggest,


![image](https://cloud.githubusercontent.com/assets/11095042/6346492/01fa66f0-bc19-11e4-94fa-ad71e4164686.png)


![image](https://cloud.githubusercontent.com/assets/11095042/6346399/52f146ce-bc18-11e4-88b1-7bb4591ae219.png)

![image](https://cloud.githubusercontent.com/assets/11095042/6346416/7c99ee40-bc18-11e4-9f25-a1f12d54f216.png)

**Comment by dadoonet** [comment]
What gives `GET atlas_events/clicks/_mapping`

**Comment by oferoh** [comment]
![image](https://cloud.githubusercontent.com/assets/11095042/6347876/0c7cb5e6-bc24-11e4-9e36-23c551ef2819.png)

**Comment by oferoh** [comment]
found the bug,:) 

missed the 
,
     "ADV_CAMPAIGN_NAME" : {
      "type" :    "string",
      "index":    "not_analyzed"

**Comment by oferoh** [comment]
Sorry thank you ,

**Comment by oferoh** [comment]
![image](https://cloud.githubusercontent.com/assets/11095042/6347948/9b3d0c4a-bc24-11e4-9dab-13a9a41d7cf2.png)
