### ISSUE TITLE
disable all filter cache per request

### ISSUE THREAD

**Issue by julianhille** [elasticsearch/elasticsearch#9834]
There is an option to disable query cache per request.
I would like to see an option to disable ALL filter cache per request.

We have some request, we're we know that all the filters should not be cached at all, 
but it would be rather painful to configure this for every setting in these cases.

```
curl 'localhost:9200/my_index/_search?filter_cache=fase' 
```

**Comment by clintongormley** [comment]
Hi @julianhille 

The results of the whole query are either cached or not, but filter caching is much more fine-grained, hence the need to specify filter caching per filter.  That said, you can probably forget about it as we'll be moving to automated filter caching based on reuse: https://github.com/elasticsearch/elasticsearch/pull/8573
