### ISSUE TITLE
My index is not Mapping in elastic search

### ISSUE THREAD

**Issue by Diwahars** [elasticsearch/elasticsearch#9840]
I'm moving my data from mysql to elastic search using jdbc river plugin.

its scheduled to fed data into elastic search every minute.... But when, I try to visualize the data.. Elastic search s not getting indexed with kibana...

JDBC RIVER

curl -XPUT 'localhost:9200/_river/Sample_query/_meta' -d '{
  "type" : "jdbc",
  "jdbc":{
      "url" : "jdbc:mysql://localhost/",
      "user" : "xxx",
      "password" : "xxxx",
      "strategy" : "simple",
      "poll" : "5s",
      "scale" : 0,
      "autocommit" : true,
      "fetchsize" : 10,
      "max_rows" : 0,
      "max_retries" : 3,
      "max_retries_wait" : "10s",
      "schedule": "0 0/1 * * * ?",
      "sql" :"SELECT *from clock desc limit 350;"

Index mapping:

"type_mapping": {
            "mytype" : {
                "properties": {
                        "GroupName": {
				"type": "string",
				"store": true, 
				"index" : "not_analyzed",
				"doc_values": true
			},
                        "HostsName": {
				"type": "string",
				"store": true, 
				"index" : "not_analyzed",
				"doc_values": true
			}, 
                        "DATE": {
				"type": "date",
				"store": true, 
				"doc_values": true
			},
                        "ItemsName": {
				"type": "string",
				"store": true,
				"index" : "not_analyzed",
				"doc_values": true
			},
			"Value": {
				"type": "number",
				"store": true, 
				"doc_values": true
			}
                    }
            }
        }
How to map the index in elasticsearch???

**Comment by dadoonet** [comment]
You'll get better support on the mailing list or on the JDBC plugin repo about this.

Github is only for issues or feature requests.
