### ISSUE TITLE
Completion Suggestion doesnt give integer suggestions

### ISSUE THREAD

**Issue by mathiasnohall** [elasticsearch/elasticsearch#9845]
{
"suggest":{"autocomplete":{"text":"80","completion":{"field":"pageAutoComplete","size":5}}}
}

Doesnt give any suggestions. Whereas 

{
"suggest":{"autocomplete":{"text":"st","completion":{"field":"pageAutoComplete","size":5}}}
}

works perfectly.

The field pageAutoComplete is a completion field, using simple analyzer.

Using Elastic Search 1.4.2

**Comment by clintongormley** [comment]
Hi @mathiasnohall 

The simple analyzer only keeps letters, it discards anything else (including numbers)
