### ISSUE TITLE
Elasticsearch converting float numbers when aggregating

### ISSUE THREAD

**Issue by ap0091** [elasticsearch/elasticsearch#9850]
Hello,
I have a index with multiple documents and  columns.
Two of my columns are order number and status code.
I am trying to identify all unique ordernumbers and find the highest status code within that same order_number.
For example: 
Order Number : 123 has 5 documents each with different status codes (1, 2, 3.4,5,7)
Order Number : 125 has 3 documents each with different status codes (3,6,3.3)

I have noticed that when I have a decimal number, the value gets converted to random number. For exmaple:
If a status code was 3350.2, it would get converted to 3350.199951171875

Aggs part of the query looks like:
	  "aggs" : {
		"keys" : 
			{
				"terms" : { "field" : "ol.ORDER_LINE_KEY", "size": 2500},
				"aggs" : {
					"max" : { "max" : { "field" : "ol.STATUS_CODE" } }
				}
			}
		}
	}

In ES_Head, the status code appears to be correct, it only seems to messup when doing aggs.

**Comment by jpountz** [comment]
> If a status code was 3350.2, it would get converted to 3350.199951171875

This is because:
 - aggregations always work on doubles, not floats. If you have a float, it will be casted to a double.
 - 3350.2 cannot be represented accurately as a floating-point number

Here is a code snippet (in Java but would do the same in other languages) that demonstrates the problem that you are seeing:

```java
float f = 3350.2f;
System.out.println(f); // prints 3350.2
double d = f;
System.out.println(d); // prints 3350.199951171875
d = 3350.2;
System.out.println(d); // prints 3350.2
```
