### ISSUE TITLE
Snapshot  / restore module lets you restore an index with alias that conflicts with another index on restore destination.

### ISSUE THREAD

**Issue by gheppner** [elasticsearch/elasticsearch#9857]
I've only tested this on 1.3.5, but after going through the release notes for every version since, including 1.4.x, I don't see it mentioned anywhere.

I had an index named "dev-blog" on my 1.3.5 cluster. I restored a snapshot of a "blog" index from another (1.0.1) cluster. This "blog" index had a dev-blog alias associated with it, and I forgot to tell the restore process to not restore the aliases. 

The restore completed successfully. However, I was unable to delete the dev-blog alias from the "blog" cluster. When trying to delete the alias ( curl -XDELETE 'localhost:9200/blog/_alias/dev-blog' ), this was returned instead:

{
  "error": "RemoteTransportException[[xxxxxxxx:xxxx]][indices/aliases]]; nested: InvalidAliasNameException[[blog] Invalid alias name [dev-blog], an index exists with the same name as the alias]; ",
  "status": 400
}

it was like this restore operation allowed the cluster to get into a state I could not get it out of.  To fix this, I had to snapshot the dev-blog index, delete it completely, and THEN i was able to issue the above delete command to remove the dev-blog alias from the blog index.

Either the restore needs to check if there is a collision between aliases and index names before allowing the restore to happen, or the validation step being done as part of the DELETE needs to let this proceed.

**Comment by clintongormley** [comment]
@gheppner this looks like it has been fixed in https://github.com/elasticsearch/elasticsearch/pull/7918
