### ISSUE TITLE
How to change chart label in Kibana 4

### ISSUE THREAD

**Issue by ebadul1981** [elasticsearch/elasticsearch#9858]
I have upgraded my application to Kibana 4, and generated few dashboard.
I am looking for option to change the label. by default it is coming as "Count of documents"

Can you please help me to fix this.

**Comment by s1monw** [comment]
this is the issue tracker for elasticsearch not kibana. Can you please refer to the mailing lists for questions like this, issue tracker are only for bugs and development discussions

**Comment by ebadul1981** [comment]
Can you please send me the URL/path?

**Comment by s1monw** [comment]
@rashidkpc what's the best place for this?
