### ISSUE TITLE
Unable to get _ID within aggregation.

### ISSUE THREAD

**Issue by ap0091** [elasticsearch/elasticsearch#9880]
Hello,
I have the following query

	{
	"query":
		{"bool":
			{"must":
				[	
						{ "term": {"ol.EXTN_CREATE_LOC": 8119}},
						{ "term": {"ol.DOCTYPE": "0001"}},
				]
			}
		},
		"aggs" : {
			"keys" : 
				{
					"terms" : { "field" : "ol.ORDER_LINE_KEY", "size" : 200000},
					"aggs" : 
					{
							"max" : { "max" : { "field" : "ol.STATUS_CODE" }},
							"ID" : { "value_count" : { "script" : "doc['_ID'].value" } }
							
					}
				}
			}
	}

First it filters and gets back all the results based on my query, and then the aggregation is supposed to group all documents that have similar ORDER_LINE_KEYS and then within those ORDER_LINE_KEYS they all have another field on that document that has a code (STATUS_CODE) I want to return the MAX code which it is doing, but I also need the document ID to be returned to further index from my application.

i looked around the documentation for this and am not seeing anything that can do this, is that true?

**Comment by clintongormley** [comment]
Hi @ap0091 

The `_id` (not `_ID`) isn't indexed or written as doc values, so you can't access it.  You can however use the `_uid` field (which consists of the type name plus the _id)
