### ISSUE TITLE
Are the repositories down?

### ISSUE THREAD

**Issue by nikolay** [elasticsearch/elasticsearch#9892]
Since at least yesterday, the repositories return 404s, which make my Ubuntu builds use the standard Ubuntu packages instead.

**Comment by markwalkom** [comment]
Seems ok to me;
```bash
# apt-get install elasticsearch
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  elasticsearch
0 upgraded, 1 newly installed, 0 to remove and 11 not upgraded.
Need to get 26.7 MB of archives.
After this operation, 30.6 MB of additional disk space will be used.
0% [Working]
Get:1 http://packages.elasticsearch.org/elasticsearch/1.4/debian/ stable/main elasticsearch all 1.4.4 [26.7 MB]
Fetched 26.7 MB in 25s (1,035 kB/s)
Selecting previously unselected package elasticsearch.
(Reading database ... 103016 files and directories currently installed.)
Preparing to unpack .../elasticsearch_1.4.4_all.deb ...
Unpacking elasticsearch (1.4.4) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up elasticsearch (1.4.4) ...
```

If you are getting errors, it'd help if you pasted them.

**Comment by nikolay** [comment]
Hmmm... seems to be working now.

**Comment by dadoonet** [comment]
Wondering if we have some hiccups here. @drewr WDYT?

**Comment by drewr** [comment]
Didn't get alerted to any outages (we ping from multiple datacenters around the world). Don't see any service degradations either, just the usual lull during off-peak US hours.

![screen shot 2015-02-26 at 8 50 32 am](https://cloud.githubusercontent.com/assets/6202/6394079/a8cd0fba-bd94-11e4-9aff-1e30e755419c.png)
