### ISSUE TITLE
Elasticsearch 1.4.4 not working with elasticsearch-cloud-aws 2.4.1

### ISSUE THREAD

**Issue by nikolay** [elasticsearch/elasticsearch#9894]
After a simple installation of Elasticsearch on Ubuntu using the repository and then doing:
```bash
/usr/share/elasticsearch/bin/plugin --install elasticsearch/elasticsearch-cloud-aws/2.4.1
```
which finishes successfully. After that, starting Elasticsearch gives the error that a mandatory plugin (`elasticsearch-cloud-aws`) is missing.

**Comment by dadoonet** [comment]
Sounds like you defined mandatory plugins in your `elasticsearch.yml` file.
Remove this or if you need to check for mandatory plugins, actual name for AWS is `cloud-aws`.

**Comment by nikolay** [comment]
@dadoonet Thanks, it works now! But `elasticsearch-cloud-aws` used to work on `1.4.2`.

**Comment by dadoonet** [comment]
@nikolay really? I can't recall we change anything on that. Any chance you could test it with `1.4.2`, exact same configuration as before?
