### ISSUE TITLE
mapping : allow user to change mappings on indices with existing data

### ISSUE THREAD

**Issue by sweetest** [elasticsearch/elasticsearch#9896]
All of a sudden I came up with this idea that it would be nice to make mappings changeable even after I have documents indexed.

Reason why, somehow I want to change the mapping but the only way to do that currently is to remove index and reindex them, which is quite burdensome.

Well, I just want to ask your opinion first about this.

**Comment by clintongormley** [comment]
sorry @sweetest, this ain't happening :)  You can add mappings, but you can't change existing mappings without rewriting all of the existing data.

However, we are planning a reindex API which will make that process easier.
