### ISSUE TITLE
Unable to use JSON query string with SearchRequestBuilder (Elasticsearch 1.4.2 & 1.4.4)

### ISSUE THREAD

**Issue by cooniur** [elasticsearch/elasticsearch#9910]
Previously, I use the following code to query Elasticsearch using JSON string (code is in Groovy):

		Settings settings = ImmutableSettings.settingsBuilder().put("cluster.name", "elasticsearch").build();
		Client client = new TransportClient(settings).addTransportAddress(new InetSocketTransportAddress("localhost", "9300"));

		String jsonQuery = """{"query":{"filtered":{"filter":{"term":{"_id":"100"}}}}}"""
		SearchRequestBuilder request = client.prepareSearch("twitter")
				.setTypes("data")
				.setSource(jsonQuery)

		SearchResponse response = request.execute().actionGet()

As you can read from the above, I want to filter the documents to find one with `_id=100`. Now it returns all documents, totally ignoring my query.

If I use `QueryBuilders`, I get ClassNoFoundException, which is described here: https://github.com/elasticsearch/elasticsearch/issues/9891

If I use `setExtraSource()`, it works. But `setSource()` was working before (from November 2014 till yesterday). And according to the documentation, it is the method that can be used to set JSON query string.

Here is my dependencies:

	<properties>
		<java.version>1.8</java.version>
		<plugin.groovy-eclipse-compiler>2.9.0-01</plugin.groovy-eclipse-compiler>
		<plugin.groovy-eclipse-batch>2.3.4-01</plugin.groovy-eclipse-batch>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch</artifactId>
			<version>1.4.2</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy-all</artifactId>
			<version>2.4.1</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.10</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.1.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-all</artifactId>
			<version>1.3</version>
		</dependency>
	</dependencies>

It can be reproduced on my colleague's environment, too. We both use Oracle JDK 8 (1.8.0_31) on Mac. IDEs are Eclipse (his) and IntelliJ (mine).

Tested on Elasticsearch 1.4.2 & 1.4.4, both failed.

**Comment by cooniur** [comment]
Hi, @dadoonet 
This is another issue happens at the same time as the other one.

**Comment by jprante** [comment]
I can not reproduce. This script works for me:

```
@GrabResolver(name='maven', root='http://repo1.maven.org/maven2/')
@Grab(group='org.elasticsearch', module='elasticsearch', version='1.4.4')
import org.elasticsearch.common.settings.Settings
import org.elasticsearch.common.settings.ImmutableSettings
import org.elasticsearch.common.transport.InetSocketTransportAddress
import org.elasticsearch.client.Client
import org.elasticsearch.client.transport.TransportClient
import org.elasticsearch.action.index.IndexRequestBuilder
import org.elasticsearch.action.index.IndexResponse
import org.elasticsearch.action.search.SearchRequestBuilder
import org.elasticsearch.action.search.SearchResponse

Settings settings = ImmutableSettings.settingsBuilder().put("cluster.name", "elasticsearch").build();
Client client = new TransportClient(settings).addTransportAddress(new InetSocketTransportAddress("localhost", 9300));

String body = """{"name":"Hello world"}"""
IndexRequestBuilder indexRequestBuilder = new IndexRequestBuilder(client, "twitter")
            .setType("data")
            .setId("1")
            .setSource(body)
            .setRefresh(true)
IndexResponse indexResponse = indexRequestBuilder.execute().actionGet()

String jsonQuery = """{"query":{"filtered":{"filter":{"term":{"_id":"1"}}}}}"""
SearchRequestBuilder requestBuilder = client.prepareSearch("twitter")
            .setTypes("data")
            .setSource(jsonQuery)

SearchResponse response = requestBuilder.execute().actionGet() 

println response.toString()
```

JVM / Groovy version

```
[joerg@localhost ~]$ groovy --version
Groovy Version: 2.4.1 JVM: 1.8.0_31 Vendor: Oracle Corporation OS: Linux
```

**Comment by cooniur** [comment]
@jprante 
Thank you for the reproduce try!

Actually, could you index a few another documents with different ids (say `id=2, 3, 4, ...`), and do the filtered query (`_id=1`) again to see whether the response is the only one document with `id=1` or all the other documents?

In my case, I got all the documents back instead of the one that I filtered.

**Comment by jprante** [comment]
@coonuir it makes no difference, works as expected here.

```
@GrabResolver(name='maven', root='http://repo1.maven.org/maven2/')
@Grab(group='org.elasticsearch', module='elasticsearch', version='1.4.4')
import org.elasticsearch.common.settings.Settings
import org.elasticsearch.common.settings.ImmutableSettings
import org.elasticsearch.common.transport.InetSocketTransportAddress
import org.elasticsearch.client.Client
import org.elasticsearch.client.transport.TransportClient
import org.elasticsearch.action.index.IndexRequestBuilder
import org.elasticsearch.action.index.IndexResponse
import org.elasticsearch.action.search.SearchRequestBuilder
import org.elasticsearch.action.search.SearchResponse

Settings settings = ImmutableSettings.settingsBuilder().put("cluster.name", "elasticsearch").build();
Client client = new TransportClient(settings).addTransportAddress(new InetSocketTransportAddress("localhost", 9300));

[1,2,3,4].each() {
    String body = """{"name":"Hello world ${it}"}"""
    IndexRequestBuilder indexRequestBuilder = new IndexRequestBuilder(client, "twitter")
            .setType("data")
            .setId(it.toString())
            .setSource(body)
            .setRefresh(true)
    IndexResponse indexResponse = indexRequestBuilder.execute().actionGet()
}

String jsonQuery = """{"query":{"filtered":{"filter":{"term":{"_id":"1"}}}}}"""
SearchRequestBuilder requestBuilder = client.prepareSearch("twitter")
            .setTypes("data")
            .setSource(jsonQuery)

SearchResponse response = requestBuilder.execute().actionGet()

println response.toString()
```

**Comment by cooniur** [comment]
@jprante 
I found one tiny difference between your code and my code:

if you add `println requestBuilder` before you execute it, the response would be incorrect.

Try the following and let me know whether you can get the document you filtered (i.e. `id=1`):

  SearchRequestBuilder requestBuilder = client.prepareSearch("twitter")
            .setTypes("data")
            .setSource(jsonQuery)
  println requestBuilder.toString()

  SearchResponse response = requestBuilder.execute().actionGet()
  println response.toString()
