### ISSUE TITLE
Max # of documents per shard

### ISSUE THREAD

**Issue by ppf2** [elasticsearch/elasticsearch#9911]
Would be nice to document this:

Lucene has a limit on the max # of documents per Lucene index (which is Integer.MAX_VALUE-1 : https://issues.apache.org/jira/browse/LUCENE-5843).  Which means that a shard in Elasticsearch also cannot exceed the same limit when it comes to the max # of documents per shard.    Certainly, we don't advise having a gigantic shard of this size to begin with (can affect recovery speeds and performance, etc..), but it will be nice to at least document the limitation.

**Comment by clintongormley** [comment]
@ppf2 how about a PR?

**Comment by ppf2** [comment]
Ok done @clintongormley :) https://github.com/elasticsearch/elasticsearch/pull/9932

**Comment by clintongormley** [comment]
Closed by #9932
