### ISSUE TITLE
[Documentation] Threading Model for SearchRequest

### ISSUE THREAD

**Issue by sathishk** [elasticsearch/elasticsearch#9917]
As per Documentation in the site [http://www.elasticsearch.org/guide/en/elasticsearch/client/java-api/current/search.html#_operation_threading_3], We shall set the Threading Model for SearchRequest. 

But the latest SearchRequest.java (https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/action/search/SearchRequest.java) does not have any method to set this value.

However, This seems to be available in the older version of the SearchRequest.java (https://github.com/medcl/elasticsearch/blob/185f5a9e1811893f19ac4679dfe7900ef84705f9/modules/elasticsearch/src/main/java/org/elasticsearch/action/search/SearchRequest.java)

Is this Option removed recently ? Is there any update needed in the documentation ?

**Comment by clintongormley** [comment]
Hi @sathishk 

yes it was removed in 1.2.0.  I've remove it from the documentation. thanks for reporting
