### ISSUE TITLE
elasticsearch can't get data from mongodb using in docker

### ISSUE THREAD

**Issue by hordemark** [elasticsearch/elasticsearch#9918]
I had install mongodb river and head plugin in the docker.
When i execute the following code, it can't synchronize data from mongodb.
But it can work well not use docker.
Anybody get trouble ?

<code>
curl -XPUT 'http://127.0.0.1:9200/_river/mongodb_source/_meta' -d '{ 
    "type": "mongodb", 
    "mongodb": {
      "db": "andes", 
      "collection": "source",
      "host": "192.168.90.46",
      "port": "27017"      
    }, 
    "index": {
      "name": "mongoindex_source", 
      "type": "source" 
    }
  }'
</code>

**Comment by clintongormley** [comment]
Hi @hordemark 

Please ask questions like these on the mailing list, or on the site which supports the mongo river.

thanks
