### ISSUE TITLE
Aggregations and fielddata caching behavior after filtering

### ISSUE THREAD

**Issue by amreha2002** [elasticsearch/elasticsearch#9920]
I'm working with terms aggregations. I've 100M+ documents in one index with 100+ types. I'm trying to run the aggs query on one single type with only hundreds of docs.
Everytime I run this query:
1- It takes a lot of time 3-4 minutes 
2- It blocks the cache, preventing other queries to run on the node till the cache is manually cleared.

I tried using all types of filters, filtered, filter agg, querystring, match query, terms aggs with tiny size and shard_size, even the post filter. But still the field data cache ignores whats mentioned in any of these and caches that field for all documents in that index.

According to ES documentation, this functionality was intentionally made as a sort of search prediction for later queries.
["The logic is: if you need access to documents X, Y, and Z for this query, you will probably need access to other documents in the next query. It is cheaper to load all values once, and to keep them in memory, than to have to scan the inverted index on every request."]
(http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_limiting_memory_usage.html)

I found a lot of alternatives but still I am not sure if any of them will solve my problem:
1- Creating an index for every type (Still the filtering won't work but at least it will only cache 1 type not all other types)
2- Using doc values instead caching in memory (Much slower, Cache will never get blocked, doesn't support working with text field yet, so it's useless in my case)
3- Expanding the memory, sharding, creating other nodes and giving a lot of space for the cache ( It will still be slow as I run more than 10 different aggs query, every query has a different field than the previous one. So the cache will always miss and every time I run a query it will take a lot of time to fill the cache that might get dropped on the next query to fill it with a new field)

Is there any workaround to disable that feature or at least an older version of ES that doesn't support  it? Any help on this issue would be really appreciated.

**Comment by clintongormley** [comment]
Hi @amreha2002 

This is the way that fielddata has worked from the beginning. Nothing has changed.  If you want to run a terms agg on an analyzed string field, then you need to load into memory the values of that field for all the documents in your index.  No exceptions.

> 2- Using doc values instead caching in memory (Much slower, Cache will never get blocked, doesn't support working with text field yet, so it's useless in my case)

Note: doc values DO work with string fields, as long as they are `not_analyzed`.  Do you really need to run all of these aggs on analyzed string fields?  Also note: they are **slightly** slower than fielddata, not much slower.  You should really consider using doc values.

Another option for analyzed text fields is to use fielddata filtering, to only load the most interesting terms into memory (eg not very common terms and not very uncommon terms)

But if you say you only want to run this on a few hundred docs, then putting them into their own index makes that easy.
