### ISSUE TITLE
Throw an exception if field mapping is invalid

### ISSUE THREAD

**Issue by clintongormley** [elasticsearch/elasticsearch#9927]
Currently we silently ignore invalid field mappings, eg:

    PUT test1
    {
      "mappings": {
        "searchText": {
          "properties": {
            "foo": {
              "type": "string",
              "anlayzer": "snowball",
              "foo": "bar"
            }
          }
        }
      }
    }

We should throw an exception instead.

Related to #8870

**Comment by colings86** [comment]
@clintongormley this should have been solved in https://github.com/elasticsearch/elasticsearch/pull/7534 (pushed only to master). If we have missed a case this issue should be re-labelled as a bug

**Comment by clintongormley** [comment]
@colings86 it is fixed in master - thanks, closing
