### ISSUE TITLE
[TESTS] Make sure test end with ..Tests

### ISSUE THREAD

**Issue by brwe** [elasticsearch/elasticsearch#9945]
We currently filter test classes by suffix `Test` or `Tests` (https://github.com/elasticsearch/elasticsearch/blob/master/pom.xml#L495), but there is no automation in place to guarantee that test classes actually end with this suffix. As a result, some tests did not run on CI without anyone noticing (see for example https://github.com/elasticsearch/elasticsearch/commit/600cb886da0b8a4adae9a3a0eb688697c10c1491). Would be great if we had some automation that checks that classes that derive from Test classes like `ElasticsearchIntegrationTest` have the right suffix.

**Comment by javanna** [comment]
+1 I think we should rather take `ElasticsearchTestCase` as the base class though.

**Comment by martijnvg** [comment]
Or if a test class has '@Test' then the class name must end with *Test

**Comment by javanna** [comment]
@martijnvg I'm afraid we don't use the `@Test` annotation consistently though... we better look also for method names that start with `test` if we take that approach.

**Comment by martijnvg** [comment]
Yes, we take this approach we should also look for method names starting with `test`. I think we either should the test method name consistently or the test annotation, but that is a different discussion.

**Comment by s1monw** [comment]
thanks so much @brwe for finding this... `das glück des tüchtigen...`
