### ISSUE TITLE
Empty document allows multiple usage of same "_id"

### ISSUE THREAD

**Issue by christtonk** [elasticsearch/elasticsearch#9948]
My test scenario is the following:
I am using parent <=> child relations in order to connect my documents. Usually I am using empty documents where I set the "_id" field as parent. All children are connected to this document.

What I figured out is: If a document is empty I can save the same document with the same "_id" multiple times. Also this document shows up multiple times in the index. If I add a field to this document I get a "document already exists" exception (this is what I would expect) when I want to insert the document multiple times.

Is this a bug?

**Comment by clintongormley** [comment]
@christtonk Can you provide a recreation demonstrating what you are doing please?  If you're using different parent IDs for each child document, then this is expected.

**Comment by christtonk** [comment]
@clintongormley I am using the Java API ... I will extract the code that looks suspicious to me ... just need some time.

**Comment by clintongormley** [comment]
If you could provide the demonstration as curl statements, it would be easier.

**Comment by christtonk** [comment]
@clintongormley Somehow I cannot reproduce it with curl statements ... but with my Java Code I can

**Comment by christtonk** [comment]
OK, figured out what is happening and I think the mistake is on my side: I am using routing extensively. What I am able to do is: inserting the same document into the same index with the same "_id" but with different routing information twice without getting a document already exists exception. What I understood so far is that this is the correct behavior.

**Comment by clintongormley** [comment]
Yes, this is correct.  The default `_routing` value is the `_id`, so if you change that (by specifying a parent or routing value) then it is up to you to ensure that you don't reuse the same `_id` on a different shard.
