### ISSUE TITLE
Logs being sent to a closed index cause logstash to lock up

### ISSUE THREAD

**Issue by efontana** [elasticsearch/elasticsearch#9950]
When sending logs (via logstash) if the log is sent to a closed index, there is no good error message reported and it causes logstash to lock up? Is there a solution for this?

**Comment by clintongormley** [comment]
Hi @efontana 

Trying to index into a closed index returns a 403 status code and:

    { "error" : "IndexClosedException[[my_index] closed]", "status": 403 }

...which seems pretty self-explanatory.  Perhaps logstash isn't checking for this error but should be?

@jordansissel ^^

**Comment by jordansissel** [comment]
This belongs on logstash, not elasticsearch. @efontana can you move this to logstash-plugins/logstash-output-elasticsearch?

**Comment by clintongormley** [comment]
thanks @jordansissel - closing
