### ISSUE TITLE
Very high disk read io when bulk

### ISSUE THREAD

**Issue by sylvae** [elasticsearch/elasticsearch#9951]
We have about 95 nodes in our cluster,and index have 89 shards.
We send bulk requests to these nodes random,total about 1 million per seconds.

Every thing is good except some nodes(about 5~10) have very high disk read io:
Device:         rrqm/s   wrqm/s     r/s     w/s   rsec/s   wsec/s avgrq-sz avgqu-sz   await  svctm  %util
sdh               0.00     0.50 19739.00   18.00 573624.00  3128.00    29.19    75.48    3.82   0.05 100.00
sdg               0.00     0.00 10850.00    0.00 298556.00     0.00    27.52     4.26    0.39   0.06  65.30

but other nodes are normal,they have very little read io:
Device:         rrqm/s   wrqm/s     r/s     w/s   rsec/s   wsec/s avgrq-sz avgqu-sz   await  svctm  %util
sdh               0.00     0.50    0.00   41.00     0.00  8964.00   218.63     0.22    5.45   0.23   0.95
sdg               0.00     0.00    1.50    0.00    12.00     0.00     8.00     0.00    0.00   0.00   0.00

I think this is very abnormal,there is not other process except  ES ,and the disk is not bad.
I look the index codes ,it seems that only the "loadVersion" function need to read the disk,but how can it use so many read io? Please help ,thanks very much.

**Comment by clintongormley** [comment]
what version of ES are you using?  And do the hot nodes have more primary shards than others?  Also, how many shards per node in total?

**Comment by sylvae** [comment]
I am using ES 1.4.2. I have set  "index.routing.allocation.total_shards_per_node": "3", so the
number of the primary shards is almost the same. We create one index per day, and import today's data to it. Every index has 89 shards and 1 replic. Also, no search at the time.

**Comment by sylvae** [comment]
I have found the reason，it was not the ES's bug.It was because of too much memory fragmentation and memory recall.

**Comment by milodky** [comment]
Hey @sylvae , I have the exact issue, how you solved this?

**Comment by stephanustedy** [comment]
how to solve this issue ? have you guys solve it ? 
@milodky @sylvae

**Comment by gilinachum** [comment]
@milodky @sylvae @stephanustedy have you guys solved it? do you remember what it was? facing similar symptoms with ES 5.4.2.

**Comment by whitejava** [comment]
same problem with 5.0.2

**Comment by ZhiqinYang** [comment]
me too

**Comment by qiangyin** [comment]
same problem with 5.6.6

**Comment by gilinachum** [comment]
How we resolved it:
1. Refactored application logic to reduce the amount of document overwrites and deletes, which reduces merges.
2. On AWS switching from R3 with local storage machines to I3 machines with local storage did wonders and eliminated the issue.

**Comment by qiangyin** [comment]
> 
> 
> How we resolved it:
> 
>     1. Refactored application logic to reduce the amount of document overwrites and deletes, which reduces merges.
> 
>     2. On AWS switching instance type from R3 with local storage machines to [I3](https://aws.amazon.com/ec2/instance-types/i3/) with local storage did wonders and eliminated the issue.
thanks a lot

**Comment by mehar** [comment]
> I have found the reason，it was not the ES's bug.It was because of too much memory fragmentation and memory recall.

How did you establish this? We seem to have a similar problem
