### ISSUE TITLE
Feature Request: ability to limit which fields are included for each "hit"

### ISSUE THREAD

**Issue by scottbessler** [elasticsearch/elasticsearch#9957]
I am running a `_search` (with a sort) and hoping to just get the _id's back. Unfortunately I get a ton of extra, mostly redundant, and mostly useless fields that I can't seem to disable.

```javascript
      {
        "_index": "itemview_v2_2015_01_20_15_13_38",
        "_type": "itemview",
        "_id": "list.4ecc2e933434af4976729cc9:54f406ece4b0e900509d3cd9",
        "_score": null,
        "sort": [
          1425352613566,
          "asdf"
        ]
      }
```

It would be great if I could return JUST an array of `{"_id":"..."}` or even better, an array of the id values themselves.

**Comment by clintongormley** [comment]
Closing in favour of #7401
