### ISSUE TITLE
[doc] query string syntax : small typo in range example

### ISSUE THREAD

**Issue by daniel-menard** [elasticsearch/elasticsearch#9965]
Hi!

Reading the docs, I think I found a small typo on page http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_ranges_2:

> Curly and square brackets can be combined:
> - Numbers from 1 up to but not including 5
>
>   `count:[1..5}`

Shouldn't it be `count:[1 TO 5}`?

(but I would love if ".." was supported!)

**Comment by clintongormley** [comment]
thanks @daniel-menard 

you're correct, i've fixed the docs.
