### ISSUE TITLE
Zen Ping_timeout inconsistent documentation

### ISSUE THREAD

**Issue by dharshanr** [elasticsearch/elasticsearch#9974]
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-discovery-zen.html

Is the default value 3s or 30s?

"ping_timeout - How long to wait for a ping response, defaults to 30s."

"The discovery.zen.ping_timeout (which defaults to 3s) allows for the tweaking of election time"

**Comment by clintongormley** [comment]
These refer to two different settings:

    discovery.zen.ping_timeout  (default 3s)
    discovery.zen.fd.ping_timeout (default 30s)
