### ISSUE TITLE
All index info lost when the original master machines are not participating in master election

### ISSUE THREAD

**Issue by mkliu** [elasticsearch/elasticsearch#9975]
It appears to be as resiliency problem, and i haven't seen it mentioned any place obvious so hopeful it could get fixed.

We had a problem recently about master nodes failing, so I enabled my data nodes to serve as master too - dualnode. However, even though the cluster name is the same, i don't see any of my previous indexes anymore! After quite a while I realize probably because the global cluster status is saved on master node's disk, so the new dualnode doesn't know. I switched back to the old masters when they come back up, then indexes appeared again, but many of them are in red state....

My question would be, since the index and segments are still on the data node, why can't the dualnode detect the indexes that's already in the cluster?

This is really a nasty trap...

**Comment by clintongormley** [comment]
Hi @mkliu 

Yes agreed. We are working on a change which will write the cluster state to data-only nodes too, to avoid this problem.  See https://github.com/elasticsearch/elasticsearch/pull/9952
