### ISSUE TITLE
Elastic search sort on number filed gives error 

### ISSUE THREAD

**Issue by dibeesh** [elasticsearch/elasticsearch#9977]
Facing problem when sorting an integer parameter Elastic search 1.3.7, status variable is causing problem, I have status field with different mapping in another collection. Does this effect?
Mapping 
{
"outboxprov1": {
"mappings": {
"deleted_user": {
"properties": {
"status": {
"type": "integer"
}
}
}
}
}
}
Query 
POST /outboxprov1/deleted_user/_search
{
"sort": [
{
"status": {
"order": "desc"
}
}
], 
"query": {
"match_all": {
}
}
}
Error

{
"error": "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[0kPf5NYmRlC15ov89wjQ2g][outboxprov1][0]: QueryPhaseExecutionException[[outboxprov1][0]: query[ConstantScore(cache(_type:user))],from[0],size[10],sort[!]: Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }{[0kPf5NYmRlC15ov89wjQ2g][outboxprov1][1]: QueryPhaseExecutionException[[outboxprov1][1]: query[ConstantScore(cache(_type:user))],from[0],size[10],sort[!]: Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }{[0kPf5NYmRlC15ov89wjQ2g][outboxprov1][2]: QueryPhaseExecutionException[[outboxprov1][2]: query[ConstantScore(cache(_type:user))],from[0],size[10],sort[!]: Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }{[0kPf5NYmRlC15ov89wjQ2g][outboxprov1][3]: QueryPhaseExecutionException[[outboxprov1][3]: query[ConstantScore(cache(_type:user))],from[0],size[10],sort[!]: Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }{[0kPf5NYmRlC15ov89wjQ2g][outboxprov1][4]: QueryPhaseExecutionException[[outboxprov1][4]: query[ConstantScore(cache(_type:user))],from[0],size[10],sort[!]: Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }]",
"status": 500
}

**Comment by clintongormley** [comment]
@dibeesh please see https://github.com/elasticsearch/elasticsearch/issues/9191#issuecomment-77784022
