### ISSUE TITLE
Getting Elasticsearch to work on Windows 2008 64bit

### ISSUE THREAD

**Issue by apilgrimda** [elasticsearch/elasticsearch#9983]
I am following the below link and when I try to open http://127.0.0.1:9200/ i get a pop-up asking for a program to open 127_0_0_1.json. Please help!!

Thank you

**Comment by clintongormley** [comment]
Hi @apilgrimda 

Please ask questions like these on the mailing list. The github issues list is for bug reports and feature requests.
